---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: networking
    io.seedmatic.rke2lab/package: kdns
  labels:
    app.kubernetes.io/instance: kdns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kdns
    helm.sh/chart: kdns-0.2.3
  name: kdns
  namespace: rke2lab-system
