---
apiVersion: v1
data:
  members: |-
    helm.cattle.io/v1|HelmChart|kube-system|github-token-manager
    v1|Secret|rke2lab-system|github-app-private-key
    github.as-code.io/v1|App|rke2lab-system|github-app
    github.as-code.io/v1|ClusterToken||github-token
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: platform
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: github-token-manager
  name: github-token-manager.group
