// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.incus.inputs.GetCertificateArgs;
import com.pulumi.incus.inputs.GetCertificatePlainArgs;
import com.pulumi.incus.inputs.GetClusterArgs;
import com.pulumi.incus.inputs.GetClusterPlainArgs;
import com.pulumi.incus.inputs.GetImageArgs;
import com.pulumi.incus.inputs.GetImagePlainArgs;
import com.pulumi.incus.inputs.GetInstanceArgs;
import com.pulumi.incus.inputs.GetInstancePlainArgs;
import com.pulumi.incus.inputs.GetNetworkAclArgs;
import com.pulumi.incus.inputs.GetNetworkAclPlainArgs;
import com.pulumi.incus.inputs.GetNetworkAddressSetArgs;
import com.pulumi.incus.inputs.GetNetworkAddressSetPlainArgs;
import com.pulumi.incus.inputs.GetNetworkArgs;
import com.pulumi.incus.inputs.GetNetworkForwardArgs;
import com.pulumi.incus.inputs.GetNetworkForwardPlainArgs;
import com.pulumi.incus.inputs.GetNetworkIntegrationArgs;
import com.pulumi.incus.inputs.GetNetworkIntegrationPlainArgs;
import com.pulumi.incus.inputs.GetNetworkLoadBalancerArgs;
import com.pulumi.incus.inputs.GetNetworkLoadBalancerPlainArgs;
import com.pulumi.incus.inputs.GetNetworkPeerArgs;
import com.pulumi.incus.inputs.GetNetworkPeerPlainArgs;
import com.pulumi.incus.inputs.GetNetworkPlainArgs;
import com.pulumi.incus.inputs.GetNetworkZoneArgs;
import com.pulumi.incus.inputs.GetNetworkZonePlainArgs;
import com.pulumi.incus.inputs.GetProfileArgs;
import com.pulumi.incus.inputs.GetProfilePlainArgs;
import com.pulumi.incus.inputs.GetProjectArgs;
import com.pulumi.incus.inputs.GetProjectPlainArgs;
import com.pulumi.incus.inputs.GetStorageBucketArgs;
import com.pulumi.incus.inputs.GetStorageBucketPlainArgs;
import com.pulumi.incus.inputs.GetStoragePoolArgs;
import com.pulumi.incus.inputs.GetStoragePoolPlainArgs;
import com.pulumi.incus.inputs.GetStorageVolumeArgs;
import com.pulumi.incus.inputs.GetStorageVolumePlainArgs;
import com.pulumi.incus.outputs.GetCertificateResult;
import com.pulumi.incus.outputs.GetClusterResult;
import com.pulumi.incus.outputs.GetImageResult;
import com.pulumi.incus.outputs.GetInstanceResult;
import com.pulumi.incus.outputs.GetNetworkAclResult;
import com.pulumi.incus.outputs.GetNetworkAddressSetResult;
import com.pulumi.incus.outputs.GetNetworkForwardResult;
import com.pulumi.incus.outputs.GetNetworkIntegrationResult;
import com.pulumi.incus.outputs.GetNetworkLoadBalancerResult;
import com.pulumi.incus.outputs.GetNetworkPeerResult;
import com.pulumi.incus.outputs.GetNetworkResult;
import com.pulumi.incus.outputs.GetNetworkZoneResult;
import com.pulumi.incus.outputs.GetProfileResult;
import com.pulumi.incus.outputs.GetProjectResult;
import com.pulumi.incus.outputs.GetStorageBucketResult;
import com.pulumi.incus.outputs.GetStoragePoolResult;
import com.pulumi.incus.outputs.GetStorageVolumeResult;
import java.util.concurrent.CompletableFuture;

public final class IncusFunctions {
  public static Output<GetCertificateResult> getCertificate(GetCertificateArgs args) {
    return getCertificate(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetCertificateResult> getCertificatePlain(
      GetCertificatePlainArgs args) {
    return getCertificatePlain(args, InvokeOptions.Empty);
  }

  public static Output<GetCertificateResult> getCertificate(
      GetCertificateArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getCertificate:getCertificate",
            TypeShape.of(GetCertificateResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetCertificateResult> getCertificate(
      GetCertificateArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getCertificate:getCertificate",
            TypeShape.of(GetCertificateResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetCertificateResult> getCertificatePlain(
      GetCertificatePlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getCertificate:getCertificate",
            TypeShape.of(GetCertificateResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetClusterResult> getCluster() {
    return getCluster(GetClusterArgs.Empty, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetClusterResult> getClusterPlain() {
    return getClusterPlain(GetClusterPlainArgs.Empty, InvokeOptions.Empty);
  }

  public static Output<GetClusterResult> getCluster(GetClusterArgs args) {
    return getCluster(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetClusterResult> getClusterPlain(GetClusterPlainArgs args) {
    return getClusterPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetClusterResult> getCluster(GetClusterArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getCluster:getCluster",
            TypeShape.of(GetClusterResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetClusterResult> getCluster(
      GetClusterArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getCluster:getCluster",
            TypeShape.of(GetClusterResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetClusterResult> getClusterPlain(
      GetClusterPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getCluster:getCluster",
            TypeShape.of(GetClusterResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetImageResult> getImage() {
    return getImage(GetImageArgs.Empty, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetImageResult> getImagePlain() {
    return getImagePlain(GetImagePlainArgs.Empty, InvokeOptions.Empty);
  }

  public static Output<GetImageResult> getImage(GetImageArgs args) {
    return getImage(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetImageResult> getImagePlain(GetImagePlainArgs args) {
    return getImagePlain(args, InvokeOptions.Empty);
  }

  public static Output<GetImageResult> getImage(GetImageArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getImage:getImage",
            TypeShape.of(GetImageResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetImageResult> getImage(GetImageArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getImage:getImage",
            TypeShape.of(GetImageResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetImageResult> getImagePlain(
      GetImagePlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getImage:getImage",
            TypeShape.of(GetImageResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetInstanceResult> getInstance(GetInstanceArgs args) {
    return getInstance(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetInstanceResult> getInstancePlain(GetInstancePlainArgs args) {
    return getInstancePlain(args, InvokeOptions.Empty);
  }

  public static Output<GetInstanceResult> getInstance(GetInstanceArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getInstance:getInstance",
            TypeShape.of(GetInstanceResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetInstanceResult> getInstance(
      GetInstanceArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getInstance:getInstance",
            TypeShape.of(GetInstanceResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetInstanceResult> getInstancePlain(
      GetInstancePlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getInstance:getInstance",
            TypeShape.of(GetInstanceResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkResult> getNetwork(GetNetworkArgs args) {
    return getNetwork(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetNetworkResult> getNetworkPlain(GetNetworkPlainArgs args) {
    return getNetworkPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetNetworkResult> getNetwork(GetNetworkArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetwork:getNetwork",
            TypeShape.of(GetNetworkResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkResult> getNetwork(
      GetNetworkArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetwork:getNetwork",
            TypeShape.of(GetNetworkResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetNetworkResult> getNetworkPlain(
      GetNetworkPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getNetwork:getNetwork",
            TypeShape.of(GetNetworkResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkAclResult> getNetworkAcl(GetNetworkAclArgs args) {
    return getNetworkAcl(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetNetworkAclResult> getNetworkAclPlain(
      GetNetworkAclPlainArgs args) {
    return getNetworkAclPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetNetworkAclResult> getNetworkAcl(
      GetNetworkAclArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkAcl:getNetworkAcl",
            TypeShape.of(GetNetworkAclResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkAclResult> getNetworkAcl(
      GetNetworkAclArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkAcl:getNetworkAcl",
            TypeShape.of(GetNetworkAclResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetNetworkAclResult> getNetworkAclPlain(
      GetNetworkAclPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getNetworkAcl:getNetworkAcl",
            TypeShape.of(GetNetworkAclResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkAddressSetResult> getNetworkAddressSet(
      GetNetworkAddressSetArgs args) {
    return getNetworkAddressSet(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetNetworkAddressSetResult> getNetworkAddressSetPlain(
      GetNetworkAddressSetPlainArgs args) {
    return getNetworkAddressSetPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetNetworkAddressSetResult> getNetworkAddressSet(
      GetNetworkAddressSetArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkAddressSet:getNetworkAddressSet",
            TypeShape.of(GetNetworkAddressSetResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkAddressSetResult> getNetworkAddressSet(
      GetNetworkAddressSetArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkAddressSet:getNetworkAddressSet",
            TypeShape.of(GetNetworkAddressSetResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetNetworkAddressSetResult> getNetworkAddressSetPlain(
      GetNetworkAddressSetPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getNetworkAddressSet:getNetworkAddressSet",
            TypeShape.of(GetNetworkAddressSetResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkForwardResult> getNetworkForward(GetNetworkForwardArgs args) {
    return getNetworkForward(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetNetworkForwardResult> getNetworkForwardPlain(
      GetNetworkForwardPlainArgs args) {
    return getNetworkForwardPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetNetworkForwardResult> getNetworkForward(
      GetNetworkForwardArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkForward:getNetworkForward",
            TypeShape.of(GetNetworkForwardResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkForwardResult> getNetworkForward(
      GetNetworkForwardArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkForward:getNetworkForward",
            TypeShape.of(GetNetworkForwardResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetNetworkForwardResult> getNetworkForwardPlain(
      GetNetworkForwardPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getNetworkForward:getNetworkForward",
            TypeShape.of(GetNetworkForwardResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkIntegrationResult> getNetworkIntegration(
      GetNetworkIntegrationArgs args) {
    return getNetworkIntegration(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetNetworkIntegrationResult> getNetworkIntegrationPlain(
      GetNetworkIntegrationPlainArgs args) {
    return getNetworkIntegrationPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetNetworkIntegrationResult> getNetworkIntegration(
      GetNetworkIntegrationArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkIntegration:getNetworkIntegration",
            TypeShape.of(GetNetworkIntegrationResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkIntegrationResult> getNetworkIntegration(
      GetNetworkIntegrationArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkIntegration:getNetworkIntegration",
            TypeShape.of(GetNetworkIntegrationResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetNetworkIntegrationResult> getNetworkIntegrationPlain(
      GetNetworkIntegrationPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getNetworkIntegration:getNetworkIntegration",
            TypeShape.of(GetNetworkIntegrationResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkLoadBalancerResult> getNetworkLoadBalancer(
      GetNetworkLoadBalancerArgs args) {
    return getNetworkLoadBalancer(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetNetworkLoadBalancerResult> getNetworkLoadBalancerPlain(
      GetNetworkLoadBalancerPlainArgs args) {
    return getNetworkLoadBalancerPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetNetworkLoadBalancerResult> getNetworkLoadBalancer(
      GetNetworkLoadBalancerArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkLoadBalancer:getNetworkLoadBalancer",
            TypeShape.of(GetNetworkLoadBalancerResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkLoadBalancerResult> getNetworkLoadBalancer(
      GetNetworkLoadBalancerArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkLoadBalancer:getNetworkLoadBalancer",
            TypeShape.of(GetNetworkLoadBalancerResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetNetworkLoadBalancerResult> getNetworkLoadBalancerPlain(
      GetNetworkLoadBalancerPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getNetworkLoadBalancer:getNetworkLoadBalancer",
            TypeShape.of(GetNetworkLoadBalancerResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkPeerResult> getNetworkPeer(GetNetworkPeerArgs args) {
    return getNetworkPeer(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetNetworkPeerResult> getNetworkPeerPlain(
      GetNetworkPeerPlainArgs args) {
    return getNetworkPeerPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetNetworkPeerResult> getNetworkPeer(
      GetNetworkPeerArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkPeer:getNetworkPeer",
            TypeShape.of(GetNetworkPeerResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkPeerResult> getNetworkPeer(
      GetNetworkPeerArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkPeer:getNetworkPeer",
            TypeShape.of(GetNetworkPeerResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetNetworkPeerResult> getNetworkPeerPlain(
      GetNetworkPeerPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getNetworkPeer:getNetworkPeer",
            TypeShape.of(GetNetworkPeerResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkZoneResult> getNetworkZone(GetNetworkZoneArgs args) {
    return getNetworkZone(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetNetworkZoneResult> getNetworkZonePlain(
      GetNetworkZonePlainArgs args) {
    return getNetworkZonePlain(args, InvokeOptions.Empty);
  }

  public static Output<GetNetworkZoneResult> getNetworkZone(
      GetNetworkZoneArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkZone:getNetworkZone",
            TypeShape.of(GetNetworkZoneResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetNetworkZoneResult> getNetworkZone(
      GetNetworkZoneArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getNetworkZone:getNetworkZone",
            TypeShape.of(GetNetworkZoneResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetNetworkZoneResult> getNetworkZonePlain(
      GetNetworkZonePlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getNetworkZone:getNetworkZone",
            TypeShape.of(GetNetworkZoneResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetProfileResult> getProfile(GetProfileArgs args) {
    return getProfile(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetProfileResult> getProfilePlain(GetProfilePlainArgs args) {
    return getProfilePlain(args, InvokeOptions.Empty);
  }

  public static Output<GetProfileResult> getProfile(GetProfileArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getProfile:getProfile",
            TypeShape.of(GetProfileResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetProfileResult> getProfile(
      GetProfileArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getProfile:getProfile",
            TypeShape.of(GetProfileResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetProfileResult> getProfilePlain(
      GetProfilePlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getProfile:getProfile",
            TypeShape.of(GetProfileResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetProjectResult> getProject(GetProjectArgs args) {
    return getProject(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetProjectResult> getProjectPlain(GetProjectPlainArgs args) {
    return getProjectPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetProjectResult> getProject(GetProjectArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getProject:getProject",
            TypeShape.of(GetProjectResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetProjectResult> getProject(
      GetProjectArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getProject:getProject",
            TypeShape.of(GetProjectResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetProjectResult> getProjectPlain(
      GetProjectPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getProject:getProject",
            TypeShape.of(GetProjectResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetStorageBucketResult> getStorageBucket(GetStorageBucketArgs args) {
    return getStorageBucket(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetStorageBucketResult> getStorageBucketPlain(
      GetStorageBucketPlainArgs args) {
    return getStorageBucketPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetStorageBucketResult> getStorageBucket(
      GetStorageBucketArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getStorageBucket:getStorageBucket",
            TypeShape.of(GetStorageBucketResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetStorageBucketResult> getStorageBucket(
      GetStorageBucketArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getStorageBucket:getStorageBucket",
            TypeShape.of(GetStorageBucketResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetStorageBucketResult> getStorageBucketPlain(
      GetStorageBucketPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getStorageBucket:getStorageBucket",
            TypeShape.of(GetStorageBucketResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetStoragePoolResult> getStoragePool(GetStoragePoolArgs args) {
    return getStoragePool(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetStoragePoolResult> getStoragePoolPlain(
      GetStoragePoolPlainArgs args) {
    return getStoragePoolPlain(args, InvokeOptions.Empty);
  }

  public static Output<GetStoragePoolResult> getStoragePool(
      GetStoragePoolArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getStoragePool:getStoragePool",
            TypeShape.of(GetStoragePoolResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetStoragePoolResult> getStoragePool(
      GetStoragePoolArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getStoragePool:getStoragePool",
            TypeShape.of(GetStoragePoolResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetStoragePoolResult> getStoragePoolPlain(
      GetStoragePoolPlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getStoragePool:getStoragePool",
            TypeShape.of(GetStoragePoolResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetStorageVolumeResult> getStorageVolume(GetStorageVolumeArgs args) {
    return getStorageVolume(args, InvokeOptions.Empty);
  }

  public static CompletableFuture<GetStorageVolumeResult> getStorageVolumePlain(
      GetStorageVolumePlainArgs args) {
    return getStorageVolumePlain(args, InvokeOptions.Empty);
  }

  public static Output<GetStorageVolumeResult> getStorageVolume(
      GetStorageVolumeArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getStorageVolume:getStorageVolume",
            TypeShape.of(GetStorageVolumeResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static Output<GetStorageVolumeResult> getStorageVolume(
      GetStorageVolumeArgs args, InvokeOutputOptions options) {
    return Deployment.getInstance()
        .invoke(
            "incus:index/getStorageVolume:getStorageVolume",
            TypeShape.of(GetStorageVolumeResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }

  public static CompletableFuture<GetStorageVolumeResult> getStorageVolumePlain(
      GetStorageVolumePlainArgs args, InvokeOptions options) {
    return Deployment.getInstance()
        .invokeAsync(
            "incus:index/getStorageVolume:getStorageVolume",
            TypeShape.of(GetStorageVolumeResult.class),
            args,
            Utilities.withVersion(options),
            Utilities.getPackageRef());
  }
}
