// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.incus.inputs.InstanceDeviceArgs;
import com.pulumi.incus.inputs.InstanceExecArgs;
import com.pulumi.incus.inputs.InstanceFileArgs;
import com.pulumi.incus.inputs.InstanceSourceInstanceArgs;
import com.pulumi.incus.inputs.InstanceWaitForArgs;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class InstanceArgs extends com.pulumi.resources.ResourceArgs {

  public static final InstanceArgs Empty = new InstanceArgs();

  @Import(name = "architecture")
  private @Nullable Output<String> architecture;

  public Optional<Output<String>> architecture() {
    return Optional.ofNullable(this.architecture);
  }

  @Import(name = "config")
  private @Nullable Output<Map<String, String>> config;

  public Optional<Output<Map<String, String>>> config() {
    return Optional.ofNullable(this.config);
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  /** Profile device */
  @Import(name = "devices")
  private @Nullable Output<List<InstanceDeviceArgs>> devices;

  /**
   * @return Profile device
   */
  public Optional<Output<List<InstanceDeviceArgs>>> devices() {
    return Optional.ofNullable(this.devices);
  }

  @Import(name = "ephemeral")
  private @Nullable Output<Boolean> ephemeral;

  public Optional<Output<Boolean>> ephemeral() {
    return Optional.ofNullable(this.ephemeral);
  }

  @Import(name = "exec")
  private @Nullable Output<Map<String, InstanceExecArgs>> exec;

  public Optional<Output<Map<String, InstanceExecArgs>>> exec() {
    return Optional.ofNullable(this.exec);
  }

  /** Upload file to instance */
  @Import(name = "files")
  private @Nullable Output<List<InstanceFileArgs>> files;

  /**
   * @return Upload file to instance
   */
  public Optional<Output<List<InstanceFileArgs>>> files() {
    return Optional.ofNullable(this.files);
  }

  @Import(name = "image")
  private @Nullable Output<String> image;

  public Optional<Output<String>> image() {
    return Optional.ofNullable(this.image);
  }

  @Import(name = "name")
  private @Nullable Output<String> name;

  public Optional<Output<String>> name() {
    return Optional.ofNullable(this.name);
  }

  @Import(name = "profiles")
  private @Nullable Output<List<String>> profiles;

  public Optional<Output<List<String>>> profiles() {
    return Optional.ofNullable(this.profiles);
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "running")
  private @Nullable Output<Boolean> running;

  public Optional<Output<Boolean>> running() {
    return Optional.ofNullable(this.running);
  }

  @Import(name = "sourceFile")
  private @Nullable Output<String> sourceFile;

  public Optional<Output<String>> sourceFile() {
    return Optional.ofNullable(this.sourceFile);
  }

  @Import(name = "sourceInstance")
  private @Nullable Output<InstanceSourceInstanceArgs> sourceInstance;

  public Optional<Output<InstanceSourceInstanceArgs>> sourceInstance() {
    return Optional.ofNullable(this.sourceInstance);
  }

  @Import(name = "target")
  private @Nullable Output<String> target;

  public Optional<Output<String>> target() {
    return Optional.ofNullable(this.target);
  }

  @Import(name = "type")
  private @Nullable Output<String> type;

  public Optional<Output<String>> type() {
    return Optional.ofNullable(this.type);
  }

  /** Wait for instance to be ready */
  @Import(name = "waitFors")
  private @Nullable Output<List<InstanceWaitForArgs>> waitFors;

  /**
   * @return Wait for instance to be ready
   */
  public Optional<Output<List<InstanceWaitForArgs>>> waitFors() {
    return Optional.ofNullable(this.waitFors);
  }

  private InstanceArgs() {}

  private InstanceArgs(InstanceArgs $) {
    this.architecture = $.architecture;
    this.config = $.config;
    this.description = $.description;
    this.devices = $.devices;
    this.ephemeral = $.ephemeral;
    this.exec = $.exec;
    this.files = $.files;
    this.image = $.image;
    this.name = $.name;
    this.profiles = $.profiles;
    this.project = $.project;
    this.remote = $.remote;
    this.running = $.running;
    this.sourceFile = $.sourceFile;
    this.sourceInstance = $.sourceInstance;
    this.target = $.target;
    this.type = $.type;
    this.waitFors = $.waitFors;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(InstanceArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private InstanceArgs $;

    public Builder() {
      $ = new InstanceArgs();
    }

    public Builder(InstanceArgs defaults) {
      $ = new InstanceArgs(Objects.requireNonNull(defaults));
    }

    public Builder architecture(@Nullable Output<String> architecture) {
      $.architecture = architecture;
      return this;
    }

    public Builder architecture(String architecture) {
      return architecture(Output.of(architecture));
    }

    public Builder config(@Nullable Output<Map<String, String>> config) {
      $.config = config;
      return this;
    }

    public Builder config(Map<String, String> config) {
      return config(Output.of(config));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    /**
     * @param devices Profile device
     * @return builder
     */
    public Builder devices(@Nullable Output<List<InstanceDeviceArgs>> devices) {
      $.devices = devices;
      return this;
    }

    /**
     * @param devices Profile device
     * @return builder
     */
    public Builder devices(List<InstanceDeviceArgs> devices) {
      return devices(Output.of(devices));
    }

    /**
     * @param devices Profile device
     * @return builder
     */
    public Builder devices(InstanceDeviceArgs... devices) {
      return devices(List.of(devices));
    }

    public Builder ephemeral(@Nullable Output<Boolean> ephemeral) {
      $.ephemeral = ephemeral;
      return this;
    }

    public Builder ephemeral(Boolean ephemeral) {
      return ephemeral(Output.of(ephemeral));
    }

    public Builder exec(@Nullable Output<Map<String, InstanceExecArgs>> exec) {
      $.exec = exec;
      return this;
    }

    public Builder exec(Map<String, InstanceExecArgs> exec) {
      return exec(Output.of(exec));
    }

    /**
     * @param files Upload file to instance
     * @return builder
     */
    public Builder files(@Nullable Output<List<InstanceFileArgs>> files) {
      $.files = files;
      return this;
    }

    /**
     * @param files Upload file to instance
     * @return builder
     */
    public Builder files(List<InstanceFileArgs> files) {
      return files(Output.of(files));
    }

    /**
     * @param files Upload file to instance
     * @return builder
     */
    public Builder files(InstanceFileArgs... files) {
      return files(List.of(files));
    }

    public Builder image(@Nullable Output<String> image) {
      $.image = image;
      return this;
    }

    public Builder image(String image) {
      return image(Output.of(image));
    }

    public Builder name(@Nullable Output<String> name) {
      $.name = name;
      return this;
    }

    public Builder name(String name) {
      return name(Output.of(name));
    }

    public Builder profiles(@Nullable Output<List<String>> profiles) {
      $.profiles = profiles;
      return this;
    }

    public Builder profiles(List<String> profiles) {
      return profiles(Output.of(profiles));
    }

    public Builder profiles(String... profiles) {
      return profiles(List.of(profiles));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public Builder running(@Nullable Output<Boolean> running) {
      $.running = running;
      return this;
    }

    public Builder running(Boolean running) {
      return running(Output.of(running));
    }

    public Builder sourceFile(@Nullable Output<String> sourceFile) {
      $.sourceFile = sourceFile;
      return this;
    }

    public Builder sourceFile(String sourceFile) {
      return sourceFile(Output.of(sourceFile));
    }

    public Builder sourceInstance(@Nullable Output<InstanceSourceInstanceArgs> sourceInstance) {
      $.sourceInstance = sourceInstance;
      return this;
    }

    public Builder sourceInstance(InstanceSourceInstanceArgs sourceInstance) {
      return sourceInstance(Output.of(sourceInstance));
    }

    public Builder target(@Nullable Output<String> target) {
      $.target = target;
      return this;
    }

    public Builder target(String target) {
      return target(Output.of(target));
    }

    public Builder type(@Nullable Output<String> type) {
      $.type = type;
      return this;
    }

    public Builder type(String type) {
      return type(Output.of(type));
    }

    /**
     * @param waitFors Wait for instance to be ready
     * @return builder
     */
    public Builder waitFors(@Nullable Output<List<InstanceWaitForArgs>> waitFors) {
      $.waitFors = waitFors;
      return this;
    }

    /**
     * @param waitFors Wait for instance to be ready
     * @return builder
     */
    public Builder waitFors(List<InstanceWaitForArgs> waitFors) {
      return waitFors(Output.of(waitFors));
    }

    /**
     * @param waitFors Wait for instance to be ready
     * @return builder
     */
    public Builder waitFors(InstanceWaitForArgs... waitFors) {
      return waitFors(List.of(waitFors));
    }

    public InstanceArgs build() {
      return $;
    }
  }
}
