// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.incus.inputs.InstanceState;
import com.pulumi.incus.outputs.InstanceDevice;
import com.pulumi.incus.outputs.InstanceExec;
import com.pulumi.incus.outputs.InstanceFile;
import com.pulumi.incus.outputs.InstanceInterfaces;
import com.pulumi.incus.outputs.InstanceSourceInstance;
import com.pulumi.incus.outputs.InstanceWaitFor;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type = "incus:index/instance:Instance")
public class Instance extends com.pulumi.resources.CustomResource {
  @Export(
      name = "architecture",
      refs = {String.class},
      tree = "[0]")
  private Output<String> architecture;

  public Output<String> architecture() {
    return this.architecture;
  }

  @Export(
      name = "config",
      refs = {Map.class, String.class},
      tree = "[0,1,1]")
  private Output<Map<String, String>> config;

  public Output<Map<String, String>> config() {
    return this.config;
  }

  @Export(
      name = "description",
      refs = {String.class},
      tree = "[0]")
  private Output<String> description;

  public Output<String> description() {
    return this.description;
  }

  /** Profile device */
  @Export(
      name = "devices",
      refs = {List.class, InstanceDevice.class},
      tree = "[0,1]")
  private Output</* @Nullable */ List<InstanceDevice>> devices;

  /**
   * @return Profile device
   */
  public Output<Optional<List<InstanceDevice>>> devices() {
    return Codegen.optional(this.devices);
  }

  @Export(
      name = "ephemeral",
      refs = {Boolean.class},
      tree = "[0]")
  private Output<Boolean> ephemeral;

  public Output<Boolean> ephemeral() {
    return this.ephemeral;
  }

  @Export(
      name = "exec",
      refs = {Map.class, String.class, InstanceExec.class},
      tree = "[0,1,2]")
  private Output</* @Nullable */ Map<String, InstanceExec>> exec;

  public Output<Optional<Map<String, InstanceExec>>> exec() {
    return Codegen.optional(this.exec);
  }

  /** Upload file to instance */
  @Export(
      name = "files",
      refs = {List.class, InstanceFile.class},
      tree = "[0,1]")
  private Output</* @Nullable */ List<InstanceFile>> files;

  /**
   * @return Upload file to instance
   */
  public Output<Optional<List<InstanceFile>>> files() {
    return Codegen.optional(this.files);
  }

  @Export(
      name = "image",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> image;

  public Output<Optional<String>> image() {
    return Codegen.optional(this.image);
  }

  /** Map of the instance network interfaces */
  @Export(
      name = "interfaces",
      refs = {Map.class, String.class, InstanceInterfaces.class},
      tree = "[0,1,2]")
  private Output<Map<String, InstanceInterfaces>> interfaces;

  /**
   * @return Map of the instance network interfaces
   */
  public Output<Map<String, InstanceInterfaces>> interfaces() {
    return this.interfaces;
  }

  @Export(
      name = "ipv4Address",
      refs = {String.class},
      tree = "[0]")
  private Output<String> ipv4Address;

  public Output<String> ipv4Address() {
    return this.ipv4Address;
  }

  @Export(
      name = "ipv6Address",
      refs = {String.class},
      tree = "[0]")
  private Output<String> ipv6Address;

  public Output<String> ipv6Address() {
    return this.ipv6Address;
  }

  @Export(
      name = "macAddress",
      refs = {String.class},
      tree = "[0]")
  private Output<String> macAddress;

  public Output<String> macAddress() {
    return this.macAddress;
  }

  @Export(
      name = "name",
      refs = {String.class},
      tree = "[0]")
  private Output<String> name;

  public Output<String> name() {
    return this.name;
  }

  @Export(
      name = "profiles",
      refs = {List.class, String.class},
      tree = "[0,1]")
  private Output<List<String>> profiles;

  public Output<List<String>> profiles() {
    return this.profiles;
  }

  @Export(
      name = "project",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> project;

  public Output<Optional<String>> project() {
    return Codegen.optional(this.project);
  }

  @Export(
      name = "remote",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> remote;

  public Output<Optional<String>> remote() {
    return Codegen.optional(this.remote);
  }

  @Export(
      name = "running",
      refs = {Boolean.class},
      tree = "[0]")
  private Output<Boolean> running;

  public Output<Boolean> running() {
    return this.running;
  }

  @Export(
      name = "sourceFile",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> sourceFile;

  public Output<Optional<String>> sourceFile() {
    return Codegen.optional(this.sourceFile);
  }

  @Export(
      name = "sourceInstance",
      refs = {InstanceSourceInstance.class},
      tree = "[0]")
  private Output</* @Nullable */ InstanceSourceInstance> sourceInstance;

  public Output<Optional<InstanceSourceInstance>> sourceInstance() {
    return Codegen.optional(this.sourceInstance);
  }

  @Export(
      name = "status",
      refs = {String.class},
      tree = "[0]")
  private Output<String> status;

  public Output<String> status() {
    return this.status;
  }

  @Export(
      name = "target",
      refs = {String.class},
      tree = "[0]")
  private Output<String> target;

  public Output<String> target() {
    return this.target;
  }

  @Export(
      name = "type",
      refs = {String.class},
      tree = "[0]")
  private Output<String> type;

  public Output<String> type() {
    return this.type;
  }

  /** Wait for instance to be ready */
  @Export(
      name = "waitFors",
      refs = {List.class, InstanceWaitFor.class},
      tree = "[0,1]")
  private Output</* @Nullable */ List<InstanceWaitFor>> waitFors;

  /**
   * @return Wait for instance to be ready
   */
  public Output<Optional<List<InstanceWaitFor>>> waitFors() {
    return Codegen.optional(this.waitFors);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   */
  public Instance(java.lang.String name) {
    this(name, InstanceArgs.Empty);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   */
  public Instance(java.lang.String name, @Nullable InstanceArgs args) {
    this(name, args, null);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param options A bag of options that control this resource's behavior.
   */
  public Instance(
      java.lang.String name,
      @Nullable InstanceArgs args,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/instance:Instance",
        name,
        makeArgs(args, options),
        makeResourceOptions(options, Codegen.empty()),
        false,
        Utilities.getPackageRef());
  }

  private Instance(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable InstanceState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/instance:Instance",
        name,
        state,
        makeResourceOptions(options, id),
        false,
        Utilities.getPackageRef());
  }

  private static InstanceArgs makeArgs(
      @Nullable InstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
    if (options != null && options.getUrn().isPresent()) {
      return null;
    }
    return args == null ? InstanceArgs.Empty : args;
  }

  private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(
      @Nullable com.pulumi.resources.CustomResourceOptions options,
      @Nullable Output<java.lang.String> id) {
    var defaultOptions =
        com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
    return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
  }

  /**
   * Get an existing Host resource's state with the given name, ID, and optional extra properties
   * used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state
   * @param options Optional settings to control the behavior of the CustomResource.
   */
  public static Instance get(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable InstanceState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    return new Instance(name, id, state, options);
  }
}
