// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.incus.inputs.StorageVolumeFileArgs;
import com.pulumi.incus.inputs.StorageVolumeSourceVolumeArgs;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class StorageVolumeArgs extends com.pulumi.resources.ResourceArgs {

  public static final StorageVolumeArgs Empty = new StorageVolumeArgs();

  @Import(name = "config")
  private @Nullable Output<Map<String, String>> config;

  public Optional<Output<Map<String, String>>> config() {
    return Optional.ofNullable(this.config);
  }

  @Import(name = "contentType")
  private @Nullable Output<String> contentType;

  public Optional<Output<String>> contentType() {
    return Optional.ofNullable(this.contentType);
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  /** Upload file to storage volume */
  @Import(name = "files")
  private @Nullable Output<List<StorageVolumeFileArgs>> files;

  /**
   * @return Upload file to storage volume
   */
  public Optional<Output<List<StorageVolumeFileArgs>>> files() {
    return Optional.ofNullable(this.files);
  }

  @Import(name = "name")
  private @Nullable Output<String> name;

  public Optional<Output<String>> name() {
    return Optional.ofNullable(this.name);
  }

  @Import(name = "pool", required = true)
  private Output<String> pool;

  public Output<String> pool() {
    return this.pool;
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "sourceFile")
  private @Nullable Output<String> sourceFile;

  public Optional<Output<String>> sourceFile() {
    return Optional.ofNullable(this.sourceFile);
  }

  @Import(name = "sourceVolume")
  private @Nullable Output<StorageVolumeSourceVolumeArgs> sourceVolume;

  public Optional<Output<StorageVolumeSourceVolumeArgs>> sourceVolume() {
    return Optional.ofNullable(this.sourceVolume);
  }

  @Import(name = "target")
  private @Nullable Output<String> target;

  public Optional<Output<String>> target() {
    return Optional.ofNullable(this.target);
  }

  @Import(name = "type")
  private @Nullable Output<String> type;

  public Optional<Output<String>> type() {
    return Optional.ofNullable(this.type);
  }

  private StorageVolumeArgs() {}

  private StorageVolumeArgs(StorageVolumeArgs $) {
    this.config = $.config;
    this.contentType = $.contentType;
    this.description = $.description;
    this.files = $.files;
    this.name = $.name;
    this.pool = $.pool;
    this.project = $.project;
    this.remote = $.remote;
    this.sourceFile = $.sourceFile;
    this.sourceVolume = $.sourceVolume;
    this.target = $.target;
    this.type = $.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(StorageVolumeArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private StorageVolumeArgs $;

    public Builder() {
      $ = new StorageVolumeArgs();
    }

    public Builder(StorageVolumeArgs defaults) {
      $ = new StorageVolumeArgs(Objects.requireNonNull(defaults));
    }

    public Builder config(@Nullable Output<Map<String, String>> config) {
      $.config = config;
      return this;
    }

    public Builder config(Map<String, String> config) {
      return config(Output.of(config));
    }

    public Builder contentType(@Nullable Output<String> contentType) {
      $.contentType = contentType;
      return this;
    }

    public Builder contentType(String contentType) {
      return contentType(Output.of(contentType));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    /**
     * @param files Upload file to storage volume
     * @return builder
     */
    public Builder files(@Nullable Output<List<StorageVolumeFileArgs>> files) {
      $.files = files;
      return this;
    }

    /**
     * @param files Upload file to storage volume
     * @return builder
     */
    public Builder files(List<StorageVolumeFileArgs> files) {
      return files(Output.of(files));
    }

    /**
     * @param files Upload file to storage volume
     * @return builder
     */
    public Builder files(StorageVolumeFileArgs... files) {
      return files(List.of(files));
    }

    public Builder name(@Nullable Output<String> name) {
      $.name = name;
      return this;
    }

    public Builder name(String name) {
      return name(Output.of(name));
    }

    public Builder pool(Output<String> pool) {
      $.pool = pool;
      return this;
    }

    public Builder pool(String pool) {
      return pool(Output.of(pool));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public Builder sourceFile(@Nullable Output<String> sourceFile) {
      $.sourceFile = sourceFile;
      return this;
    }

    public Builder sourceFile(String sourceFile) {
      return sourceFile(Output.of(sourceFile));
    }

    public Builder sourceVolume(@Nullable Output<StorageVolumeSourceVolumeArgs> sourceVolume) {
      $.sourceVolume = sourceVolume;
      return this;
    }

    public Builder sourceVolume(StorageVolumeSourceVolumeArgs sourceVolume) {
      return sourceVolume(Output.of(sourceVolume));
    }

    public Builder target(@Nullable Output<String> target) {
      $.target = target;
      return this;
    }

    public Builder target(String target) {
      return target(Output.of(target));
    }

    public Builder type(@Nullable Output<String> type) {
      $.type = type;
      return this;
    }

    public Builder type(String type) {
      return type(Output.of(type));
    }

    public StorageVolumeArgs build() {
      if ($.pool == null) {
        throw new MissingRequiredPropertyException("StorageVolumeArgs", "pool");
      }
      return $;
    }
  }
}
