// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.incus.inputs.StorageVolumeState;
import com.pulumi.incus.outputs.StorageVolumeFile;
import com.pulumi.incus.outputs.StorageVolumeSourceVolume;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type = "incus:index/storageVolume:StorageVolume")
public class StorageVolume extends com.pulumi.resources.CustomResource {
  @Export(
      name = "config",
      refs = {Map.class, String.class},
      tree = "[0,1,1]")
  private Output<Map<String, String>> config;

  public Output<Map<String, String>> config() {
    return this.config;
  }

  @Export(
      name = "contentType",
      refs = {String.class},
      tree = "[0]")
  private Output<String> contentType;

  public Output<String> contentType() {
    return this.contentType;
  }

  @Export(
      name = "description",
      refs = {String.class},
      tree = "[0]")
  private Output<String> description;

  public Output<String> description() {
    return this.description;
  }

  /** Upload file to storage volume */
  @Export(
      name = "files",
      refs = {List.class, StorageVolumeFile.class},
      tree = "[0,1]")
  private Output</* @Nullable */ List<StorageVolumeFile>> files;

  /**
   * @return Upload file to storage volume
   */
  public Output<Optional<List<StorageVolumeFile>>> files() {
    return Codegen.optional(this.files);
  }

  @Export(
      name = "location",
      refs = {String.class},
      tree = "[0]")
  private Output<String> location;

  public Output<String> location() {
    return this.location;
  }

  @Export(
      name = "name",
      refs = {String.class},
      tree = "[0]")
  private Output<String> name;

  public Output<String> name() {
    return this.name;
  }

  @Export(
      name = "pool",
      refs = {String.class},
      tree = "[0]")
  private Output<String> pool;

  public Output<String> pool() {
    return this.pool;
  }

  @Export(
      name = "project",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> project;

  public Output<Optional<String>> project() {
    return Codegen.optional(this.project);
  }

  @Export(
      name = "remote",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> remote;

  public Output<Optional<String>> remote() {
    return Codegen.optional(this.remote);
  }

  @Export(
      name = "sourceFile",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> sourceFile;

  public Output<Optional<String>> sourceFile() {
    return Codegen.optional(this.sourceFile);
  }

  @Export(
      name = "sourceVolume",
      refs = {StorageVolumeSourceVolume.class},
      tree = "[0]")
  private Output</* @Nullable */ StorageVolumeSourceVolume> sourceVolume;

  public Output<Optional<StorageVolumeSourceVolume>> sourceVolume() {
    return Codegen.optional(this.sourceVolume);
  }

  @Export(
      name = "target",
      refs = {String.class},
      tree = "[0]")
  private Output<String> target;

  public Output<String> target() {
    return this.target;
  }

  @Export(
      name = "type",
      refs = {String.class},
      tree = "[0]")
  private Output<String> type;

  public Output<String> type() {
    return this.type;
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   */
  public StorageVolume(java.lang.String name) {
    this(name, StorageVolumeArgs.Empty);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   */
  public StorageVolume(java.lang.String name, StorageVolumeArgs args) {
    this(name, args, null);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param options A bag of options that control this resource's behavior.
   */
  public StorageVolume(
      java.lang.String name,
      StorageVolumeArgs args,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/storageVolume:StorageVolume",
        name,
        makeArgs(args, options),
        makeResourceOptions(options, Codegen.empty()),
        false,
        Utilities.getPackageRef());
  }

  private StorageVolume(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable StorageVolumeState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/storageVolume:StorageVolume",
        name,
        state,
        makeResourceOptions(options, id),
        false,
        Utilities.getPackageRef());
  }

  private static StorageVolumeArgs makeArgs(
      StorageVolumeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
    if (options != null && options.getUrn().isPresent()) {
      return null;
    }
    return args == null ? StorageVolumeArgs.Empty : args;
  }

  private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(
      @Nullable com.pulumi.resources.CustomResourceOptions options,
      @Nullable Output<java.lang.String> id) {
    var defaultOptions =
        com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
    return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
  }

  /**
   * Get an existing Host resource's state with the given name, ID, and optional extra properties
   * used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state
   * @param options Optional settings to control the behavior of the CustomResource.
   */
  public static StorageVolume get(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable StorageVolumeState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    return new StorageVolume(name, id, state, options);
  }
}
