---
apiVersion: v1
data:
  members: helm.cattle.io/v1|HelmChart|kube-system|cert-manager
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: platform
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: cert-manager
  name: cert-manager.group
