---
apiVersion: cluster.seedmatic.io/v1alpha1
kind: NodeImage
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-management
  name: bioskop-mgmt-node-base
  namespace: rke2lab-bioskop-mgmt
spec:
  alias: node-base
  buildChecksum: c229eb3e257859c631b4c96de8f62e07ad56e7fa270c4127fbc9c383c74910f7
  fingerprint: 077320b4ba5454ddd9196705d0582555b1bc7600ccb8df3dc2aae3bca301883a
  rke2Version: v1.34.10+rke2r1
  runtime:
    kernelModules:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - netlink_diag
    - nf_nat
    - overlay
    - br_netfilter
    - xt_socket
    - xfrm_user
    - nft_compat
    - xt_mark
    - xt_CT
    - xt_TPROXY
    - xt_comment
    - xt_conntrack
    rawLXC: |-
      lxc.mount.auto = proc:rw sys:rw cgroup:rw
      lxc.apparmor.profile = unconfined
      lxc.cap.drop =
    security:
      interceptBPF: true
      interceptBPFDevices: true
      nesting: true
      privileged: true
  source:
    endpoint: https://nixos.bioskop:8443
    project: rke2lab
