---
apiVersion: cluster.seedmatic.io/v1alpha1
kind: PoolIntention
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-management
  name: bioskop-mgmt-control-node
  namespace: rke2lab-bioskop-mgmt
spec:
  clusterRef: bioskop-mgmt
  controlPlaneEndpoint:
    host: 10.80.7.10
    port: 6443
  image:
    fingerprint: 030d237c98ac0958aee720694d3ae6eab20a94787f82227c4e7d7ef24d918113
  kubeVIPVersion: v0.9.2
  namespace: rke2lab-bioskop-mgmt
  nodes:
  - name: bioskop-mgmt-master
  pool: control-node
  rke2Version: v1.34.10+rke2r1
  role: control-plane
