---
apiVersion: cluster.seedmatic.io/v1alpha1
kind: PoolIntention
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-management
  name: bioskop-mgmt-control-node
  namespace: rke2lab-bioskop-mgmt
spec:
  clusterRef: bioskop-mgmt
  controlPlaneEndpoint:
    host: 10.80.7.10
    port: 6443
  image:
    fingerprint: 75037325b2a8dfd79f0ba662a042a3dfbce0b7b22d6a90a8abab103178065536
  namespace: rke2lab-bioskop-mgmt
  nodeLabels:
  - flox.seedmatic.io/enabled=true
  nodes:
  - name: bioskop-mgmt-master
  pool: control-node
  rke2Version: v1.34.10+rke2r1
  role: control-plane
