---
apiVersion: cluster.seedmatic.io/v1alpha1
kind: PoolIntention
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-management
  name: bioskop-mgmt-control-node
  namespace: rke2lab-bioskop-mgmt
spec:
  clusterRef: bioskop-mgmt
  controlPlaneEndpoint:
    host: 10.80.7.10
    port: 6443
  image:
    fingerprint: a37534b42e00e38fb69b5c42da928f450e22221815009d37ad290b034257edac
  namespace: rke2lab-bioskop-mgmt
  nodes:
  - name: bioskop-mgmt-master
  pool: control-node
  rke2Version: v1.34.10+rke2r1
  role: control-plane
