---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: rke2lab-system/flox-controller-webhook-serving
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: flox-webhook
  name: flox-controller
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: flox-controller-webhook
      namespace: rke2lab-system
      path: /mutate--v1-pod
      port: 443
  failurePolicy: Ignore
  name: flox-inject.flox.seedmatic.io
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-public
      - kube-node-lease
      - flux-system
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 5
