---
apiVersion: v1
data:
  members: |-
    source.toolkit.fluxcd.io/v1|GitRepository|flux-system|flox-catalogue
    flox.seedmatic.io/v1alpha1|FloxCatalog|rke2lab-system|catalogue
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: flox-catalog
  name: flox-catalog.group
