{
  description = "workspace — materialises a workspace from its manifest (the nix registry and the editor file), and verifies one";

  # Follow the seedmatic aggregator so the whole closure resolves to one nixpkgs (same
  # discipline as seed-incluster / flox-controller / flox-nri-plugin).
  #
  # ★ And COLLAPSE the aggregator's unused inputs onto nixpkgs, exactly as flox-controller and
  # flox-nri-plugin do. Measured 2026-10-02: following the aggregator without this block writes
  # a flake.lock of 320 983 lines / 8.5 MB — the full transitive closure of every tool the
  # aggregator carries — while the same input set collapsed this way weighs 164 lines. This
  # tool needs Go and nothing else, and the branch is meant to stay light.
  inputs = {
    flake-commons.url = "github:seedmatic/nix-flake-commons/develop";
    nixpkgs.follows = "flake-commons/nixpkgs";
    flake-utils.follows = "flake-commons/flake-utils";

    flake-commons.inputs.bird.follows = "nixpkgs";
    flake-commons.inputs.cachix.follows = "nixpkgs";
    flake-commons.inputs.chromium-bin.follows = "nixpkgs";
    flake-commons.inputs.darwin.follows = "nixpkgs";
    flake-commons.inputs.determinate.follows = "nixpkgs";
    flake-commons.inputs.devenv.follows = "nixpkgs";
    flake-commons.inputs.disko.follows = "nixpkgs";
    flake-commons.inputs.extra-container.follows = "nixpkgs";
    flake-commons.inputs.flake-compat.follows = "nixpkgs";
    flake-commons.inputs.flox.follows = "nixpkgs";
    flake-commons.inputs.home-manager.follows = "nixpkgs";
    flake-commons.inputs.impermanence.follows = "nixpkgs";
    flake-commons.inputs.incus-compose.follows = "nixpkgs";
    flake-commons.inputs.lix-module.follows = "nixpkgs";
    flake-commons.inputs.maven-mvnd.follows = "nixpkgs";
    flake-commons.inputs.nix.follows = "nixpkgs";
    flake-commons.inputs.nix-snapshotter.follows = "nixpkgs";
    flake-commons.inputs.nixos-generators.follows = "nixpkgs";
    flake-commons.inputs.nixos-hardware.follows = "nixpkgs";
    flake-commons.inputs.nixpkgs-unstable.follows = "nixpkgs";
    flake-commons.inputs.nvfetcher.follows = "nixpkgs";
    flake-commons.inputs.ripvcs.follows = "nixpkgs";
    flake-commons.inputs.socket-vmnet.follows = "nixpkgs";
    flake-commons.inputs.sops-nix.follows = "nixpkgs";
    flake-commons.inputs.treefmt-nix.follows = "nixpkgs";
    flake-commons.inputs.zen-browser.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        version = pkgs.lib.fileContents ./VERSION;
      in
      {
        packages = rec {
          # Store-name prefix io.seedmatic.<asset> (org convention) so the artifact is findable
          # in /nix/store; meta.mainProgram keeps the bin at bin/workspace for `nix run`.
          workspace = pkgs.buildGoModule {
            pname = "io.seedmatic.workspace";
            inherit version;
            src = pkgs.lib.cleanSource ./.;

            # ONE dependency, and that is deliberate. The sibling controller's flake documents
            # at length how a single TEST-ONLY dependency slipped through a green local build
            # and broke delivery on the node, because nix generates a vendor dir from this hash
            # while `go test` locally runs in module mode. So: stdlib everywhere, yaml.v3 for
            # the manifest, and NOTHING for the tests.
            #
            # Regenerate after any go.mod change: set this to `pkgs.lib.fakeHash`, run
            # `nix build`, paste the hash nix reports.
            vendorHash = "sha256-g+yaVIx4jxpAQ/+WrGKxhVeliYx7nLQe/zsGpxV4Fn4=";

            subPackages = [ "cmd/workspace" ];
            env.CGO_ENABLED = 0;
            ldflags = [ "-s" "-w" "-X main.version=${version}" ];
            meta.mainProgram = "workspace";
          };

          default = workspace;
        };

        apps = rec {
          # `nix run .#materialize` is the materialisation step: it produces the registry and
          # the editor file. It is NOT an activation hook — evaluating the principal's flake
          # needs the registry, and an environment builds before a hook runs, so a registry
          # generated by that hook would arrive too late for its own build.
          materialize = {
            type = "app";
            program = "${pkgs.writeShellScript "materialize" ''
              exec ${self.packages.${system}.workspace}/bin/workspace materialize "$@"
            ''}";
          };

          # `nix run .#verify` is what an activation hook calls: it asserts and fails hard.
          verify = {
            type = "app";
            program = "${pkgs.writeShellScript "verify" ''
              exec ${self.packages.${system}.workspace}/bin/workspace verify "$@"
            ''}";
          };

          default = materialize;
        };

        devShells.default = pkgs.mkShell {
          packages = [ pkgs.go pkgs.gopls pkgs.gotools ];

          # ⚠️ `go test` and `go run` build their binary under $TMPDIR and exec it from there.
          # Measured on this seat (2026-10-02): TMPDIR is a tmpfs from which exec is refused, so
          # both die with a bare `signal: killed` and no further output — which reads like a
          # crash in the code under test and is not. Compiling the binary into the tree first
          # sidesteps it entirely:
          #
          #   go test -c -o ./ws.test ./internal/workspace && ./ws.test -test.v
          #
          # Overriding TMPDIR to a path on a normal filesystem works too.
          shellHook = ''
            echo "workspace ${version} — go test -c -o ./ws.test ./internal/workspace && ./ws.test"
          '';
        };

        formatter = pkgs.nixpkgs-fmt;
      });
}
