{
  description = "seed-incluster — the in-cluster twin of seed-master: reconciles ClusterProvision (intent) adopt-first and owns the ClusterAdoption that adopts running RKE2-on-Incus control planes into CAPI (→ Cluster/LXCCluster/RKE2ControlPlane/Machine/LXCMachine)";

  # Follow the seedmatic aggregator so the whole closure resolves to one nixpkgs
  # (same discipline as flox-controller / flox-nri-plugin).
  inputs = {
    flake-commons.url = "github:seedmatic/nix-flake-commons/develop";
    nixpkgs.follows = "flake-commons/nixpkgs";
    flake-utils.follows = "flake-commons/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        version = pkgs.lib.fileContents ./VERSION;
      in
      {
        packages = rec {
          # The controller binary. Static (CGO off) so it runs in a minimal image.
          seed-incluster = pkgs.buildGoModule {
            # Store-name prefix io.seedmatic.<asset> (org convention) so the artifact is
            # findable in /nix/store; meta.mainProgram keeps the bin at
            # bin/seed-incluster for `nix run`.
            pname = "io.seedmatic.seed-incluster";
            inherit version;
            src = ./.;
            # Deterministic vendoring of the Go deps. Same dep set as flox-controller
            # (controller-runtime + apimachinery + client-go; the CAPI CRs are handled
            # UNSTRUCTURED, no typed CAPI/CAPRKE2/CAPN module import), so the vendor hash
            # matches. Regenerate after a go.mod change: set to lib.fakeHash, `nix build`,
            # paste the printed hash.
            vendorHash = "sha256-L4MK8X4iveyVbBJmJrPXQxh4e+gtuQP1yk0QifYqhUA=";
            subPackages = [ "cmd/seed-incluster" ];
            env.CGO_ENABLED = 0;
            ldflags = [ "-s" "-w" "-X main.version=${version}" ];
            meta.mainProgram = "seed-incluster";
          };

          # OCI image for the in-cluster Deployment — the DISTRIBUTION artifact. Air-gap
          # path (as for flox-controller): rke2lab bakes this tar into the node-base image,
          # rke2 auto-imports it into containerd at boot, and the Deployment references
          # `io.seedmatic.seed-incluster:<version>` with IfNotPresent. Unlike
          # flox-controller this controller ONLY talks to the kube API (via its
          # ServiceAccount) — it does NOT exec node nix/flox, so there is no host /nix mount
          # and no nsenter: a plain static binary + cacert. dockerTools can't build on darwin
          # (build on aarch64-linux).
          seed-incluster-image = pkgs.dockerTools.buildLayeredImage {
            name = "io.seedmatic.seed-incluster";
            tag = version;
            contents = [ pkgs.cacert ];
            config = {
              Entrypoint = [ "${seed-incluster}/bin/seed-incluster" ];
              Env = [ "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt" ];
            };
          };

          # The generated CRDs as a store artifact — the single source rke2lab's manifest
          # synthesis emits into the cluster's `crds` layer (the ClusterAdoption +
          # ClusterProvision CRDs), instead of re-modelling the schema. Regenerated by
          # `controller-gen crd` (see the flox dev env); this just stages the committed output.
          seed-incluster-crds = pkgs.runCommand "io.seedmatic.seed-incluster-crds" { } ''
            mkdir -p "$out"
            cp ${./config/crd}/*.yaml "$out"/
          '';

          default = seed-incluster;
        };

        # Dev toolchain lives in the flox env (.flox/env/manifest.toml): `flox activate`
        # provides go, controller-gen, kubectl, delve, make.
      });
}
