---
apiVersion: v1
data:
  members: |-
    v1|ServiceAccount|tailscale-system|tailnet-purge
    v1|Secret|tailscale-system|tailnet-purge-oauth
    batch/v1|Job|tailscale-system|tailnet-purge
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: tailnet-purge
  name: tailnet-purge.group
