apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: seed-incluster
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token-write
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token-write
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZODRpc2lteFI3U3p1QUlk
        cG1MSStqYWN4OXduWDh2Ym9oS0IwbnlEcFZrCmkxZmNBNy9KTnlVVmJWZm0rdDZU
        SjBRYnc4RUZ1dzhuUGVkYmtmQjF1OEkKLS0tIHR4UkIrZG5UYmpYMVJ4dFZVZmlZ
        djBMU2lLVGx3WVA3MG8rclEvUkZBN00K0J8Zr6LNIwp7uELUlZArSk13haO9rsSD
        PoEcGaUvCzGmREbccMK9Rz6BguOowsKt2GT78Ozrgkb5IKolRm0mlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYm5SSFFFYVJ2MnBFaVZv
        eTIxZTNLRHJkY0FsdXpCUDV2SzRUWWlXakF3CjlreXI1ZUxsUElVTUtLZStKYXND
        clAvN2lYaldPd1kxeWszZ3A5dFVnQ3MKLS0tIFpsRjl5dHpZZm5tUWFRMUJWM0tX
        d2hEbnNrWXU0SFp4NkhQWTRZM3NVeFkK0Yk2QK+Ek3nVtaCoeMWUqi/VsuQgvx/x
        HGlr+ehPZGIfMU4V2rhlBgl/tWIWBpe2ulIeckAnlRDX7OB8Tz8VHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T19:12:29Z"
  mac: ENC[AES256_GCM,data:ExdOJYWKDcFR2y5ity9hkMkeJJbQOHZHpKBTttzcUqbHlJbF94/1zckvanFsHOazKhn0afco7nl5/of2+sgR/bQZyNdyFo6CR8MCtMC+U4MqIqJDLEgFmpXpi5mZBgKNW8cay7e+gj0OGD2h+vgU4CXk/tRYKvvR+SAtOYNJlNM=,iv:g/uuVS3T5srFr08dNL6PYACzazSvHShYIRlB8y1C6YQ=,tag:1UeMg1i/qGIhaPifyMdsBg==,type:str]
  version: 3.13.3
