apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: seed-incluster
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token-write
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token-write
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMW5MUFRtV2prUVJuYWVK
        RWQvclRJb25vdG5Zb1FtbUlvSDJaNDRHWFVBCkh1ZjJaSlFuZkhSWlZRRTNsdkRX
        MUlCNHZLWmFWT1VweWpDRWs0ZkNwdXMKLS0tIGRHQkpyZEsrS2owamdsUjB0SVB4
        K0JsRnhLZFhFL3ZBdU41VU4vMnJiR3cKx5mtqzbDtSEkUlt/cGntFdXMTr2MR/SV
        rjRR410ITHUICCwpbyu7LJLUTTvv0kcBvgUlmjFfD1RMhDvvlPiLgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdktVS09oaXhTNWEwUGVZ
        WlJvMjZIZWZvZGFPVk02bks3dmJ4Zm1RUlc4CkRveWhHNUNZMzVpYjlaMDU3L1Vy
        anY5QnFJQkxsUXVaR0tiL2JlamFKeHMKLS0tIFpKQXU4VHdITTd1VWVBWjRaNElz
        M01QWDR5UFJNYzJkamtFYk1TK1I4RjAKrqYPbY2mNQByTsW9l0jceNxIcb5zYas0
        r2+Bg0O07XnDJX4tD61eI/PJ4pNJS+2P56ttjHAblkp/MfYX1VVaVA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T10:21:56Z"
  mac: ENC[AES256_GCM,data:fAchDzYCfLf+3iadOM9dYae8Of1SHbT1MqDTXYvKN+pmVHp0/Iur1jKknMYDpzZjn/HmehX2ug7AnElBI1TjE2rbaFHqFwl6Vu2zKNUs7FUc079nATNhJ1714v0ejPHQftYuMJ1O0f8f2+JoRBIqZvuhVYu6crv7ZX8ertzux4g=,iv:e4LdpcwwtoN9D6UHkokYoT4d4pf2P3Hplsgr/NfLryk=,tag:+JH0o0MVsYiqnIEjwGckNg==,type:str]
  version: 3.13.3
