apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: seed-incluster
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token-write
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token-write
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dXBHdTJGMWpmMXpvK0NZ
        OWgyRGViMlhKT081OHFLV3NMeTQ3TENtWHpNCmovTDFxMFkyWk5aZ2MydDJyQkhq
        ZU1TSkhyaGZ0THlYSW5rakRrMUk4K2cKLS0tIGw1Wk5GNGd5U3V6N0FzYm1JTWQ5
        M3Izc1pZTWwwTFBwRzJ3TlR3VWpPQ2cKUNRpryRwMHCncqPvucFxwoXyUf1HZoGs
        dCUvb9kMl7ADEd9rNJFOBEYl9FoabWvb9rbk/DO3D66tS5+Ifmeo8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ1hsL00vQVgzQ05YVXh0
        ZnV1aWd5R3dheFNUU1BGVEhEWEh6Sm55WjJnClZoaTFiNVBHMkFwSkRRVk5zS21q
        aC9IREVpa0F3LzlONjF1M0xrcGcxU3cKLS0tIDJ4TFMrMjNPWVVyYTBFQnBiNVEr
        WHFOTDhWdDVlS3Z6eHk5dDljQ3BwSDAKfY0d+80KGTDE3crH7QWOTFRbNZJbGDcz
        ohKRg2OBvno6FCEyBptZQ4HJrhbatsWHJY6946UofMuKRIUoPYcZug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T22:35:23Z"
  mac: ENC[AES256_GCM,data:AkHTcmXMOTpFBcl0ZD9ftG2jSkm/gpaULRzBTtfJfRrmkrKQ5mr7AODMRiwtNRvnL0XlM4MNZucjA3vZ9MVpMGRxYHvQLY4brgKu2F+6Xzbay7TttdXyTXLBDFuZ55KoMLpqwE+Ra2AaAJ3NZe20Z19pTdUGCIfXV/bzQ+m8PIg=,iv:lbvXwS4p5T19IGYP4ATrgnHXQ0UYF+ty5eI4UZMcx64=,tag:5cBCNc2ZTUwxpyYQOg7q2Q==,type:str]
  version: 3.13.3
