// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetCertificateResult {
  private String certificate;
  private String description;
  private String fingerprint;

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  private String id;

  private String name;
  private List<String> projects;
  private @Nullable String remote;
  private Boolean restricted;
  private String type;

  private GetCertificateResult() {}

  public String certificate() {
    return this.certificate;
  }

  public String description() {
    return this.description;
  }

  public String fingerprint() {
    return this.fingerprint;
  }

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  public String id() {
    return this.id;
  }

  public String name() {
    return this.name;
  }

  public List<String> projects() {
    return this.projects;
  }

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  public Boolean restricted() {
    return this.restricted;
  }

  public String type() {
    return this.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetCertificateResult defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private String certificate;
    private String description;
    private String fingerprint;
    private String id;
    private String name;
    private List<String> projects;
    private @Nullable String remote;
    private Boolean restricted;
    private String type;

    public Builder() {}

    public Builder(GetCertificateResult defaults) {
      Objects.requireNonNull(defaults);
      this.certificate = defaults.certificate;
      this.description = defaults.description;
      this.fingerprint = defaults.fingerprint;
      this.id = defaults.id;
      this.name = defaults.name;
      this.projects = defaults.projects;
      this.remote = defaults.remote;
      this.restricted = defaults.restricted;
      this.type = defaults.type;
    }

    @CustomType.Setter
    public Builder certificate(String certificate) {
      if (certificate == null) {
        throw new MissingRequiredPropertyException("GetCertificateResult", "certificate");
      }
      this.certificate = certificate;
      return this;
    }

    @CustomType.Setter
    public Builder description(String description) {
      if (description == null) {
        throw new MissingRequiredPropertyException("GetCertificateResult", "description");
      }
      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder fingerprint(String fingerprint) {
      if (fingerprint == null) {
        throw new MissingRequiredPropertyException("GetCertificateResult", "fingerprint");
      }
      this.fingerprint = fingerprint;
      return this;
    }

    @CustomType.Setter
    public Builder id(String id) {
      if (id == null) {
        throw new MissingRequiredPropertyException("GetCertificateResult", "id");
      }
      this.id = id;
      return this;
    }

    @CustomType.Setter
    public Builder name(String name) {
      if (name == null) {
        throw new MissingRequiredPropertyException("GetCertificateResult", "name");
      }
      this.name = name;
      return this;
    }

    @CustomType.Setter
    public Builder projects(List<String> projects) {
      if (projects == null) {
        throw new MissingRequiredPropertyException("GetCertificateResult", "projects");
      }
      this.projects = projects;
      return this;
    }

    public Builder projects(String... projects) {
      return projects(List.of(projects));
    }

    @CustomType.Setter
    public Builder remote(@Nullable String remote) {

      this.remote = remote;
      return this;
    }

    @CustomType.Setter
    public Builder restricted(Boolean restricted) {
      if (restricted == null) {
        throw new MissingRequiredPropertyException("GetCertificateResult", "restricted");
      }
      this.restricted = restricted;
      return this;
    }

    @CustomType.Setter
    public Builder type(String type) {
      if (type == null) {
        throw new MissingRequiredPropertyException("GetCertificateResult", "type");
      }
      this.type = type;
      return this;
    }

    public GetCertificateResult build() {
      final var _resultValue = new GetCertificateResult();
      _resultValue.certificate = certificate;
      _resultValue.description = description;
      _resultValue.fingerprint = fingerprint;
      _resultValue.id = id;
      _resultValue.name = name;
      _resultValue.projects = projects;
      _resultValue.remote = remote;
      _resultValue.restricted = restricted;
      _resultValue.type = type;
      return _resultValue;
    }
  }
}
