// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetNetworkResult {
  private Map<String, String> config;
  private String description;

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  private String id;

  private List<String> locations;
  private Boolean managed;
  private String name;
  private @Nullable String project;
  private @Nullable String remote;
  private String status;
  private @Nullable String target;
  private String type;

  private GetNetworkResult() {}

  public Map<String, String> config() {
    return this.config;
  }

  public String description() {
    return this.description;
  }

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  public String id() {
    return this.id;
  }

  public List<String> locations() {
    return this.locations;
  }

  public Boolean managed() {
    return this.managed;
  }

  public String name() {
    return this.name;
  }

  public Optional<String> project() {
    return Optional.ofNullable(this.project);
  }

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  public String status() {
    return this.status;
  }

  public Optional<String> target() {
    return Optional.ofNullable(this.target);
  }

  public String type() {
    return this.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetNetworkResult defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private Map<String, String> config;
    private String description;
    private String id;
    private List<String> locations;
    private Boolean managed;
    private String name;
    private @Nullable String project;
    private @Nullable String remote;
    private String status;
    private @Nullable String target;
    private String type;

    public Builder() {}

    public Builder(GetNetworkResult defaults) {
      Objects.requireNonNull(defaults);
      this.config = defaults.config;
      this.description = defaults.description;
      this.id = defaults.id;
      this.locations = defaults.locations;
      this.managed = defaults.managed;
      this.name = defaults.name;
      this.project = defaults.project;
      this.remote = defaults.remote;
      this.status = defaults.status;
      this.target = defaults.target;
      this.type = defaults.type;
    }

    @CustomType.Setter
    public Builder config(Map<String, String> config) {
      if (config == null) {
        throw new MissingRequiredPropertyException("GetNetworkResult", "config");
      }
      this.config = config;
      return this;
    }

    @CustomType.Setter
    public Builder description(String description) {
      if (description == null) {
        throw new MissingRequiredPropertyException("GetNetworkResult", "description");
      }
      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder id(String id) {
      if (id == null) {
        throw new MissingRequiredPropertyException("GetNetworkResult", "id");
      }
      this.id = id;
      return this;
    }

    @CustomType.Setter
    public Builder locations(List<String> locations) {
      if (locations == null) {
        throw new MissingRequiredPropertyException("GetNetworkResult", "locations");
      }
      this.locations = locations;
      return this;
    }

    public Builder locations(String... locations) {
      return locations(List.of(locations));
    }

    @CustomType.Setter
    public Builder managed(Boolean managed) {
      if (managed == null) {
        throw new MissingRequiredPropertyException("GetNetworkResult", "managed");
      }
      this.managed = managed;
      return this;
    }

    @CustomType.Setter
    public Builder name(String name) {
      if (name == null) {
        throw new MissingRequiredPropertyException("GetNetworkResult", "name");
      }
      this.name = name;
      return this;
    }

    @CustomType.Setter
    public Builder project(@Nullable String project) {

      this.project = project;
      return this;
    }

    @CustomType.Setter
    public Builder remote(@Nullable String remote) {

      this.remote = remote;
      return this;
    }

    @CustomType.Setter
    public Builder status(String status) {
      if (status == null) {
        throw new MissingRequiredPropertyException("GetNetworkResult", "status");
      }
      this.status = status;
      return this;
    }

    @CustomType.Setter
    public Builder target(@Nullable String target) {

      this.target = target;
      return this;
    }

    @CustomType.Setter
    public Builder type(String type) {
      if (type == null) {
        throw new MissingRequiredPropertyException("GetNetworkResult", "type");
      }
      this.type = type;
      return this;
    }

    public GetNetworkResult build() {
      final var _resultValue = new GetNetworkResult();
      _resultValue.config = config;
      _resultValue.description = description;
      _resultValue.id = id;
      _resultValue.locations = locations;
      _resultValue.managed = managed;
      _resultValue.name = name;
      _resultValue.project = project;
      _resultValue.remote = remote;
      _resultValue.status = status;
      _resultValue.target = target;
      _resultValue.type = type;
      return _resultValue;
    }
  }
}
