// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class InstanceExec {
  private List<String> commands;
  private @Nullable Map<String, String> environment;
  private @Nullable Double gid;
  private @Nullable String timeout;
  private @Nullable String trigger;
  private @Nullable Double uid;
  private @Nullable String workingDir;

  private InstanceExec() {}

  public List<String> commands() {
    return this.commands;
  }

  public Map<String, String> environment() {
    return this.environment == null ? Map.of() : this.environment;
  }

  public Optional<Double> gid() {
    return Optional.ofNullable(this.gid);
  }

  public Optional<String> timeout() {
    return Optional.ofNullable(this.timeout);
  }

  public Optional<String> trigger() {
    return Optional.ofNullable(this.trigger);
  }

  public Optional<Double> uid() {
    return Optional.ofNullable(this.uid);
  }

  public Optional<String> workingDir() {
    return Optional.ofNullable(this.workingDir);
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(InstanceExec defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private List<String> commands;
    private @Nullable Map<String, String> environment;
    private @Nullable Double gid;
    private @Nullable String timeout;
    private @Nullable String trigger;
    private @Nullable Double uid;
    private @Nullable String workingDir;

    public Builder() {}

    public Builder(InstanceExec defaults) {
      Objects.requireNonNull(defaults);
      this.commands = defaults.commands;
      this.environment = defaults.environment;
      this.gid = defaults.gid;
      this.timeout = defaults.timeout;
      this.trigger = defaults.trigger;
      this.uid = defaults.uid;
      this.workingDir = defaults.workingDir;
    }

    @CustomType.Setter
    public Builder commands(List<String> commands) {
      if (commands == null) {
        throw new MissingRequiredPropertyException("InstanceExec", "commands");
      }
      this.commands = commands;
      return this;
    }

    public Builder commands(String... commands) {
      return commands(List.of(commands));
    }

    @CustomType.Setter
    public Builder environment(@Nullable Map<String, String> environment) {

      this.environment = environment;
      return this;
    }

    @CustomType.Setter
    public Builder gid(@Nullable Double gid) {

      this.gid = gid;
      return this;
    }

    @CustomType.Setter
    public Builder timeout(@Nullable String timeout) {

      this.timeout = timeout;
      return this;
    }

    @CustomType.Setter
    public Builder trigger(@Nullable String trigger) {

      this.trigger = trigger;
      return this;
    }

    @CustomType.Setter
    public Builder uid(@Nullable Double uid) {

      this.uid = uid;
      return this;
    }

    @CustomType.Setter
    public Builder workingDir(@Nullable String workingDir) {

      this.workingDir = workingDir;
      return this;
    }

    public InstanceExec build() {
      final var _resultValue = new InstanceExec();
      _resultValue.commands = commands;
      _resultValue.environment = environment;
      _resultValue.gid = gid;
      _resultValue.timeout = timeout;
      _resultValue.trigger = trigger;
      _resultValue.uid = uid;
      _resultValue.workingDir = workingDir;
      return _resultValue;
    }
  }
}
