// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class InstanceInterfaces {
  /**
   * @return IP addresses assigned to the interface
   */
  private @Nullable List<InstanceInterfacesIpAddress> ipAddresses;

  /**
   * @return Name of the network interface within an instance
   */
  private @Nullable String name;

  /**
   * @return State of the network interface (up, down)
   */
  private @Nullable String state;

  /**
   * @return Type of the network interface (link, local, global)
   */
  private @Nullable String type;

  private InstanceInterfaces() {}

  /**
   * @return IP addresses assigned to the interface
   */
  public List<InstanceInterfacesIpAddress> ipAddresses() {
    return this.ipAddresses == null ? List.of() : this.ipAddresses;
  }

  /**
   * @return Name of the network interface within an instance
   */
  public Optional<String> name() {
    return Optional.ofNullable(this.name);
  }

  /**
   * @return State of the network interface (up, down)
   */
  public Optional<String> state() {
    return Optional.ofNullable(this.state);
  }

  /**
   * @return Type of the network interface (link, local, global)
   */
  public Optional<String> type() {
    return Optional.ofNullable(this.type);
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(InstanceInterfaces defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private @Nullable List<InstanceInterfacesIpAddress> ipAddresses;
    private @Nullable String name;
    private @Nullable String state;
    private @Nullable String type;

    public Builder() {}

    public Builder(InstanceInterfaces defaults) {
      Objects.requireNonNull(defaults);
      this.ipAddresses = defaults.ipAddresses;
      this.name = defaults.name;
      this.state = defaults.state;
      this.type = defaults.type;
    }

    @CustomType.Setter
    public Builder ipAddresses(@Nullable List<InstanceInterfacesIpAddress> ipAddresses) {

      this.ipAddresses = ipAddresses;
      return this;
    }

    public Builder ipAddresses(InstanceInterfacesIpAddress... ipAddresses) {
      return ipAddresses(List.of(ipAddresses));
    }

    @CustomType.Setter
    public Builder name(@Nullable String name) {

      this.name = name;
      return this;
    }

    @CustomType.Setter
    public Builder state(@Nullable String state) {

      this.state = state;
      return this;
    }

    @CustomType.Setter
    public Builder type(@Nullable String type) {

      this.type = type;
      return this;
    }

    public InstanceInterfaces build() {
      final var _resultValue = new InstanceInterfaces();
      _resultValue.ipAddresses = ipAddresses;
      _resultValue.name = name;
      _resultValue.state = state;
      _resultValue.type = type;
      return _resultValue;
    }
  }
}
