// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class InstanceInterfacesIpAddress {
  /**
   * @return IP address
   */
  private @Nullable String address;

  /**
   * @return IP family (inet, inet6)
   */
  private @Nullable String family;

  /**
   * @return Scope (local, global, link)
   */
  private @Nullable String scope;

  private InstanceInterfacesIpAddress() {}

  /**
   * @return IP address
   */
  public Optional<String> address() {
    return Optional.ofNullable(this.address);
  }

  /**
   * @return IP family (inet, inet6)
   */
  public Optional<String> family() {
    return Optional.ofNullable(this.family);
  }

  /**
   * @return Scope (local, global, link)
   */
  public Optional<String> scope() {
    return Optional.ofNullable(this.scope);
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(InstanceInterfacesIpAddress defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private @Nullable String address;
    private @Nullable String family;
    private @Nullable String scope;

    public Builder() {}

    public Builder(InstanceInterfacesIpAddress defaults) {
      Objects.requireNonNull(defaults);
      this.address = defaults.address;
      this.family = defaults.family;
      this.scope = defaults.scope;
    }

    @CustomType.Setter
    public Builder address(@Nullable String address) {

      this.address = address;
      return this;
    }

    @CustomType.Setter
    public Builder family(@Nullable String family) {

      this.family = family;
      return this;
    }

    @CustomType.Setter
    public Builder scope(@Nullable String scope) {

      this.scope = scope;
      return this;
    }

    public InstanceInterfacesIpAddress build() {
      final var _resultValue = new InstanceInterfacesIpAddress();
      _resultValue.address = address;
      _resultValue.family = family;
      _resultValue.scope = scope;
      return _resultValue;
    }
  }
}
