// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkAclIngress {
  private String action;
  private @Nullable String description;
  private @Nullable String destination;
  private @Nullable String destinationPort;
  private @Nullable String icmpCode;
  private @Nullable String icmpType;
  private @Nullable String protocol;
  private @Nullable String source;
  private @Nullable String sourcePort;
  private String state;

  private NetworkAclIngress() {}

  public String action() {
    return this.action;
  }

  public Optional<String> description() {
    return Optional.ofNullable(this.description);
  }

  public Optional<String> destination() {
    return Optional.ofNullable(this.destination);
  }

  public Optional<String> destinationPort() {
    return Optional.ofNullable(this.destinationPort);
  }

  public Optional<String> icmpCode() {
    return Optional.ofNullable(this.icmpCode);
  }

  public Optional<String> icmpType() {
    return Optional.ofNullable(this.icmpType);
  }

  public Optional<String> protocol() {
    return Optional.ofNullable(this.protocol);
  }

  public Optional<String> source() {
    return Optional.ofNullable(this.source);
  }

  public Optional<String> sourcePort() {
    return Optional.ofNullable(this.sourcePort);
  }

  public String state() {
    return this.state;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(NetworkAclIngress defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private String action;
    private @Nullable String description;
    private @Nullable String destination;
    private @Nullable String destinationPort;
    private @Nullable String icmpCode;
    private @Nullable String icmpType;
    private @Nullable String protocol;
    private @Nullable String source;
    private @Nullable String sourcePort;
    private String state;

    public Builder() {}

    public Builder(NetworkAclIngress defaults) {
      Objects.requireNonNull(defaults);
      this.action = defaults.action;
      this.description = defaults.description;
      this.destination = defaults.destination;
      this.destinationPort = defaults.destinationPort;
      this.icmpCode = defaults.icmpCode;
      this.icmpType = defaults.icmpType;
      this.protocol = defaults.protocol;
      this.source = defaults.source;
      this.sourcePort = defaults.sourcePort;
      this.state = defaults.state;
    }

    @CustomType.Setter
    public Builder action(String action) {
      if (action == null) {
        throw new MissingRequiredPropertyException("NetworkAclIngress", "action");
      }
      this.action = action;
      return this;
    }

    @CustomType.Setter
    public Builder description(@Nullable String description) {

      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder destination(@Nullable String destination) {

      this.destination = destination;
      return this;
    }

    @CustomType.Setter
    public Builder destinationPort(@Nullable String destinationPort) {

      this.destinationPort = destinationPort;
      return this;
    }

    @CustomType.Setter
    public Builder icmpCode(@Nullable String icmpCode) {

      this.icmpCode = icmpCode;
      return this;
    }

    @CustomType.Setter
    public Builder icmpType(@Nullable String icmpType) {

      this.icmpType = icmpType;
      return this;
    }

    @CustomType.Setter
    public Builder protocol(@Nullable String protocol) {

      this.protocol = protocol;
      return this;
    }

    @CustomType.Setter
    public Builder source(@Nullable String source) {

      this.source = source;
      return this;
    }

    @CustomType.Setter
    public Builder sourcePort(@Nullable String sourcePort) {

      this.sourcePort = sourcePort;
      return this;
    }

    @CustomType.Setter
    public Builder state(String state) {
      if (state == null) {
        throw new MissingRequiredPropertyException("NetworkAclIngress", "state");
      }
      this.state = state;
      return this;
    }

    public NetworkAclIngress build() {
      final var _resultValue = new NetworkAclIngress();
      _resultValue.action = action;
      _resultValue.description = description;
      _resultValue.destination = destination;
      _resultValue.destinationPort = destinationPort;
      _resultValue.icmpCode = icmpCode;
      _resultValue.icmpType = icmpType;
      _resultValue.protocol = protocol;
      _resultValue.source = source;
      _resultValue.sourcePort = sourcePort;
      _resultValue.state = state;
      return _resultValue;
    }
  }
}
