// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class StorageVolumeFile {
  private @Nullable Boolean append;
  private @Nullable String content;
  private @Nullable Boolean createDirectories;
  private @Nullable String directoryMode;
  private @Nullable Double gid;
  private @Nullable String mode;
  private @Nullable String sourcePath;
  private String targetPath;
  private @Nullable Double uid;

  private StorageVolumeFile() {}

  public Optional<Boolean> append() {
    return Optional.ofNullable(this.append);
  }

  public Optional<String> content() {
    return Optional.ofNullable(this.content);
  }

  public Optional<Boolean> createDirectories() {
    return Optional.ofNullable(this.createDirectories);
  }

  public Optional<String> directoryMode() {
    return Optional.ofNullable(this.directoryMode);
  }

  public Optional<Double> gid() {
    return Optional.ofNullable(this.gid);
  }

  public Optional<String> mode() {
    return Optional.ofNullable(this.mode);
  }

  public Optional<String> sourcePath() {
    return Optional.ofNullable(this.sourcePath);
  }

  public String targetPath() {
    return this.targetPath;
  }

  public Optional<Double> uid() {
    return Optional.ofNullable(this.uid);
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(StorageVolumeFile defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private @Nullable Boolean append;
    private @Nullable String content;
    private @Nullable Boolean createDirectories;
    private @Nullable String directoryMode;
    private @Nullable Double gid;
    private @Nullable String mode;
    private @Nullable String sourcePath;
    private String targetPath;
    private @Nullable Double uid;

    public Builder() {}

    public Builder(StorageVolumeFile defaults) {
      Objects.requireNonNull(defaults);
      this.append = defaults.append;
      this.content = defaults.content;
      this.createDirectories = defaults.createDirectories;
      this.directoryMode = defaults.directoryMode;
      this.gid = defaults.gid;
      this.mode = defaults.mode;
      this.sourcePath = defaults.sourcePath;
      this.targetPath = defaults.targetPath;
      this.uid = defaults.uid;
    }

    @CustomType.Setter
    public Builder append(@Nullable Boolean append) {

      this.append = append;
      return this;
    }

    @CustomType.Setter
    public Builder content(@Nullable String content) {

      this.content = content;
      return this;
    }

    @CustomType.Setter
    public Builder createDirectories(@Nullable Boolean createDirectories) {

      this.createDirectories = createDirectories;
      return this;
    }

    @CustomType.Setter
    public Builder directoryMode(@Nullable String directoryMode) {

      this.directoryMode = directoryMode;
      return this;
    }

    @CustomType.Setter
    public Builder gid(@Nullable Double gid) {

      this.gid = gid;
      return this;
    }

    @CustomType.Setter
    public Builder mode(@Nullable String mode) {

      this.mode = mode;
      return this;
    }

    @CustomType.Setter
    public Builder sourcePath(@Nullable String sourcePath) {

      this.sourcePath = sourcePath;
      return this;
    }

    @CustomType.Setter
    public Builder targetPath(String targetPath) {
      if (targetPath == null) {
        throw new MissingRequiredPropertyException("StorageVolumeFile", "targetPath");
      }
      this.targetPath = targetPath;
      return this;
    }

    @CustomType.Setter
    public Builder uid(@Nullable Double uid) {

      this.uid = uid;
      return this;
    }

    public StorageVolumeFile build() {
      final var _resultValue = new StorageVolumeFile();
      _resultValue.append = append;
      _resultValue.content = content;
      _resultValue.createDirectories = createDirectories;
      _resultValue.directoryMode = directoryMode;
      _resultValue.gid = gid;
      _resultValue.mode = mode;
      _resultValue.sourcePath = sourcePath;
      _resultValue.targetPath = targetPath;
      _resultValue.uid = uid;
      return _resultValue;
    }
  }
}
