schema-version = "1.11.0"

[install]
go-2fa.pkg-path = "go-2fa"
  [install.age]
    pkg-group = "keyhole"
    pkg-path = "age"

  [install.gnupg]
    pkg-group = "keyhole"
    pkg-path = "gnupg"

  [install.keychain]
    pkg-group = "keyhole"
    pkg-path = "keychain"

  [install.openssh]
    pkg-group = "keyhole"
    pkg-path = "openssh"
outputs = "all"

  [install.openssl]
    pkg-group = "keyhole"
    pkg-path = "openssl"
outputs = "all"

  [install.pass]
    pkg-group = "keyhole"
    pkg-path = "pass"

  [install.pwgen-secure]
    pkg-group = "keyhole"
    pkg-path = "pwgen-secure"
outputs = "all"

  [install.sops]
    pkg-group = "keyhole"
    pkg-path = "sops"

  [install.ssh-to-age]
    pkg-group = "keyhole"
    pkg-path = "ssh-to-age"

[options]

[profile]
  common = """
    GITHUB_SIGNING_KEYFILE="$HOME"/.ssh/keys.d/github-signing
    if [[ -r "$GITHUB_SIGNING_KEYFILE" ]]; then
      set -a
      SOPS_AGE_KEY=$( ssh-to-age -private-key < "$GITHUB_SIGNING_KEYFILE" )
      set +a
    else
      echo no signing key
    fi
  """
