apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: flox-controller
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/floxhub-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: floxhub-token
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VVNDOW82b1J4OVVIQnNy
        c0l4TXg0QXErZEQrRVR1VFdaVXZPaG01aEY4CnhnSHBzTnZkOVJkbERMbG45WlhK
        Vzd1bTFYUDJsOTBVYkJmdkRXbko1bFUKLS0tIEJtSlp6V2NUSlhCNFJUTEY1VVg3
        VXpPbDJPZitBR0N2ckhaeEk4REpkK2cKLYXJh3dHXTHp8Woq7njSAz5Q0STUHbdC
        S7TbRFFl/scAMfyKrgCeMZWjz9l41DVeu7G7D16cBhvnDoF6HCMTBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUHFjOGN6OG9NQmJpdHV5
        MEM2LytsMTZyenF6WEVxbHZRajJOYUR3YUZjCjhMMFNQM3YzNGZZM0hMUldrbW01
        c1hINGlJdlI4bytCM1crd3N5UmE2YjgKLS0tIHZnandvRzkwNXRQYlZENmh2V2dv
        N05RcWR0VVZybG51QmVnUDdteG43SEkKiTG9uxVX0atIUY/H46XotBMFtR8NSCEC
        /48MaTZLTItV13mMu1/gm8upueJVM6GH3aCNm2Ht9ec3N+rcVmIFqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T06:46:35Z"
  mac: ENC[AES256_GCM,data:vZTnq4FmTbP0HwJ6nUkXGPCDrO4JVrxBnKp3vkcYieR0HyUYlxQQ/5RhswejWSTy/gPRHlcMtz9hdiNBXCZS5gBe6SOC1y70REi38oVRV4OOn6/8vy8k3CvRDOFsZBcc1GJulMfhO8e4V3FCulhF7HMBzjA3qxymb50EcsmkPRk=,iv:aHbRurjhlJ2807HADotfW5la212SKQYg7nPCI8jQ8es=,tag:6ufKyE3PMfalIuQC8T7S6Q==,type:str]
  version: 3.13.3
