apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: flox-controller
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUE1wakxBckRtZzRPdnhD
        L2w5bEZZaHVoTElncmFQNHhhaUg4TlVjU1d3CitxVXM4bG51bW5sWG9VWUpLMlJB
        bXVaajJ4MlliYkJqL2hIYkpDQmxiM2MKLS0tIHF3NlYvb3MzMm5zdjRuSVlFV24v
        cms4OXdUdCszSHRRN0tIanBXeERJNTQKfUl51GMry1ib28mee+QrzYJtDPujIWkJ
        RMBoAwjP5Ysqg8/Dto9UTsAuAHOyEOo0PsOzbJLYOZziROXrVW+b9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYazB1N0xvUXFYRlZIWkhQ
        cXJrNkl0TVVidEVVazhUaU1NTHFIcC8yNURJCk5GQndwRVN5aVpobmFGdEJGeGU4
        cFRvZGZuek5JNHdHMU1jRlJSNXMvU28KLS0tIHFSTXFaUm8xdEdGZXpyS3pEV092
        QXkwNzN4NFpWUXZicmEyN3lSckVaQjAKqe0+ZZFW+kyKW+jywcJIjTe+/CpwKwGf
        /1h+WcNwAYMHaO3cmp6PJ5kEuI94ZBrHzTFGI21jOjZvq7CAgDWmcA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T14:17:46Z"
  mac: ENC[AES256_GCM,data:Mqv+k2F0w4i3UYRvELWX8TScwT5ZfwWrHKIn4NfRz2DyWeLE629/D+GJNcjK25Lf6fsRf68yMLJZTcnCzrbd5KmwyUJqOBOhhqqNjWx6YqusI168RQP2yO027GeDZu928fp+NyTCmjJpr5Fe3lPWBV61QqmmUXWjJ0iEkoSDoAA=,iv:uNYEWSs2JxYcihgT4wkLdby++IaUJp2BD1MrEnuFmQM=,tag:AYo8F+jCvxspXOXa9M8jOQ==,type:str]
  version: 3.13.3
