apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: flox-controller
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaWkvRUFuTnhmLzRnYzAv
        azRHTSs5UGtRTENYOTRZaVMrWkpub1p1SWpNCjhXb1kvK0tlVDYxSDhCTWt4Y2NF
        MEZCbnJYcUZ6bXRDc2FOdFhvMUVTbEUKLS0tIDlDMGRKbEFBbEZZT284Mjcwc2NP
        eVV4SFR2WHBQU3UxdFZPWXhSM1J5aWMKJdEKvg9iNbkqWVejGNsaLgHOTKYhCaqf
        108dwD/FHSuQ19XZavGWBbi7HwdD6rUJXH1FrPvMAq/TOHhVEvwIfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZDRvQTdKWlZDcGFObEN3
        Zm56d1RSZGlQdWtmaXVVNDYxbitUalRoQlRBCmZoR2JkTDVyTlpVQ0Zzd2hKK2FS
        anVxRGg3NDJ2NlFnWUtnRXhBVXdac00KLS0tIEFiUzJpM1BPQ04xZ25uZzZsQXc2
        alR4YWtGWWRYd0hYZmY1d2FOcmZ0dVkKRMrbXuROjW3uwSz62njAFhHvbYlCsOQ8
        z7o2XoJFmTDbKmOWcU4VkleWOfYhQf/Lcch5Batd9tfGnGz70sElQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T14:55:21Z"
  mac: ENC[AES256_GCM,data:WVqzAZO3e2mIVckFD2dfSWkngze7dUMMW1/WTtWGsWtxwWqrt41z7EOHpczoEHo2kv/uN/JTTfNFMjK1ZxBzOYP7nZrCGrNUDxYfZKvc9HWEXWsO3bBQ04w+avqZRuZsaeBClghS1rSw/lb4Rz427CJKX9a7UWO5vDCbEQiLpYc=,iv:/FT5DlI1ckRthg5jRlU/6kJ5KpWlj7ZA/y2BW0m+UzA=,tag:pfsn9afeyDTFMY9cgXnyIg==,type:str]
  version: 3.13.3
