apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: flox-controller
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc2t0ZUN4T25QSHU1V1k1
        eEdjK1Vvdk9aK0xBZHZyRllwNDJCZEJuM1RrClJsZ1J5UFdBamluRnAycEFCTndI
        RmZjdkNaQllQNDh1NzI5QnA1TjZoTVEKLS0tIEhGL3JMOCtGTGd1UzY5Q0h1SE83
        ZmN1bXRRVGIxc21ySVRCelVnaVFUWFUK7V3vbGk4RyDbO2Uk1mtsxPDpBfJUWEXh
        YE1tK2O0W03vB13k1qU1G3RxuSz9s+mWD1M7cSIibu/DqUoyhAdM/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM3d0WG9QSU9ET1NhMk82
        YVlPWWwxVFppM1BYUXdkZW44dFZvWStUM1RjCnE1RjBNZTdFMVpNbFFmWTN1UGUy
        TzA0K2FXS1RJdEppcFJVci9scFF1N2MKLS0tIHU1YnFyMFAvMU5ZUDB4WUlzUkNr
        amxuSVJnYUFFTDRBNk9XZzRvbVNOZDgKJtp9m0NtsDciR0vCU3DOMM6jxH5cBOv8
        LzSdlk6QK9+AKjXh49EnKmjXtXc5h/5C3+40mmouckR5Ip0LTcYM9g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-12T15:31:25Z"
  mac: ENC[AES256_GCM,data:jX12mQzQzJvZSzqu9ODxtpx3vRMAVxzRSyss3ozPw51X2aaFOPEo7DVtub1/1qr4R4JRR+2t2VLk8ryw1rIUO0NPpKnltbylnr09x+uG8HblkiBSx1AluAtQooRo98r/EcYSUP9ESbuFWc4HsYxtC7pmteYom7m9oaDZ+3XGKeo=,iv:twjzUHiBVww8xFastGzj14RKfAq5KngRjLoYSiIyNJM=,tag:4t8a7ZeDAFlhKaN/fnSjsA==,type:str]
  version: 3.13.3
