apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: flox-controller
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/floxhub-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: floxhub-token
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VktRWW5BZ3d4cHZ4Rmhs
        TVF3TlNiSVF1bG43RW55bHJBQjZ4QWkwWld3ClJ3WjRBTVZYM0RFOGVoL0JPeGJa
        S3UvZlA0cUhTcDFmS2tJb0dBRlJmd1EKLS0tIE0yL2tWNzIxWVMyY0NCRmxMVVJo
        NUFkeXErdkE1b3N5NVBHbVZ2WFA1azQKe66E4+Ge3HeCN+YzrWW2xTInGyBOSibW
        bP7gu9YleEDF68Jx9C/haSp9fSCn+wJXi1fnhqydvOjywLjO+Js6pQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUTBlL1lUNFBGbzc1bktQ
        VGdrV3BYRHVpYWcwZ052bXBTSkF0Sk1mUjA4CjdRUWVoay9oeE5BNDUyVkhZQ2Zt
        UndMaEQyYk9pMzkwemVCQUI2SW9mRWsKLS0tIE1OZGoyMnJ5SUFURG1WQWM0WjJw
        WjRqUElJbTVac3p6dEp4QVcvVDBPTXMKa4VIOU0aYX/XwoutH7UHSj/dLAgbnF9W
        mDv+rxfL3slPXhdu+AP4Bh2OkkuXKQRXSQ3mRqMZfkGkMjEDq7YC9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T20:40:59Z"
  mac: ENC[AES256_GCM,data:Md+xaXeoL1BRSSMxB6KYvA/gFzzuabwTeMU8+U4g9k/ELDMIdocN8rz7m0uyDF1Spk4i9pThiZt8s+3fex2a1o6TCdmrFNEQBcKJnJyaCsan/unIsp3XpvE8hS5OopIylFK/9cfU5GNQAUb4DPwg/5acMXTYdT7zLvfy9/f4n/0=,iv:6YHn4xlDb0V0DW9Vrs+A4QPCZiifDZXoHa1LPsJydQs=,tag:NgFG3c4DhgcblClfEWAgIg==,type:str]
  version: 3.13.3
