apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: flox-controller
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/floxhub-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: floxhub-token
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMWN4OE9yTEVGVEkzSWRv
        WkxqdDBENnVVYjg1eUp6Zy9veHgzcTNGOGtJCm5adjYvVnR2L0duaENNaXRTMmZH
        T056UVF1SXVHMlowbjVwRDNtTGkxWUEKLS0tIG84VTN0WHJkSm9mUGlpeHRPRUFP
        aHdkVWlxOFNXd0MyajJsa244YU94MW8KqqtDq4m6r3OPi+hcXo72xxYxYEXDYVcS
        yrPqEK7ypDFw3CCRwYicWLZhfwoI7N+ldLuz2qQx+ICIqGNE5zSRrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaE5acllZUGdUTms1NkJX
        b2tHalJyQklORFI2S2t0aDlyd1ZEWlNoT0RFCjI3Wms5dnZ4TitMc1NmblV3eENh
        ZXZkT3A5NFNkemlZL2tjbWw1RUY1Y0EKLS0tIFd3VHNQL09HaHRiUlRCdHkxT254
        UEtCY2duSzFpcmh1WjIwSTh1UUxRdlEKC0KeiutcuBoKcF/NA2OA1Mz9wNAI/4Md
        aw4minNNR2mp0JcQmiVETS95dn48zcFNvUpAkdvyvFSHfiPvWTt45Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T08:20:32Z"
  mac: ENC[AES256_GCM,data:KGK0x35psHweu4mz4eDVEhM8jVP+qHfmHrm8OsNIc+RucuRHZG87FRUeA6CDwF21anMEfB9OWyRLGurnTeCbcJrAE+SvjJ1PR/fMsLjjolCbRZ6SOXd5sQ8Q9wkRQoOWQAG7ShiefkmwnSiPMee6JuFV2DJEuXeTMJwsbpYsFUU=,iv:8mWvsSzYFg2UnbWKaLt9zYXqnJqnJQnF5ezgykGEmvg=,tag:zlGMMZbeS8tp4eswvmXmMQ==,type:str]
  version: 3.13.3
