schema-version = "1.11.0"

[include]
  [[include.environments]]
    dir = '../keyhole'

[install]
  [install.cachix]
    pkg-group = "nix"
    pkg-path = "cachix"
outputs = "all"

  [install.deadnix]
    pkg-group = "nix"
    pkg-path = "deadnix"
outputs = "all"

  [install.nix-eval-jobs]
    pkg-group = "nix"
    pkg-path = "nix-eval-jobs"
outputs = "all"

  [install.nix-fast-build]
    pkg-group = "nix"
    pkg-path = "nix-fast-build"
outputs = "all"

  [install.nix-output-monitor]
    pkg-group = "nix"
    pkg-path = "nix-output-monitor"
outputs = "all"

  [install.nix-tree]
    pkg-group = "nix"
    pkg-path = "nix-tree"
outputs = "all"

  [install.nixd]
    pkg-group = "nix"
    pkg-path = "nixd"
outputs = "all"

  [install.nixfmt-rfc-style]
    pkg-group = "nix"
    pkg-path = "nixfmt-rfc-style"
outputs = "all"

  [install.nvfetcher]
    pkg-group = "nix"
    pkg-path = "nvfetcher"
outputs = "all"

  [install.statix]
    pkg-group = "nix"
    pkg-path = "statix"
outputs = "all"

  [install.watchexec]
    pkg-group = "nix"
    pkg-path = "watchexec"
outputs = "all"

  [install.linux-builder-vz]
    pkg-group = "home"
    pkg-path = "darwin.linux-builder-vz"
    systems = ['aarch64-darwin']
outputs = "all"

[options]
