---
apiVersion: v1
data:
  members: |-
    v1|Namespace||openebs
    storage.k8s.io/v1|StorageClass||openebs-zfs
    storage.k8s.io/v1|StorageClass||openebs-zfs-shared
    storage.k8s.io/v1|StorageClass||openebs-zfs-persist
    helm.cattle.io/v1|HelmChart|openebs|openebs-zfs
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: storage
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: openebs-zfs
  name: openebs-zfs.group
