---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: platform
    io.seedmatic.rke2lab/package: replicator
  labels:
    app.kubernetes.io/instance: kubernetes-replicator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-replicator
    app.kubernetes.io/version: v2.12.4
    helm.sh/chart: kubernetes-replicator-2.12.4
  name: kubernetes-replicator
  namespace: kube-system
