---
apiVersion: v1
data:
  members: |-
    v1|Namespace||rke2lab-bioskop-mgmt
    v1|Secret|rke2lab-bioskop-mgmt|bioskop-mgmt-operator-kubeconfig
    v1|Secret|rke2lab-bioskop-mgmt|bioskop-mgmt-kubeconfig
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: kubeconfig
  name: kubeconfig.group
