---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tailscale-funnel-cert-restore-operators.yml
- tailscale-funnel-cert-restore-workloads.yml
- tailscale-funnel-state-operators.yml
- tailscale-funnel-state-workloads.yml
- tailscale-system-namespace-foundation.yml
- tailscale-system-namespace-workloads.yml
- tailscale-tailnet-purge-operators.yml
- tailscale-tailnet-purge-workloads.yml
- tailscale-tailscale-operators.yml
- tailscale-tailscale-workloads.yml
