apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: seed-incluster
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token-write
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token-write
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYjZCcHpwazllSXI3UTEy
        bDRobi9aTkJac1FTZHF5ZUc4Vm1zNTR6T20wCit6TmtzdjFncmNrYThxejJXQlBE
        QkczU29ja3ZmODh6dlQvaWhoaXE2cFkKLS0tIHpnL3ZVQWRXNEFBMVVZMWlmOWlh
        THQ0MzhFeXN6WUxtLzZXeG1JbGNPakkKeEnMoAELyznjdZQ5KOtB0mjGpE+kWp9E
        AXRtxYyeroChiZTvJNA4xcylXsGijgbLavC2B1mrCbBtyxCW/A7CIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU1hMQ1dLQ2E4dXJJbm5R
        c2VhaU5MSDJqUkVGaFpKemlsSUJhbjJsSEJ3Cm1od28xZ0xZSTBKK1F4a2JYK25z
        WC9Wb2t6R2lCemRTWnZKejhLckRxdDgKLS0tIG1YVzZ5RUMvRVV1blJDTTY2Ynd3
        UzVIc2hmSGFpcmtacWpXb25seWExaVkKXEdXnR0uV9beEfYaWI6NOlVHfJ+E1N6v
        qfNEBVk4ruU4AJW1fI3ExKa8+n4Rj+f3ttTzXP5Sl3aydZGaWj5JVA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T08:55:14Z"
  mac: ENC[AES256_GCM,data:f44fM1ajZIc21HHeqACJC1VJXt49FpGlTVeaxfAVdHug9+qIgnaSfTBPPWFmyTJtpMDlBvc8ruUyeGuXUdLcTB+fDthPF0p2578f0sbW6jWNe0DoHZw6atBEOPch9KVyL/AKWlcu6KU5G3o0sjhqdg7NFlCdwy71UKlwi3VgX2g=,iv:mURLmIDrUvDV3p3uZ09VHCJVS/7x27XsU4WTFR/S5o0=,tag:ozF107p6/wqjeTLmB0RB9Q==,type:str]
  version: 3.13.3
