apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: seed-incluster
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token-write
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token-write
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UFU5RnM5eSsyNnk3eHBP
        cG5mL0dCaEdqWnhyM3ZwUnhnKzlIY3dYWXdRCk9pYm9SZFZGWER2Y0h5ZTNycmFz
        L3NQRk1hSldvd3ZEekxzankyZmZhL0EKLS0tIHFTUmppdUdVZWx0ei9SSnVSZGlH
        ZGxraFR3RTVHR213T1AxZjZXMVY2N0UKMwlUKyjDQ4qbojtjoaq1kjY9B0ztsMk5
        oj2amur9psqs7P1tzh8ofj/Jhid+NiumlXJx3KSrEv4uR45XjYz2CA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNG9wcGhDQjl0a3VmZjVY
        MllIZGlkaFlSbzNWMmhQN0VXMFNWVEoyeVdFCnplZGpWLytxOSt2SWlucW90dVh0
        aVRlWVhTWDZMTld4d2ZrQWp0cFNpdU0KLS0tIDBGMnhxMGxLTEVzVDhiK0NkalNp
        K2tzRVlLNnN0Mm5KTE5tQncxd0lrRTQK2RF8E0Qr/bH+eFjM5QoyLK3Kcj/nVE7D
        8Ix19mX39Ruds3dMmPC2ERkYqXVlYg6ZBBs70QErB1ylN2+2/51Agw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T14:38:18Z"
  mac: ENC[AES256_GCM,data:m3gymZRRRUtWaA4yfdx0ePKA/eU0d6RQlCTqKpgt/DizxP2PgZ7TmBjjXpyVK/vivFlyyDdsxh50iRgsb51LFpYXrtvDRPDB402zaX//pbg/bphnJC7sdNIp5yKIrkApTraeErfuQIgZ/DpVKdw/LulBGcOb+CeVUnFA4ODFk6k=,iv:Scxwrm/VeVO66nTL8DFc12+pNRqbuLVYWvMAE4Mooj8=,tag:fgGQgxrDyFONp2o9UCdt6A==,type:str]
  version: 3.13.3
