apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: seed-incluster
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/github-token-write
  labels:
    app.kubernetes.io/replicated: "true"
  name: github-token-write
  namespace: rke2lab-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UXpubENrZ3FxQmtzakhh
        WE8yR0hzN0diUXl4VHFxeHlIQVA5UGVnY1NvClNBVVpFcVdxcGdqQmVWRTMyaFhO
        VVlLQzhRbURYMzE1cjAyM0NKaXRTUkEKLS0tIFJaZmFUTndvb2JCOHljR20rdWdZ
        N0tZV2s5NkVXVERxSmpJdG1RanBXN28KhwjNvZTQnFcTlfPxkmZVFh4wnByrPmhW
        DLh8rvW55XsRDIS5PDAcJn+Igh+RCuk+5uvNumNFpUaO3BbT6AyckA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOTA3MmVSVWlERXJ3Qml2
        NTR1N3F6MkJZZkFtVnJkWmtnYk5DYXhxQlFrCllvOGdJUjBkeWthYkowLytDd0pH
        TVJhZHhPNXlhZUlHWUxoc2pFS012N1UKLS0tIC9yd2dXTjJlNjd0bkRObW1ERkU3
        MEgxOC9LeUpwR1QvbVdhbVRCUW5hczQKcM/GSVCPQfaTTeHGBHqyrYPJoV63hSqB
        gNL+LfCe58gBCp+o7zwvOmMvBFPenmmr+orOOwtkjS4EBQ2ipFLd2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T17:47:12Z"
  mac: ENC[AES256_GCM,data:DRTaYMcqryrVkl6dOd0ckwtwj/OrXarRepoiSACpNgwrCXLuqHCNgIHW1Fprn3BeFVdwEXoazLQbJ/7V0ukX2f/f1rO6u/sPkm2UjCip/jHBqg6gpp+jXFAL84Z8OQCDHXCS96Ov3jFMkH+tdeFt33WuNTz0m+Vskzt7c2nMjZw=,iv:7OLy0jZ0J3N8GQ97Pg0VhECu4dNht8GDMMHSmIq51j0=,tag:ZHF9TsSfqyB6la13bMi5PA==,type:str]
  version: 3.13.3
