apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: tailnet-purge
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/operator-oauth
  labels:
    app.kubernetes.io/replicated: "true"
  name: tailnet-purge-oauth
  namespace: tailscale-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOWdxL1ZCdWNHaGtoT3hO
        Y1JUTE5EZGZrZlVValpRd011dmFpS1FBeWhVClZUOGtieENyZWx6akJKRlBnY3B6
        TEFwQmpreW1rOG9iU1J2VTI0SUtONHcKLS0tIHBhTXpTUEtRYmprQ0FrTnBDeitm
        K0N3MzZONWxnNTVwaHlLdlBpOENqZEkK+xERdoXYiZqhcXc8i6Z4Bo6vFfBSr05R
        SlikpLpQOrvkJRw3xv+Op2j01tFWFApjSX/T5ilBD97YIqXK8F4d8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya2lSSVFSU1k5R3JaWUUy
        UExIcmZ6SEdMQUo4aGFUWFM0Qzk2VUJDUENjCkE2N2RNQnlnM0xSOFN3bzZUbG9q
        TFY3NEFNSTdmUXhuSm8yQkZEMmc3ZGsKLS0tIGl5MEFGcUxHeG8vK3NzblBkaXhz
        OS9TQXAvUFpTRXFJT3NpaW01OGRTYTQKfWAl2xk1eW4cylw1QAFmQ8KQjqB80KP8
        ll11CMtNEavkonmLA5TO/48DBj5HxqkTfsI55UtSoMmkxf+UUljleQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T17:40:13Z"
  mac: ENC[AES256_GCM,data:HzBNiI0e4xibkTCC5bBILgHa3jO08wiO7dccq688G3rsAs5Vy8G/7AuxfmU05E/oep6koMU8Ir6O/2vfdcUmp1ullLGzrBGmDiPDm/tB27ziuGAC4ypR4nxOtIB0O3PcUk6HPUGbu9J90DNL7mFlV9hhoDthafpupVF+CbdEMCw=,iv:doEQnUukAaDhPyPqqGexaoM0k89WJRRpYep2TtFAxOk=,tag:cPyyn3iJ1BG17+ck8xRmLw==,type:str]
  version: 3.13.3
