apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: tailnet-purge
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/operator-oauth
  labels:
    app.kubernetes.io/replicated: "true"
  name: tailnet-purge-oauth
  namespace: tailscale-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOVlBRjl6TUJ4a2FuN0F1
        eFcvSXVmTEdPQVhoYUY2NFpRMzdpZlBIN1JRClVaZGZ2RFJIMngvbDg0MWEyWi8w
        anI3N3RtN3NNUzZtSG9RUkZ6MWdJN3cKLS0tIC9LOGk1MEhrdW1kVnJYYTBSQ2pM
        cXd5ZVhnZCt1U1dpUEg2WEowQmpWMkUKRtp9TLvOESp6YeMO7kdmIQBdfthWnFUq
        PMklmrNNzSQL+HjZ0SLP8JaDaesaQhTddCEJsTyp+wWdFaCITkYa7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TjIzWGcwbURERTdteVpW
        WnUzYzB3ckpDR09IeG54bzYxL0VuVzVkZzFZCktRTXlpeTIzMmgrK1p5TWcybVIr
        UkxKaUlaYU1BS2kydnRqNXkvdWVuQlUKLS0tIENwZjJzYmMrNWMxNU9WZ3V1R0F0
        cDJvU0xqWWRaZnpvNFc0THJSdFpCb1EKkYCNfW7MDj1v/jUtZzTG8lK/Y3GSVdET
        dl6KjwHd2ZT5MuU+SkUswECsCR/+uQcag61p0qvGDn1K79nJhK4vEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T16:47:26Z"
  mac: ENC[AES256_GCM,data:XncH4NtTgLZ1NN6P4mX3QB8SxXDIq7QE1FHWyKmKgL/lo9iaZqlkZuyYTIJAd/t5KAW47cVsr2eEvoidp0UjbJS9tlXOFyIngkpQ7Aj8k/pSQBrYO8p/o7/bMIeq25O766coNlWjC/mxtnp0gFsDVudnz1xkNFqP+7rh704BN4E=,iv:Y4s+udlmWK+gKY1v02nEelu9Br+0hpHN4VEHu8p71lM=,tag:c4yr4P90HFJi5t5IJV5qRQ==,type:str]
  version: 3.13.3
