apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: tailnet-purge
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/operator-oauth
  labels:
    app.kubernetes.io/replicated: "true"
  name: tailnet-purge-oauth
  namespace: tailscale-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S3pvTmdjb2tRVSt6ZnpO
        Q0E4d0hTeXZKRHBJcEM2UzJETkFYSGN0S1NVCk42aG5WQUp1d2FQSHdvaXNTakRU
        VXFyamxFMHpDZFRMUnVYVE1zb3VqOW8KLS0tIDJSMTl4RXlXeGhqQVFWVHRHck1t
        MDZDSnpaZkJtNUZSMEJwWGpKSkpKQ0EKUW46mSR8Y2PEPa03wI/cirMWc5nUaBhO
        Y/OzvCBSEHm5au2vtyNLjLQY6swM4SyGebT1xB2R16IxAn12LWibRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UlBIMHRoQ3NXcmQzQ3VJ
        dVdoU1RxQUpCZUtma1FDZWZpcHFJenFEblFRCm43TWd3bjNqTmxydGtudEYyVG00
        OG5mYzFUaFd3a0xuSTk1SFJQeUJIWDgKLS0tIHRPek1jczY0RzJXVy9OZFB4eUZC
        VUU1S2ZWSGN0Rm9FZVk4TzYyQ3RyRG8KjZw6sgiaTtGjTDR7x2uDeI2X7RDF3FKt
        MFMm3f8qIWFWr2TZiJGSPkXiHigTx+7O3PTJ4VTUH1V3k5VLWjZeXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T07:53:31Z"
  mac: ENC[AES256_GCM,data:gIo5Jft8kshil0tUxK2wvyHRB7Ktb//2Ry5K3kpidYgcMOhoBgZ2lh9vOZusnzKF2dRn4YxjVOPevurN5KklmurSmp7IPITnhcokQkjSaTNM/VNcwWRR9yui2/u11stvOHin7zVykIpxzfL0bNc0Q9VppQMgHdqjjTxi30k+vwo=,iv:PuPpMdhIi9zUXDxf3PtZ5Ir+Iu941jNfCZ+s7ga6GEw=,tag:FxxTzgdIB1qKrNL4jVGM5A==,type:str]
  version: 3.13.3
