---
apiVersion: v1
data:
  members: |-
    v1|ConfigMap|rke2lab-nikopol-mgmt|cidrs.yaml
    v1|ConfigMap|rke2lab-nikopol-mgmt|core.yaml
    v1|ConfigMap|rke2lab-nikopol-mgmt|debug.yaml
    v1|ConfigMap|rke2lab-nikopol-mgmt|disable.yaml
    v1|ConfigMap|rke2lab-nikopol-mgmt|etcd-metrics.yaml
    v1|ConfigMap|rke2lab-nikopol-mgmt|etcd.yaml
    v1|ConfigMap|rke2lab-nikopol-mgmt|tls-san.yaml
    v1|ConfigMap|rke2lab-nikopol-wrkld|cidrs.yaml
    v1|ConfigMap|rke2lab-nikopol-wrkld|core.yaml
    v1|ConfigMap|rke2lab-nikopol-wrkld|debug.yaml
    v1|ConfigMap|rke2lab-nikopol-wrkld|disable.yaml
    v1|ConfigMap|rke2lab-nikopol-wrkld|etcd-metrics.yaml
    v1|ConfigMap|rke2lab-nikopol-wrkld|etcd.yaml
    v1|ConfigMap|rke2lab-nikopol-wrkld|tls-san.yaml
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: rke2-config
  name: rke2-config.group
