apiVersion: v1
kind: Secret
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: RKE2 token fragment (sops-encrypted on the branch)
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/package: rke2-config
    io.seedmatic.rke2lab/rke2-config: "true"
  name: token.yaml
stringData:
  token: ENC[AES256_GCM,data:DD+9cbKdLRY23/YW4G0=,iv:XqnMDqEzR2x7BIAz/a6YhTtmtpgZu90zXAm/f3nmifk=,tag:bAWYbRxZwwM1Vt2TJoeG3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Smg0MjR2YU5mWjU2OHd4
        eUJ4VStMMFN6WU02Q1JNM3VGTjhsSk9mdmc0CjRJYTZjb3JkS0hNTFoxNTdQZCtQ
        RDVsdzlWSzFJS1RCWWZwNytMeE9jLzAKLS0tIHJlN2FsRHprcElvaDB4OExxVjl4
        NVJYeUQ0RTFvWlRGNjI5MVlaNC85bDgKoQOq/Ee90GqH62rq3085980ylbzLmQWY
        CBwZEc+0sD3vtTAHx0ECkI6ry6/S/gw+BjHCCgi8YU+s6due1H/F3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RmJzdklaNm9ocmRSNXpS
        WVlDTzB1UmQ4Unp6dy9jV004cDlkOWw3VnhFClJ4V1JHVEU1cnlacGV4SkI4dW1R
        dndCNU9sWXpaTm9lR0hRWWJsb1Nhd3cKLS0tIG40L3NoSzVFOTQra0VEbGU2T2tk
        TFYwSFBSQWFjZnlMaFZCRmtqZnNJOTQK01IdsPijo4VcBWM+XII6nhAVhPNEd4c2
        qvHOJr6lNJ5rqJ07WUx08swQ0OqWruYpRarerrFkcnd0Dq1ZpfpGKw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-12T22:54:53Z"
  mac: ENC[AES256_GCM,data:/UvlZkbBzBbmU4A77NJZ1JDvw4RgmwfwAy6YHTdKpuW8iJgMcx2tlO60k6ZzhlVZm4SzEyrWD3exINcHc2R53a4w7NryOcbNVderi5WOj58Uwl8uEaB8/zS8ttqpX8+GjTjy2SzsfdFJGRA1TSQi6LVLBxOvEhDl/BQPED70JIE=,iv:ZF3xoY73a1SMCUjJjglfrw8bkpC7OExTDYq2HLLFxWQ=,tag:IrNad+UXYUG2uIIVodqEng==,type:str]
  version: 3.13.3
