---
apiVersion: v1
data:
  bind-address: '"0.0.0.0"'
  cni: '"cilium"'
  write-kubeconfig-mode: '"0640"'
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    description.kpt.dev: Core RKE2 settings
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/package: rke2-config
    io.seedmatic.rke2lab/rke2-config: "true"
  name: core.yaml
