---
apiVersion: v1
data:
  members: |-
    v1|Secret|flux-system|flux-webhook-token
    notification.toolkit.fluxcd.io/v1|Receiver|flux-system|github-receiver
    networking.k8s.io/v1|Ingress|flux-system|flux-webhook
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: gitops
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: flux-receiver
  name: flux-receiver.group
