apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: gitops
    io.seedmatic.rke2lab/package: flux-receiver
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/flux-webhook-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: flux-webhook-token
  namespace: flux-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbkdMQnlrMVk2c2ZIQm91
        UDhrUllSS2REWUtpbHZhWDNmOG1mN2E5ZUM4Cnc0L1gyQlBhVEd1V1FYRVkrN0ov
        aEVIVzl4RFIvMlRheVdzZ2lvR1pOdjgKLS0tIElGZTRIbitHaXlNUlIwWUFlTDZM
        THFQMUlTaEdHdFA5aU9SdjAxQk40eWMKxz6f5AK4w4fwoHtvkIRRklu90uhd7jJd
        jlchYJ0WjWgMyMYOITofDolFcSaF/6e8HcSya5psEhnXzXPjtq2VIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUGpjWkFWUE1HYXB3N3JF
        SnA1dzJOcHVPcG94NlkwTEtyRVJleUxsUHhnClY2Wm1uTEpXOFQzZEh1c0hVQmJW
        ckJlbXYwanFaQ3Y3U2pQeHlTL1I2OVUKLS0tIG81cUhBTjRJZ1h5eTZteWJJN2lr
        MzdYTzZ1QU4xS0Q0MlQycGgxUXhMMFkK7c9bfvmOqtdGMzDHWWc+VVkNRPTXFIWg
        Cd3B4Zt2LY57BNbiwOshCeLWaEb8TXxmLg4l078M0/+O527x2uCImw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T16:24:38Z"
  mac: ENC[AES256_GCM,data:j25Etcrvqbyh2XuygFJcbtP+zUa5P9N4jvbYBHxkYAyXk93xiqPQP3kqrnTV/aNjzS/E/8+HM9wLcF2Ak+FibLHDCoORLs1WVnVHbRTWTY6lDJFVhbSVlL74s/PB7UtmmGgI4tRAy5b4y5I5tgUk4KjfRV/vLmst43+77ue6vr4=,iv:Pm/xz8SOlol8ShshfPGWZiWClcbrD88wlRQtI+AvveU=,tag:mhb9l+ekJy9dJ2Xl6VwCTQ==,type:str]
  version: 3.13.3
