apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: gitops
    io.seedmatic.rke2lab/package: flux-receiver
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/flux-webhook-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: flux-webhook-token
  namespace: flux-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVTRlVUFVamE2NWFaaGd5
        MHdWYW0xcjVkL01OeHF0cGorQmFnemFZdGdrClNaVXcxWk9GMnRmbXYwcGRITnBx
        OXpTSWY3amhEYzZYUHR3dGV6V0lKb2cKLS0tIEhmSWN0R2VPa2U5SkhlWk0vV2Qv
        cGlhRUhWRTMyYzBoQTg2N3gxMjBSL0kKFNvlkHzaqlfo9WSaKrLvts/QNC6bQfro
        3UTFzK0a+W7ckAmFpy36InLQ4XgiYmQpBFQ/HNZGH93f+0eAxjCdNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK1QxdTYxOURZRS9ha1VU
        L081SmJyRlUrMVNvS0JzVHB5S1hUZHR0VFY4CktGM1BPRE5MbDk0TW1DNU1TaVNH
        aUNDNy94THZwNjdWRG53L0lhR2pWMDgKLS0tIHlCZExza1g0SE5OcFFOanEwY2F3
        eHcvL1RPeHM0UjZGWXFPSTVEQlNVK2sKak8ZPdCZhXZE6KumiURCUsBdqko2Li+b
        YBBZmptoZ3bqHYew5Lht2SfQWxkY1ABOeNViJN76/8sBPpd7GNYvYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T20:43:32Z"
  mac: ENC[AES256_GCM,data:IswMqMOoFuse89tCp2GkyA9XLNFzV7pTFoXuOCs9O2A1Qp9YlUdUAODPI9cPmDROtD+abYUWZWCkLp8q1Onmk8nv0QoyNC6aSzoIb/FnJjBNYuswhFLNV1vMuRBfIROvuOfmTbQzrJYPMJcwsY+4Mg6+EMa0x+22VLs3NExSxMI=,iv:XLYzesqCf/s1NYGAVGgcJQUjpaiIiIC/4BFwci6rS8M=,tag:MeyGRRRlXtq7BJeUzeMdQQ==,type:str]
  version: 3.13.3
