apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: gitops
    io.seedmatic.rke2lab/package: flux-receiver
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/flux-webhook-token
  labels:
    app.kubernetes.io/replicated: "true"
  name: flux-webhook-token
  namespace: flux-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ1V3RXJvNnhxYnFmMUhv
        L29GaVZ1b2g3Vm5DU0tRcFAvdEhucHpmSDFrCklUVXZyTk1tQUJHcjBBSnFaVjB2
        VjF6S1Zod3A2a04vSHdrektPeWM1VjAKLS0tIFlQS3FKL3o4MkNiQ21JeFRPVlVp
        cWt0WFF3NFlpUmJsaDdBNjNCakl3WjQKpt5HdY/LTe+lgled5l0Cphx6cTSYgwID
        gLEfYPmYjwI0toLWWoB0/svzJiXLx1Hn8NvESJgT+1wn90mKPHmbRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc1lHbktsVkRDeWJVNzl1
        NlI1UGttZWxtTlNTUVBCZ3FtSks0TVpvbkRnCmt5Q1RPRzhuODBvcXVVeHlwUGdk
        RDBNbFVzaldBV09oYTdldzFyV1pOVDgKLS0tIDNZcG5VMHR0K1dlVnR3ck5MQjZp
        SlBhaGlabm0rVW1TZ3NnczlEV3J6NlEKTRMW4sAnQAyTU0bVKAw6ZPIfZEszo6XC
        xnrT9aTLvD8t4vdRKwSF0T0gLNdvrkPGK0Zl6mipf97MpiiFsU94jg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T19:22:14Z"
  mac: ENC[AES256_GCM,data:PwzVxS61Ium1jQYsK4DkqMIKyOfe7/ZtAa9Ek35XmIESQiTVQMM3EUQZ6tfBmt1L8MyBu0cEgWl0LnW7RLip2YsVeBfnkSRylOcRTtJQeoFKdgLJQWvAnnk4kzSbHVl9+MoL82kx+QP0PvqRbbXb3rMXUBWjEWXpPRPfqtNGvmE=,iv:rA+rzy8stJz4/R+wS5/bKv+XTUQ47GGdOB6ktH/T6iQ=,tag:STpSDeNKDOWTvZ7TjkHgbg==,type:str]
  version: 3.13.3
