---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: funnel-state
  name: flux-webhook
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        env:
        - name: TS_KUBE_SECRET
          value: ts-flux-webhook-state
