---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gitops-flux-instance.yml
- gitops-flux-operator.yml
- gitops-flux-receiver.yml
- gitops-flux-root.yml
- gitops-githubapp.yml
- gitops-sops-age.yml
