---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mesh-headscale
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: mesh-system-namespace-foundation
  - name: mesh-system-namespace-workloads
  - name: networking-cilium-config
  - name: runtime-flox-controller-crds
  - name: runtime-flox-controller-operators
  - name: runtime-flox-controller-workloads
  - name: runtime-flox-webhook-operators
  - name: runtime-flox-webhook-workloads
  force: true
  interval: 5m
  path: ./workloads/mesh/headscale
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: rke2lab
  wait: true
