apiVersion: cluster.seedmatic.io/v1alpha1
kind: PoolReflection
metadata:
  annotations:
    cluster.seedmatic.io/owner-ref: '{"apiVersion":"cluster.seedmatic.io/v1alpha1","kind":"PoolIntention","name":"nikopol-mgmt-control-node","namespace":"rke2lab-nikopol-mgmt"}'
  creationTimestamp: null
  labels:
    cluster.seedmatic.io/cluster: nikopol-mgmt
    cluster.seedmatic.io/pool: control-node
  name: nikopol-mgmt-control-node
  namespace: rke2lab-nikopol-mgmt
spec:
  clusterRef: nikopol-mgmt
  namespace: rke2lab-nikopol-mgmt
  nodes:
  - name: nikopol-mgmt-control-plane-9hv57
  pool: control-node
status:
  lastReflectTime: null
