apiVersion: cluster.seedmatic.io/v1alpha1
kind: PoolReflection
metadata:
  annotations:
    cluster.seedmatic.io/owner-ref: '{"apiVersion":"cluster.seedmatic.io/v1alpha1","kind":"PoolIntention","name":"nikopol-wrkld-control-node","namespace":"rke2lab-nikopol-wrkld"}'
  creationTimestamp: null
  labels:
    cluster.seedmatic.io/cluster: nikopol-wrkld
    cluster.seedmatic.io/pool: control-node
  name: nikopol-wrkld-control-node
  namespace: rke2lab-nikopol-wrkld
spec:
  clusterRef: nikopol-wrkld
  namespace: rke2lab-nikopol-wrkld
  nodes:
  - name: nikopol-wrkld-control-plane-hd5c7
  pool: control-node
status:
  lastReflectTime: null
