---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-cluster-issuer-foundation
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: platform-cert-manager-foundation
  - name: platform-cert-manager-workloads
  force: true
  interval: 5m
  path: ./foundation/platform/cluster-issuer
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: rke2lab
  wait: true
