---
apiVersion: v1
data:
  members: |-
    v1|PersistentVolumeClaim|rke2lab-system|manifests-maven-cache
    tekton.dev/v1|Task|rke2lab-system|git-fetch
    tekton.dev/v1|Task|rke2lab-system|render-publish
    tekton.dev/v1|Pipeline|rke2lab-system|render-manifests
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: render-pipeline
  name: render-pipeline.group
