---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/package: render-pipeline
  name: manifests-maven-cache
  namespace: rke2lab-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: openebs-zfs-shared
