---
apiVersion: v1
data:
  members: |-
    v1|Namespace||rke2lab-bioskop-mgmt
    cluster.seedmatic.io/v1alpha1|NodeImage|rke2lab-bioskop-mgmt|bioskop-mgmt-node-base
    cluster.seedmatic.io/v1alpha1|ClusterIntention|rke2lab-bioskop-mgmt|bioskop-mgmt
    cluster.seedmatic.io/v1alpha1|PoolIntention|rke2lab-bioskop-mgmt|bioskop-mgmt-control-node
    v1|Namespace||rke2lab-bioskop-wrkld
    cluster.seedmatic.io/v1alpha1|NodeImage|rke2lab-bioskop-wrkld|bioskop-wrkld-node-base
    cluster.seedmatic.io/v1alpha1|ClusterIntention|rke2lab-bioskop-wrkld|bioskop-wrkld
    cluster.seedmatic.io/v1alpha1|PoolIntention|rke2lab-bioskop-wrkld|bioskop-wrkld-control-node
    v1|Namespace||rke2lab-nikopol-wrkld
    cluster.seedmatic.io/v1alpha1|NodeImage|rke2lab-nikopol-wrkld|nikopol-wrkld-node-base
    cluster.seedmatic.io/v1alpha1|ClusterIntention|rke2lab-nikopol-wrkld|nikopol-wrkld
    cluster.seedmatic.io/v1alpha1|PoolIntention|rke2lab-nikopol-wrkld|nikopol-wrkld-control-node
    v1|Secret|rke2lab-nikopol-wrkld|nikopol-incus-identity
    v1|Secret|rke2lab-nikopol-wrkld|nikopol-wrkld-ca
    v1|Secret|rke2lab-nikopol-wrkld|nikopol-wrkld-cca
    v1|Secret|rke2lab-nikopol-wrkld|nikopol-wrkld-etcd
    v1|Secret|rke2lab-nikopol-wrkld|nikopol-wrkld-peer-etcd
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: cluster-api-workload
  name: cluster-api-workload.group
