---
apiVersion: cluster.seedmatic.io/v1alpha1
kind: ClusterIntention
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-workload
  name: nikopol-wrkld
  namespace: rke2lab-nikopol-wrkld
spec:
  adoptedBy: nikopol-mgmt
  clusterName: nikopol-wrkld
  clusterNetwork:
    podCIDRs:
    - 10.47.0.0/16
    serviceCIDRs:
    - 10.51.0.0/16
    serviceDomain: cluster.local
  controlPlaneEndpoint:
    host: 10.80.31.10
    port: 6443
  kind: workload
  namespace: rke2lab-nikopol-wrkld
  remote:
    endpoint: https://nixos.bioskop:8443
    identitySecretName: nikopol-incus-identity
