---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LXCMachineTemplate
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-workload
  name: bioskop-wrkld-control-plane
  namespace: rke2lab-bioskop-wrkld
spec:
  template:
    spec:
      config:
        linux.kernel_modules: "ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,netlink_diag,nf_nat,overlay,br_netfilter,xt_socket"
        raw.lxc: |-
          lxc.mount.auto = proc:rw sys:rw cgroup:rw
          lxc.apparmor.profile = unconfined
          lxc.cap.drop =
        security.nesting: "true"
        security.privileged: "true"
        security.syscalls.intercept.bpf: "true"
        security.syscalls.intercept.bpf.devices: "true"
      image:
        fingerprint: 636df014af3a2f490342e9650f7ea062f8ae94aa29668b47dff58ad5126ce685
      instanceType: container
      profiles:
      - rke2lab
