---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LXCMachineTemplate
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-workload
  name: bioskop-wrkld-worker
  namespace: rke2lab-bioskop-wrkld
spec:
  template:
    spec:
      config:
        linux.kernel_modules: "atkbd,br_netfilter,ctr,ext4,isofs,lockd,loop,nf_conntrack,nf_conntrack_netlink,nf_nat_ftp,nf_tables,nfnetlink,nfs,nfsd,nfsv3,nfsv4,nft_chain_nat,nft_ct,nft_fib,nft_fib_inet,nft_fib_ipv4,nft_fib_ipv6,nft_masq,nft_nat,nft_numgen,nft_redir,nft_reject,nls_cp437,nls_iso8859_1,overlay,sunrpc,veth,vhost_vsock,virtiofs,vsock,xt_CHECKSUM,xt_MASQUERADE,xt_comment,xt_conntrack,zfs"
        raw.lxc: |-
          lxc.mount.auto = proc:rw sys:rw cgroup:rw
          lxc.apparmor.profile = unconfined
          lxc.cap.drop =
        security.nesting: "true"
        security.privileged: "true"
        security.syscalls.intercept.bpf: "true"
        security.syscalls.intercept.bpf.devices: "true"
      image:
        fingerprint: b7c6a573dda580f221734b9f300c220ed97848211adb18ad58494390f922dc51
      instanceType: container
      profiles:
      - rke2lab
