---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-workload
  name: bioskop-wrkld-md-0
  namespace: rke2lab-bioskop-wrkld
spec:
  clusterName: bioskop-wrkld
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: bioskop-wrkld
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: RKE2ConfigTemplate
          name: bioskop-wrkld-agent
      clusterName: bioskop-wrkld
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: LXCMachineTemplate
        name: bioskop-wrkld-worker
      version: v1.34.8+rke2r2
