---
apiVersion: cluster.seedmatic.io/v1alpha1
kind: PoolIntention
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: cluster-api-workload
  name: bioskop-wrkld-control-node
  namespace: rke2lab-bioskop-wrkld
spec:
  clusterRef: bioskop-wrkld
  controlPlaneEndpoint:
    host: 10.80.15.10
    port: 6443
  image:
    fingerprint: 483198367e547bce5d56a04dbdee0423807c958f761523d42a4861df8c67a130
  namespace: rke2lab-bioskop-wrkld
  nodeLabels:
  - flox.seedmatic.io/enabled=true
  nodes:
  - name: bioskop-wrkld-master
  - name: bioskop-wrkld-peer1
  - name: bioskop-wrkld-peer2
  pool: control-node
  rke2Version: v1.34.10+rke2r1
  role: control-plane
