---
apiVersion: v1
data:
  imageAlias: node-base
  imageBuildChecksum: 42c54a2bd9881f3fc7fd8e37acfe6a8777b50db6457ed113803933ac921da882
  imageFingerprint: 030d237c98ac0958aee720694d3ae6eab20a94787f82227c4e7d7ef24d918113
  incusProject: rke2lab
  incusRemoteAddress: https://bioskop-nixos:8443
  rke2Version: 1.34.10+rke2r1
kind: ConfigMap
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: image-state
  name: bioskop-mgmt-image-state
  namespace: capn-system
