---
apiVersion: v1
data:
  imageAlias: node-base
  imageBuildChecksum: fe9115661a737f03d0667a249d75e0fa8fe1e0fc6389f123bbb61ece168dfe57
  imageFingerprint: 164337efd99ee8e8fafc916b892ad145888b07da775444e273a451fc7c8c25d4
  incusProject: rke2lab
  incusRemoteAddress: https://bioskop-nixos:8443
  rke2Version: 1.34.10+rke2r1
kind: ConfigMap
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: image-state
  name: bioskop-mgmt-image-state
  namespace: capn-system
