---
apiVersion: v1
data:
  imageAlias: node-base
  imageBuildChecksum: 7c26725d18cf94fd2ebe0ebdeb2d4d46745e4a0db022f336d1c11296f5f12185
  imageFingerprint: 789e98ee846eb2c00b414c96c90872a5fc4c31b5e16f37d011be387ce1c2671c
  incusProject: rke2lab
  incusRemoteAddress: https://bioskop-nixos.lan:8443
  rke2Version: 1.34.10+rke2r1
kind: ConfigMap
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/package: image-state
  name: bioskop-mgmt-image-state
  namespace: capn-system
