apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: tailscale
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/operator-oauth
  labels:
    app.kubernetes.io/replicated: "true"
  name: operator-oauth
  namespace: tailscale-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRzBxWnhsNUlkaWtpOEpw
        OGZIbWtveS9ocjRmWldCY01wYUFOZWZJSkZVCkR4Y1pwN0EwNjRXWjZ3Vno2SHBh
        K0NrblBLajE0NWFLQlVWUGNpZ0VLYkkKLS0tIHdOemlDQ1RkTDZDTzY5R1BvZ2tN
        SC80ZFcwM2RSQ2Y3UXBWRHJZN3lGTWsK3QvzQYcDAR9f+2Z567IhVPTph48rsk0k
        /ikWMJzP5dfV/Qo5AIygLTv3aHYodGLc3kdSW1qqyc1XBGS5CDsCJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTDNRYmpQa3hrZkRMR3I3
        SEttbElMYVBUTWZxOEt1MXZnTkpScW9KYzFzCk9waHBUbURhNWFKMTVHdHdhak94
        SHVTQ3hhYWhtWHdLdmJHV0RuYWMyejAKLS0tIDhKYk84dVZXM3lIYVUrUjJtSWwr
        bmE5QXp1NXJ5czhGZWM1cUlnMG5GRTQK2ddnWcNdDJIHQu+i41bMdGdxccNPhNUP
        yNw5FRMKs5JMPp79yLL7cZo1rx2zaPey5eF+MPPH3nvhBgBwwcPVSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T18:22:41Z"
  mac: ENC[AES256_GCM,data:a3PYM0ZK6FmzRMIw7pPLxi+jjzZ1RBxvvu4eAdNCB4XIxSTT5KTL+ncrOWweGYLhTd9zpFC889mZ/nbrYe50sOlcGtXjS435nWD6QoBY7Ndc1ziXdZtUpNDw0+e6GJmi9NwbgzeEfgF6tESaZFj3iNxI35pm+A8NgMoH+sp8//s=,iv:8AiwvLx/XWP1vrCbWjQ+CAk8MmGMHfbplbmeYdnLAR0=,tag:iwdd0j2Jw/4eLdXbu7uoQw==,type:str]
  version: 3.13.3
