apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: tailscale
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/operator-oauth
  labels:
    app.kubernetes.io/replicated: "true"
  name: operator-oauth
  namespace: tailscale-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ckhici9JOFVtQmJFazBT
        eWxGWGk4UUptdDIvZVJETnVxUEF2bTl1SVhjCk81RENhOFFyZU9EVGxCWnNZcUdm
        TllKSm9VejRNOGtIbnVyQ0FQTFBSTlkKLS0tIDRnUUt4RkVUb2h5Ym5OZVR4TXRq
        TXNQUEdRMFVDY2FlYzdURzNSVTdWeGsKSsibLPEHO1q9GYA2OABrwC6OWG4KPMoc
        FN9K90zgg/igNXZf+hxpmutU2AoLsb0vT3DeMxaeK8P9a8woSj+slQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdGQ1VjlwMnA2THJkcWFS
        aXh1S0d3Q0lNZGl2SUxuZGFEQi9nT3pUQkJFCm5TOGhkcThMN2N0cFBDamkzY2th
        aU1hTVRjVHIwRW0zQnFrL1RXMy9BcUUKLS0tIHplcTBzVGRabEhzMEdDL0VmQXdy
        RW1hckEvdXhHNDkrSDRYS0pxMHRXTHMK4dkSdC0amtNI+6mqBpr/FvfLUAQyIKgx
        0ngsJSbmrKUlbnXpifgBcis0svNUHNSYJ6CJld/cd6jZRsWud101vA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T19:29:36Z"
  mac: ENC[AES256_GCM,data:D9QGKOGjhgYp1gioRGD/2ZSWXYrOYDSXnka/PWXQrbAux7pTUKVrSJSqlIqkdF7Hyhj8nnR3i5UG9cUT3XIh+BZikMNPZK3cGB7MFs1UEKczDpN4ffdG5zGBVIKR+Lm21zJPEohJgOd/FN+f+wqC7moN0jedfenNDdOiSdaeiWI=,iv:yle/wH98I+XJ4TzFYvCEKzT1Kph8MWehlU/CS7cWuZI=,tag:nzlXQ1eZJT7Gt3+yQYohzA==,type:str]
  version: 3.13.3
