apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: tailscale
    replicator.v1.mittwald.de/replicate-from: rke2lab-secrets/operator-oauth
  labels:
    app.kubernetes.io/replicated: "true"
  name: operator-oauth
  namespace: tailscale-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNkZoMFc2YWtyWnRVaVpw
        UXduQzBOZlFpUW9VR2NyTm05bmJueENIS21zCldHaVFtcVAxMVFpMjdTanZEdWs0
        VktCZFV4MlhwQWlWUU5nc0NCK2JCZ0kKLS0tIEEwZTBDZjlNSWVZK1ZHV1pMVzdx
        cjI2a3lYNXlVS21nM3JJOUs4VCtPT1kKtVP4YsMBydqlqKZnyKFsAaILO68p/bQx
        XArfa94YSV7fH3G8ho/liO+/KXGfi9vj2BCg9xYmyiEHPLAxRIQvZg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY3M4N0RpeUFlRG1YM1h2
        THNWNUhlTkNyenEyOG5RREZkL1pndnBjMHk4CkpNR2NubU5wZGVLeVo4eDVGQWJh
        dmpjemc4ZnM1RUNLeEFVZEZlbDN6QlEKLS0tIGY0SmVqN2NvdGZ6cDlvdGJSTjNh
        bFJqSStLYisvRWpsd2FueFZFOUhkUWMK/fABHAktT+01Lm0nLhJgXGXTmjCHVVi4
        QDf8E3nF1thzT0P2eoBJVBy8JcfOO6x2x61neOfBq8Fv91gknM7BFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T09:10:58Z"
  mac: ENC[AES256_GCM,data:uX1ETu25mNMqdBmk0RFUpTO6hofsQ2rWjZpvCL+Etgmz9jcgJHtpBnNUSDUjapOTmbS5NU+rRv2ugPuEhxtlM9CbPxPcDrQRsmNQcvOa6+Nqef0lswnuRIITnwgGa6w3etjX8aIH+EtdIWmuTDXhXLM+VcJK28SR55fxxdVfDyA=,iv:lN8A4L8KLdZVjvJqLDliKDe/ifxaAGdhHJeQu8RdYVM=,tag:EOoBI2CbDKnzU0AA8nJLMg==,type:str]
  version: 3.13.3
