---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-cilium-advanced
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: networking-cilium-config
  force: true
  interval: 5m
  path: ./workloads/networking/cilium-advanced
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: rke2lab
  wait: true
