---
apiVersion: v1
data:
  members: |-
    cert-manager.io/v1|Certificate|rke2lab-system|flox-controller-webhook-serving
    v1|Service|rke2lab-system|flox-controller-webhook
    admissionregistration.k8s.io/v1|MutatingWebhookConfiguration||flox-controller
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: flox-webhook
  name: flox-webhook.group
