apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: cluster-api-operator
  name: capn-provider-config
  namespace: capn-system
stringData:
  CAPN_VOLUMES: ENC[AES256_GCM,data:ZvaxFmz3b4Y6LSPYmbDkpIk8CcKLiA6DE0PiCln1eNOXvpOJ25mCfoipJ3ms4AIj+2NawyqSFJ/+56VMfblpWMH8KZZ+Wdzh+MPeNyx+aSTqVQp2xjlsqg==,iv:IKaCZnnLf6jH01Bq7TxQUz9txADApCUA6qqexy5w5qQ=,tag:nirLwbTpQ8gUQ8Ddz+2tpQ==,type:str]
  CAPN_VOLUME_MOUNTS: ENC[AES256_GCM,data:kFT6pwolBQSiSwEwIvTSw4PnSOILGxNUerpkSLYHuGF29ap+sgzKx/lvml5PBLdJ6oIjPsGAaiGaHWHl7y83PnYQPu41hMWvTH0zqDIr5KnWv08=,iv:uc8PgUAAAyFExDxbZflDUxHPLbQ1N/K7MiFI3kyVJgw=,tag:mD4hej2eOwd0Lqj65URmkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTWwxYU05UEdsQVRuMCth
        b3I0NE94bUJvWUVZM01EM3c3bXN6eVpnRkdvCnUzNEhLdldiQ0U5U2x5cnZRQnM4
        VlJWUzNOSi9FY3ZEb1dnRDM0VTM4YTgKLS0tIGtMYjA4UGVzNXdGdVRicjRVSHd1
        ZlB1cTNFR3BhK2U0VEdlQW9QY0ZCc2MKPhZvNtiOF9Kdyd6vRouAwURxWOTl+927
        f6IA/m4hReKXXEQkuRhe8ymkYFsArUjtbemcIc7Z5/3zGWgicFf1TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dEtxQVVHSWI1K1VzZ3B6
        cFgzL1lFTWpLcHk1azNiaWx6dkx2VmhxaUR3CkhkY1pjeEFYLy92cW5GVkpZWnFm
        Q2FKUHd5dVUxRDhINjBlN3RneUszUXcKLS0tIHZyV1ErZ1J2Q2cwNU1pdVpYUzB6
        VlpCVWN3bld5Z0V0Um5TcnBsUlk1YncKs6PxP+VlV+k5pzLGzSvG1sJnQdpGTxxj
        wIU86Fdh/p9gSl0oYlOFVLA/ldtSCnptmT58cnF+cnvVdWsZJq24Pw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-01T18:14:42Z"
  mac: ENC[AES256_GCM,data:dL+FFrQRqjtksLzucDdCwUDjjCMZMYqi0bY8+TZaiTRkLyk4bTU0oHT9en8ComUrou93WVmtS6LNIEMndP9fE5pbtNAUt8mqq4tUKmrCukQ/r/4bHsZcYV/sSwj7SNH6mAmzouPMNJJmBCWbSz3VKOMCA3J2PZRCn70Yi+HIH9s=,iv:IqoCHF3IPDUEZLAo/6IreZ5ReX8pDMKyh+QlAiuJiXk=,tag:hy7FTARW2Iq5xElvpotesQ==,type:str]
  version: 3.13.3
