apiVersion: v1
data:
  ca.crt: ENC[AES256_GCM,data:/HNz2KFUgYH2DuD/nIvzOXROuGlclVllbovk3qAArdeDXAPLlCs98F8w6u4IDCfa71BsBNdXRiaGt7E79slb9UlSPE6JQmcmfrkoNvdfbadgNUPhMRgZzwRK/YYMtBFScUM7eMKJvwdDSPeQNlmueOTnCsMGGBu7goLmxksAKdEGiklHJdZCI087mhWXcjmRjfFH2ZZa1wAsCws5G4/pCEII+Z8M2sToc3r65G0aUN+Rz/POIm4LsJp9cy/qOOvhOTKUf4704Luv4tHhPbxBzgrbsHhoUzXaF5zvyev49ScZbcdNR5jAeKNuZ4vzdReLPodKQ48yc6kGtcAysBvgXVJwsbQjfCBNRVOAbwGy47EpMdp3kvgaScH9BcuaCf63q7Y/3Kdq/heG6/xrjaNRLK7AZz+MwBEvNa6vpZyPhnixTBXEGHm3N8lPSTNkK+KjrruEdSUWzR7r3erjbJsSNSZx+CO5HPwFd3qRpWOl9Pm/38IUBvQXZhZ8ctFYs1SQR/uLwjbK3CnvBToGfL+fUjvP3EKq1Vg5RTPhc+i77lwMGMyVqAVCWHjGhf5dnAaihS0EH7ajsyg0ZDKXE7vvO65w6ajjoScrmfng+5t0TBqy2001Oqg/fLzKchvzNxFsIAz8XiH37k6JK1ijrncwWQHW6XDYTC+x9IwQWC1gXjOBHlbjK/61OxHrWDuNfjoZ61wOqtQSRlKOA2V8pLZJl2XbkBBx5ZxYR1/P30Ej95wjfoai9+lHZgFXAs4xStVZvqN3kxzneTtXiA8TI0g+4gVkxEK+23NiyR4QUYbX3aB5Mw0++9hfbBUsOP7ctCOVzflLVYBpFyFaayDnWi0in9KiBjsWu23ImO4LTr28iCp+1fA/F2l+8SgAMMF14jAq+NqxTRpLUhU3BK6sJGW9Fu/Z35Dxb7PMqPRJQR8KHBG+FGdZqQkPaizDgNNTr5rnNfifZMoXBY4D6hW0lbrTwNIwbFoZ0VLbnbVHxCpLdbO9MvsEExJcog==,iv:vQv7GITfGOtjgqqaQS2G6d48Fi3qIT6+5/BDXgknOxY=,tag:X45D+VJ+R0XKaDDOoYLg9g==,type:str]
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: cluster-api-operator
  name: rke2lab-tls-authority-ca
  namespace: capn-system
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dVFVVUhlMGpHSlk1RnVD
        cUtqSzNBOWlZZ2dGcWRydmJnbWFJZ2YzYVhnCjhYNEtsaDZ4TlpjTnNaWmIxU0RF
        c2RFaWFselNjN3NmQjZ2WmhlelljcW8KLS0tIEp1S0pQeXl6S2plQmlMNnNoYTNs
        Q04wVGdaYWlnWkduKy95TVNDS3Y2RmsKsI24XOGPi0dCSCsewf5TKlGcAcKWe6UE
        i/vP4XrCKgP3pgf2PUS9rckj/U/n2qVQICyyqVIfph7kiasZreH6bw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSElhTjZRcWI1VytuMXJy
        QUlvbWw1ZWs4NTVTY045ZG5NV1lvVXhxMWk0CmxNVHh4bWRXWm5GVkRyNmdvdDVl
        ZGc2S2VuOWdDczhhVXZFOTVudm5kUFEKLS0tIDgvd09xTk1XZUROTjFDV1R3ckhr
        RDRBYy95QjBOYWQzNXlOSFFqWk9ybmsKt/Cnp089VA7oPrXU4bNeQd1yZ9LQ54iz
        NMMiDYxGZxJ9I+zrJXTBJIrwXomhAt1JcH37qiKMGpwpO1VsmsL/sA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T23:33:37Z"
  mac: ENC[AES256_GCM,data:2IvHskeYLW9FwMk0xHQum7ZXiBu7eoMjtaECgWEep0eAgTV3Tz8YqDizfNeESFG3SOGSfXJrlUphxhWaFkZJpJxP7rtBzRvChO3HbM7CeOCvzGqkxunvKx2Cr32mFpk7YPqJcjxWT92QeIAuWYghTcBcXVVO0z+K/79xtoAyfoM=,iv:csiMXj5evxGISa3VF304psPqIz3eeRCO/kHQKu/aI24=,tag:Sz7cAySYSTbRJqfS8d9ZEg==,type:str]
  version: 3.13.3
