apiVersion: v1
data:
  ca.crt: ENC[AES256_GCM,data:pTtOgPgqj79G7FsDzxwNcJj84fSstMCcz4QiafETOx1yH43FoguTwNuU4aV0Zkdcj9+DNJGOjrTiFqEhlA+G6WD5zJmB/eBv+vWxaIpII4zxBj/4334fsYmq35/Ffz2HlMG4hkCXBhjy4GaYxEhcGBlXSh92Vrzucq26TLsieOo8R/LM/5OlGv2SpfRULD12v0ad232pSsFUHzuO0pLU0ITiZyu3Yc7WbUvkdWnFqT28T+yKYLFwxAhsgvf9vFLxHacRzhpT678anCQGi8ZYqqhkvnovLCnjb/5EcRsi9++NUlLIPqnYLDMfxut1L3mmQnWjvtCIjIXuMPXVqegCaBdf7Bt9NtpBUx3HdkPISn0mDu4hy/htrWxVJ15ZuoWdqJZ0GO1zX4RdDoR1szZ9Ry+BC5s0Xm3GJCbj+KQacd+8dZQfng6toD8Qla80a/TOhCh/R9Ttt4tBfcD7UtHet2Jz9DHVKqrDlG+eWKeyMZb0lRBk5rEDVAmY1IjCqQ6UlUrQyyp6jQZXx46oxYW8DZYkHrlOrFTB2uIYM94FEGLFjH7IJEdE2v0VQB2NkAL9fDD6ElWfuTr1zOvMNkwZVNKqo02j6mnvk2aOKy4myRb+51VqgzkXvbldDeUyhXSWsFKvz+V8hnxCHMdNwmwZQhVXBy8/TcAZpjQ21L2/LBMaJxlXtCE5rcU9gINlfztuYrn3r9k/CF8pNSyfR8uSH/kV9R2EaXmY8hFDo6KZ0JXkQBeCt0vuLego3lW0BNlnAWRbbOEt3bqPUuF914cmWpiq9KvNO15IDY4dMiBB4dslswzn+7dALW0pNsnB4A2xPjIl1AS2OcQPr3ZhM8usBK1xQ9Bbnt4yTSSnAzcJNB+mJXjbbx9fM4oah/CFz6Ny8XlFTMgGqqfK8BQYxgqhC1d4qgEQSnVhASA5vMoo1Aod1YB5Ockj7aY+oVx0VL4+RSyjLfmhywOsKmY/tTrIh50JWsxp8+vhj7kDfhsOQ2AY14Fa4rKscw==,iv:ZF2VfJZeP61HRWSAy25/1sbI/qmts7TMD1yVQXuA99A=,tag:RkInvn/Sbq2anzFxCkB5zQ==,type:str]
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: cluster-api-operator
  name: rke2lab-tls-authority-ca
  namespace: capn-system
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ0c5M1hNaDBKQmx0Y1ly
        SmxjcDBjYUpLRng1ZEhNenZBbCtHTW0yU2xnCktiYkFRa0sycVAydGhkRDNrNTRW
        OUlwMjBJTmhxSWhKZXZTbjhSQUtURjgKLS0tIExhWk00aEZRZVdhQjRhcmlIdFpr
        NXVWTkdFUUNJcnQ3dHFCU3RpUlIyNG8KEqlWGzIkaYy42jswRcOiy8VZVNp3y8HK
        fa9gr4LrbtIoZydIExb5rT9VotagCcevm+TGy8/QKIj5HdbO5sXtOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQVd0Wi9JanQrYzdERkxT
        ZStZazhHSE9RT2xpcjRvRzNiWnhZc24zYkJJCmNGaVRjakpVUjFrR3VYSTFOYnNi
        Qk5hdXQ5VGN4amVKUUJzV29EVXlRN0kKLS0tIGFNTUFkZVQ1Mzc1K2ttTnhGaUow
        cktrUlc3UFY4K05qakI2THNPMm5yQUUKNrtHS1ScazSTfXH0MU+npvodL3D2WpIw
        mZgMjs5oBYXfR+qmXa1Od82IMqseGkzYGs/FbXhK5Spx6eWY8D9APQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T23:33:43Z"
  mac: ENC[AES256_GCM,data:c+3lYAohlw3SZvEOkw0LTvv44wkNapVg3Y5ZOWvLw2kZJgOHQfcoDj2FIPHHoGyUe8T3mrCKFrhtozhgR6keMPybNRuNTyO5ryhu3CYn6IEaZfWWLykC7KWsXXd6pDKnogBssi7Ehl1z39vLnq9HmMrPdlip2uElb9gSkbbc4PU=,iv:lFT7ogLypdBkYDNR0fHC83v2RuSoNXgdBsZcXX7/2ZQ=,tag:p+QKWSP7y/Ys9D759saWTw==,type:str]
  version: 3.13.3
