apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: cluster-api-operator
  name: capn-provider-config
  namespace: capn-system
stringData:
  CAPN_VOLUMES: ENC[AES256_GCM,data:GOCQaF6COXzQiIGt67nxkTpzLQUUx4Vl403bJQ0klqI0NEQJmEE/fCr4c4S5zYVsK2iO5c+pyJPzpB/1XuFpIu51BQCtGOcLKztmfdoQbEauPPf1LRubMw==,iv:dusC6zA44LoYO6+/ZceQ/g6d/FPoSnF+ZJP3PM/RM14=,tag:mDSVFalfgmyKPzjsHXW7kw==,type:str]
  CAPN_VOLUME_MOUNTS: ENC[AES256_GCM,data:bY/oaJiA14YMTjBsgl34cgs+aGQclhY67DT3iSXF+frZR1WO1ICXpr2iOr98s447+HUH0ctUMcW4JRrwNS17Wyhk2tmrU+nBqFhRrZj9OcAaibU=,iv:ukcbPtqGvhJ9HX5oJldnh5FGnNXsX+NkAzNnnpbVnNQ=,tag:4qJtph5LXWCafbyqEgHzow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bnRrbkFIT3h6WDNnT0JG
        MzZya3hZWnplbGFicytkZEJIZGsrWmhvYVFnClZnTVNVcDFIZFNZaWJ2UXZPcmdD
        K01MNyttVmx1ZXJQemhhWG1NTEFZc2sKLS0tIEU2K25OaStBc3V1R25rTldZSUcv
        YzhTYjk4czNWbXkyV2hEVEJsZFBiZ0UKLLZhmVRl1cmNmjs/OkYkMT4QJiFUTYRq
        EuThnV09EKTBEgDqwXkz0WUXiArbB3WBhyQ+3bPC1R4Qohxhfr1pfg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S2t4WmpuaS9KWHR6aDdm
        cVNaNVRJaFlzNmkzbkZqM29jcllTRjlsVEZZCnBEb2pxbktsRG85S094RldoU05C
        QWNDWnppTGZlZHg3ZXZidFI3WU9PWWsKLS0tIDlDV29BTkU3RjdaYU5HQis2b3Y1
        M25oV0VGSnRuK3d0STg2L2c0NmdNWVEKXUXWiJ3tPjsehiI+j2HThQ6B9QJQVe9o
        mNA7QOgo4OQR2cF2uNtKvxvN44Ze8NULhpsxlrkPvklx8jM5Oau4Og==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T06:00:59Z"
  mac: ENC[AES256_GCM,data:9tkceUnkar7DKFAprFFcsgtbqr5iVgF1intwonLbllG4wZ+N69CHYLnolBho5Xa1bhohKAC+cjxIyR5iwMRXYFxBqTbxZXkjUNqfPLAmllp8r8TvdSyxfo6KqnLBXrLs4lFmaJNlV9/qxZSdmGujTsVAgnkQCouoWm8W58Z6UW4=,iv:uuDtA2wj42RwZrvWTpesPulp0okz9cKMyfWsJK95GX8=,tag:9PYMeX9diDFjDw7HH6rfVw==,type:str]
  version: 3.13.3
