apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: cluster-api-operator
  name: capn-provider-config
  namespace: capn-system
stringData:
  CAPN_VOLUMES: ENC[AES256_GCM,data:lhOUFkqQp6k26p2Q8kiUtpMAnRAkmKS3lChMiAGhHMSKq4wNWOZkMt7v+qSMbdFh6i+AYEZLt4WNsofW+iygRJUBAVeqz1zqB5bGymPYQIKM1gbiJIi6Pw==,iv:+9McmnpAimWaatL4XrHBPdHk7VuY42kJxY9LlhvBar4=,tag:31B8dfj5P2b67unQmQeXzw==,type:str]
  CAPN_VOLUME_MOUNTS: ENC[AES256_GCM,data:Y/4v6Bx6RqGHs11WsfWWaj6j7k134wLQtQV7RX0lEi23bNRMFsslelbLGaFmWDXaOlFXNVzylkLm++1n6QHGRLibqmKrvy/SzatDahtSl+P9FP8=,iv:QB6j8FYEQcT2AC0PuZGOQxohj7GjIwz6TgikfuIVYoE=,tag:BVYf9NSj67J4hJvlf3vSdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkR05qTy9CaXIwakFGSnpU
        eHdtaG9BQmdCZSszd1FseE1wVHdzRER3L0dNCmNzSUNhVjFxakhJZTE1eWFXeFdD
        ellLUEg1T3ZTT0c0bUVoUkFOdmF2UFEKLS0tIDVKZUxzM09lRXp6eGNDdDRNaDdH
        Ry9jQzJCUnBDQkJtQkdzVWtPdk84bjQKnlPF0nsq/mCyuZS+kchxsbBIpTTvmI3/
        abj81glLYHd/xj9gTu5XPMCxuHyruWS8cFB+TwI+r71K++SEzsJaCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRVBSWVdWSnA0OXJiakJK
        bThReUluMVBJZW9jaXE0OS9kQWNoLzdsdm5vCk5PYkJ6WEF1MlVyNEZkM0VGT2Nl
        MGtBQ0NOeGREZnBQRUtMREVxMDZ5a0UKLS0tIDBRQ2xWNFhITncwN3ZibFFZVnJ6
        TE9BUGZET3NzQU9saFZXd0gxR2RaYkEK+4BsnwpsPSkuTasrFaqWfNlYngsKT2mJ
        oywdKfRaQKqSGVVfjYHSJnnV0q/Sd4gGtK73daSGtWvAsFiwPCuDbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-01T20:48:42Z"
  mac: ENC[AES256_GCM,data:8tQpnqlsrn4GU/pKJF4ZMostDZzwsOKhKnaS+nCpL9kgBROGWkt77pkELIfARjYtl5UGDCScDn8ju5eFe9aPLucKGDWdXh0iQ6OuShM/uSTSetQM50+GxWnb+Rby7oydNnTIhDIyEwPv7QY2V0YxXF3+HQ8U4fp8xnce1yCGDfI=,iv:vRSiWsijPaxXDVI3qWtPVHbDQ+QRLrm+rtFQkjC05k4=,tag:b6Q26G0T8LjO7khlpRPBzA==,type:str]
  version: 3.13.3
