---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: runtime-flox-controller-workloads
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: cluster-runtime-system-namespace-foundation
  - name: cluster-runtime-system-namespace-workloads
  force: true
  interval: 5m
  path: ./workloads/runtime/flox-controller
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: rke2lab
  wait: true
