---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: runtime-flox-webhook-operators
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: cluster-runtime-system-namespace-foundation
  - name: cluster-runtime-system-namespace-workloads
  - name: platform-cert-manager-foundation
  - name: platform-cert-manager-workloads
  - name: platform-cluster-issuer-foundation
  - name: platform-cluster-issuer-workloads
  force: true
  interval: 5m
  path: ./operators/runtime/flox-webhook
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: rke2lab
  wait: true
