---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: funnel-cert-restore
  name: funnel-cert
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 16Mi
  claimRef:
    name: funnel-cert
    namespace: tailscale-system
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: tank/rke2lab/persist
    volumeHandle: funnel-cert
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: openebs.io/nodename
          operator: In
          values:
          - bioskop-mgmt-master
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-zfs-persist
  volumeMode: Filesystem
