---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cicd.yml
- cluster-api.yml
- cluster.yml
- gitops.yml
- high-availability.yml
- networking.yml
- platform.yml
- runtime.yml
- storage.yml
- tailscale.yml
