---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux/tailscale
  prune: true
  sourceRef:
    kind: GitRepository
    name: rke2lab
  wait: false
