apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-secrets
  namespace: mesh-system
stringData:
  cookie_secret: ENC[AES256_GCM,data:f7Rocm7b5bdnhbvIrwusyTAsaJiWGBlHxRBvN0IV2ho=,iv:tBHWUD8BZaShdOm4m+npv+fjXbM0VFbZO6cA2+NfOw8=,tag:LWaIjot8d+XIQ0xDGRmJug==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdFlmSld4N3pkYXNUS044
        bTMrQ25UWDJ1S21XdmRQTXNLSTQ5NkJyVERzCjR1czc4VS9vTmxFZll4U2hLR0VU
        cXcxVms0RGxFc2JZRkdXTFpwRy9PL1kKLS0tIFAxNVV3d0ZkTjU2NUE5WXJWUFZ1
        LzdCQnpkNllkcm5oUVFoYW9SZElhckEKO/U08I3SGD3Z78YVVHJYxyw8mTNCh6Xv
        J2ffRDqcBoESP/iNwa/AGM4Yuho6YMdPjzrwfM9duYyDpfmXCAncmg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRUZBWlZNTUQzUTlWZW1N
        TGwzdGdWTHhhR1VkQ2VZdnNJUitxYUM5MVZrClB2OUgyd0xObk1VZUxxckpVMEJ0
        cXRMaHkzdG1XZitHM2s5ZWtZQnYzaVUKLS0tIFZ6Snp4ajdFRVZuUG1PQmRDN3Rr
        VHNTK0E2M1NrbGhVck9iUVhqWGV5ZEUKd4Uu8xyvtGvIM7qE2ECzRBWIhdp/e4Ih
        SNDUDdsVqc2SwHPQYesNhQCJTehWz+6BLdxTzzqT5VlJHkPnKlcTsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T05:37:14Z"
  mac: ENC[AES256_GCM,data:GfE3+GPRd6jplrpzbWst/5mWv/yZTulRlRQGRq6AG4yGBS6EIzh2L5cgy+uiUEOxUZnriUf6DXyYQtJaNMet6snjwyia+zNsyQCoD6q7NNqP9ThhVyZfoJB1kaTe4rZQpU0JMVlXDCa+bleM2rn1tBC4WWAj50FxLRYfDGe5lko=,iv:R+zxEcS3bUGLX4Q0mSyzIHWeLyEFWdrKHO6VKK//wrQ=,tag:ODQzUveRvk63I1ZOUlliNw==,type:str]
  version: 3.13.3
