apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-config-tmpl
  namespace: mesh-system
stringData:
  config.yaml: ENC[AES256_GCM,data:v7+Y+UquGSabaq9uFtPRvZJlL9FkTQlnJUbL2ZQhhmXywUY3RaFX2ZTsoLlQY6jUUNsX+iKlc0d5vPBNx7JRjZsESWh2YWIDTWhwryaUjTMHJ6XVmBKEUxETFiuNXPB+zVPv+9mcBBhv/3z7MERFWN5nT11XQ7pSQrlmwKeC7WHXmKVIlhUtlM9mHF33eIGnGe1C0fl9oJTIJG7RohqGOQ8AheXpBX6tqhkwCoySfcMDhpjSslLcyBewOgIKGpYGIerzN9vI2N4iBTzKuE545FHpIGtYx9ecJXrmPGW2RzOUWNOBXjxSmZ3tddbOTs2ttVWq/rJKuquEDrlc3yEaYBsGQNwF4p5S6F9gKiYBoTkLZ2InJebOR4T0fNlgvaZFmr+1MajqCu/NgDyiM0ykj+3ybvfaSh1gTCdiaNgXjbzW5IXIkD5hVDrUJecwzZbeqsZWM86BLomvNc9pB8mqyvmpfxorLUXZ4jfe8qGMKn0T8jbLA55FDqvwTTC3TL6U0uPRB6uRMojOBVTjHVTvXHi3e/J+c4Ht943EmYeT09K78vQmwnXh7DWUAa7QyZ8FcGUIlGU+Dda+LAkDtNTW2nbWlIWW+tvg7ge0UuknWmIE+4adQD+up+8gwSqCbh3mo5zzjlIA5M+6WoMkcC/NkPXm2jBA6VcO50cJ3HCe21NCZtsh9b7H2cntJn15iqPTJxcCIWZlXjdBh8EGXOdoeIHmBRb+ZzlXgg2bwNCmedP33xb7Lb3DfLqbzw==,iv:YGuEeWA0g2MVpC3//vZrKNGJE43BERQClWhkS9Bry3o=,tag:2kveavg40R19lwWqBTUI4g==,type:str]
type: Opaque
sops:
  age:
    - recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQW9ZMzkvZjZWYVgyQU52
        SUFMU1QyaFhUZ2swYlpZc084OUo4eFNYdGk0Ckl0NUhUNkxRYWd5eDVmVThLUTJs
        OUhTK3VHYXR5bE1EK1F2WG4xVFZVOTQKLS0tIDh5L1lJZWhBS1pYNHdJeVZEUHli
        bkNkbzRMa0J4NUNsOTdxS3h1WjNQYncKFSrxLI210BvTD/EbzZ4OmeHIjcxYLX4z
        S6I+dqR7nDGtT0TJ8A3Ipj1++Ii4nKzloPSnwKq1UExiwrhyDMkuTw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeEx0SmxTMUlKeEYwVTNi
        WWJxWHVBNFlPY3hWdTRHZUh4cUUvczhFZ3lRCjBVeUhLL1gzWENYbnFmUFIwQUdv
        akNMeVgvZ2c0QXZIdDFWdCtYbmVsVmsKLS0tIGMrc3BsNXg0d3ZNdUk3Mjc3dzk4
        Y1Y0ekR3dVViRlduenlJZE0rU0sxbUUKnYAp/2tE0sMcVduhNSL3OAl+dsz7KO2V
        KgE/bgwJe5AJ6rzDjM7SV3CYZK8yGRB1ab8CHbozR78d0ftI1gxalA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-23T09:19:51Z"
  mac: ENC[AES256_GCM,data:KqjlvbkCtmujSm/cm0afzejDzeFC4LvOm57lWkDkfoRWipWaVS3KwjviNtQuKnaEjrpWo39YGz5OTsWn/i97+fIdJcdQXLdu/XPx+DLhZ4Mmp/SaYzqJjSfhi24mfqPpbs6s/EAoHP8rpBSOjE2NgFtOagZMVWZnkpCihY2qhRQ=,iv:7lGFT/VCAvN4FiYwwjlYda0aF6P1nU92DW3VDhwa1rk=,tag:xtwLvg4/SGmxPbKsd/28fA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
