apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-config-tmpl
  namespace: mesh-system
stringData:
  config.yaml: ENC[AES256_GCM,data:RH7dTWfYug/z2vZOkEfYolLCYj/rQiLC1ZRi8i1FRJRYav4b44iUnzzxmQ9/x4iTaoXf9zJ6dx61mKag44faPFU95HV0p97I2btaVnCfwjdGMraNq5aCSKiOcCsaSYoRKc9QO3JjXmVZt5QBsw6C1IBBqbXF6C/DltVLkW/YyCs0trydDrtbPcErbq//IyFn31p/0HTpcRLkNMLQoDRB9e0DDOjpByS0s5sxypgk/MP0NIrOTNvpxL7WVzSTMqehUgAxO1yHcI/xFmfvjrBYR4MnAfl2O4l/oJK0DPUTYt3nH5AOF0HBzIGSNZMbjsIYAEhxWKZKRefmIMCzzKNpoofQezoswms0DjaOkqjBBZePNr5CEMrF668jWDUGrm8w4UhP6g3B+CNpqjfl2zEyKH/JEaN4yWi5SArD77O1djlevsTx4sj50ZUREOm7scrMooOc0QFDnQI2l8oPu8hXD/TG+mzInn1uL/10n6PYy6mkivVh287qb472tBpsJVJXiW8sEWNJaPOiFNweHBj3ZFx4O+UVWPy7hrmNMFwYcbGpcmixcs/9nwg7PjBIuNgrVUkLsjA6Le5et+vfKwS0uvX04gzkDLg3mg5+kNZuMMghBn3qRcANYABGsJpFlnhRMyWm/DQKHzpgq3CcP7U2SkvNhBTsnFeCl7mfAPeqkKKVVP3NtLEd9C9ogAp2TJ5zCMID5O06cyWLapYvDKww6OVF90sk9zL3wZS0sar6uJIr5VFovTTAY8FLLQ==,iv:KO6SWKpL4cTwGZJyj+a3QWoXiy+zUHtkqnJa0hkwNSU=,tag:agTMvS8rbqxDPqLCZh6qvg==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZnByMVBXcDhGb29iQXlp
        WmxEdzdLMWQ3Q2NWMWdQcGdUa0xPay8yUFYwCnRMbDQyK3RTMFFBSUp0MkZVTGlO
        Wjl3UVVPb0hCU041aFMyZmYwb0NuYUUKLS0tIEFuMFJiOE5XNkhHRXZKRHdJWGFG
        YU1WWjNNZDV4KzdZbGtVTlNBWEU3aTAKXqAlIH7Wbm+zwNcLbBwuLKD4BfEJgdiM
        uDMDkGRdxjeUHscqBjySJs0IEk7o5hmIgi7uA9F0IlvhrCASDRX/1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWjU2Wlp4NVZlME1VTVh3
        cUN0Z3V0Tm5iUDcrYUFKZFhJNGxacTlwRDFRClcyYmVQNkR0QVBnaFladTRBWm9w
        eC9UN05YL1FnNDhtSEFGVUYvSjJkdFEKLS0tIEloZTRzUWFwZlgwU0M3S2c5a2VW
        Q2E0QXJIWmJXRU9vVTEzUmZyVUxqUDAKXK2OuNiE+bczgjRs0F3Sglse2GXPl2Gf
        DUuQCzHLtuQDzWnEw8i7KrG6U4s+KiobDbsK7+sAuhlRVyc0OzF4vA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T08:11:33Z"
  mac: ENC[AES256_GCM,data:A4VOhrWpvcf1I1NC8BVHNcaccgFlEBRkuGJBaG1gFQRq+wEEKuJzQ+C2HLDDRDGoUE1SzUZpCL7FK7EYuiGba9a31kCK/l+QfymKj0cidwYAtbNTUn0lZae4dZUSSWHKxJ0NI3i4gwMAZ8gO2CVyUtOu0xziiK8v7G1UooJtCaU=,iv:PtPNyE66KJK95Oc7hHBa05Ey/bghBiWYHTPl4nk/XXg=,tag:fe0vSAnM9ux6Hmrod9/etw==,type:str]
  version: 3.13.3
