apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-secrets
  namespace: mesh-system
stringData:
  cookie_secret: ENC[AES256_GCM,data:VLzJgeXf//1NXA1qWpfi7uzamWjnWZptq7tk/wtfz2Q=,iv:iXphyk1forqEgZvWg/W/Rob34olgZ1eF8R4KjVFI+ZY=,tag:UfdUXz0DaCPJ/H/sg5kTtw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQk1YbjVlRjgxRVhQSHpP
        L1BXd2o3ZTBPMHlCRk1sd3ZvOHFrNUFnQTNzCmQrOXM2L0N1aEh0cFhLMmVnVmEw
        Vm8yTlZKNHljTE1tMUtrenM4c0JVTmMKLS0tIE9NaVdkYVNWQnpINUFVT0xYTFRm
        M3h3Y2dvSzFualRabllOYUVJV2FRQmMKeg2jwNLJplnbVWmF3Fe7qmu4hE4f4d7E
        DJkq9ydaYHlCJljf1PDGKgQSvpL2U6hyM7GT+ffUd3K3H5TRnYUWbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTB0S1FSbGphcDBHRERQ
        UWRkcGEzK1RzQjFtVTFZSWY1RExZSmRwR3dRCkh5dVdYN200ZGRUQkJmeENmL25Q
        ZWgrV04rc2M2bjF6MW1JdHRpQ0N3KzgKLS0tIERIcTM1SHovQU12b3J6Mll5ak1k
        YTJMd3pCUExsUmdHSi9qbTI1a1VWRDgKJU3gE2L3jzPhG0g16Q2SbgQI7tjR1jjT
        aoftudFuTH0PPcZZlPZUIUAUVySs4Suy+iDR94i0aY2CxjM8wy3Vkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T21:27:18Z"
  mac: ENC[AES256_GCM,data:qzxMeKKXyjpRz8ewHUlEunWcg38NekXcf+n09dDJwhLLqqj+G+k4UVDrxilml+M32fZc1zvx6HMG9k9IW0sPkKd0jbFWSr8jM8DzPon6hR6PQM8IDPNwb26iE2yMmjzfVdoCGaNqNr3+RqM6rE4OyoTKZtLI2B63GavSe5H81ms=,iv:foUZns/PztpdHqqVhlEMczKlud03+6ROTYNsVFy5vjk=,tag:6peRrg+hUMNvAe+aAJkc2g==,type:str]
  version: 3.13.3
