apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-agent-auth
  namespace: mesh-system
stringData:
  preauthkey: ENC[AES256_GCM,data:NkqQTN6KDK9N1kuBZNGEG5ZxNXSAIoo//DEWNIeP/u08iQ==,iv:pAvO5p5VyL/mZWyZceU9TdUljZ+DNnAnDchuL4+kZwA=,tag:3+QxsXmixgHa1Kf9RQtRzw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMWFwWDdCdG16RENYcEhJ
        ZnQybkhvcjF1Z1pHVUR5VWJ4eThpaTgzZ0VvCllzVVlPUHd5dmZDTXBMTDNwY1ls
        VjhMTDE4OGN6YnhWZnBCOUZRV3JCb1kKLS0tIGYwVktLMUR6NEZrNXQyZFRtNWhk
        V1E1RVc3c2ErL1Z6QUV1azZkOW96eGcKo1mPHZrcQxvxGZNfJ1HPuTrio1mFQsDf
        vzdvsj7O3gi6UsnhF20tAUgQ1VoXUqLFiX1zub0EZfioNIJJv4DV1g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja0RycnN5eDlXRGVsSzBq
        ZGdUcUZtZ0tDL0ovR1o2UlVrTU9RTVRNNm1JCmVObCsxaHZGVmM1OThVSWNDT2xl
        YmJWdFFicFVVWktxWGlvT093dDJiWkEKLS0tIEtTTEtnVXNhVXppbWRFdnM4OExF
        cTZzNndUWCs0Y2UxbUk3eTZrem5INEUKVb2bibXbrhcc/zdeROLxclLxKcuaBqGg
        n5q4NMT7BZEAD+SLaZjTUMRurdTkILdC8Q8C4cut6jzFTD0GF0/CpA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T22:09:08Z"
  mac: ENC[AES256_GCM,data:dFEdZ2LCN9TPILRWfw64YnbwariaSeVczDbcVs7fBxCtGdEdly2XHaD+GZtJAnfp6PBiWjkrjvRmYgCu3s2tLJRVst2rrkPIVCxsRVhtUHEFhEPKLo4YVZmXVD8aE6kKd5PxZmzZmj4GWpu2TEDSDuSY8I2fdKEyd1EZBTV+IL4=,iv:4t+5FCXlDelKXHw0SyeFeXAHTV+tmFB4OOSCA+3HoiM=,tag:tsc1tqMuqXLQgtih7Bld8A==,type:str]
  version: 3.13.3
