apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-agent-auth
  namespace: mesh-system
stringData:
  preauthkey: ENC[AES256_GCM,data:ZC/CqX+BgBuSr6eaokf8U9RDAcx6zMhKmHnYmmnDGRyccA==,iv:RDBfinEE2fRIWzkksYNPfith1SlmWPDlNSBGgTlXt1g=,tag:rKP83e7E7XdIimnx5P9VQg==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDRlMXZ5TFVzTnFhbG91
        NjF0cGJmblk2cVkyZUVoQVAwaFkzS3F2ZHc0Cm5uODhQb1VEamZOV1pweWJUQlE4
        S1pqSENRbGFvSi9NRmdFbWZaOEZQWkkKLS0tIHd6amNqTDhXUkMxZmdrcG1lRFcv
        Z0FTemxjc2xlQWxjVjhENFhJUXRBZ2MK9dfz+RbLpe9SCsYbQec8uHm+PK9i4qqV
        BvsWDpTzoWOdkydBWs7EcPuVCVSbs0UEaO6n5nv7qbETJu3l2Pwu1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVWRFbVZ0dmQ5N3pqNVlS
        TVFSd2hDZFJpd1RrMlJFZk52ZmVRVWpvaFdnCndrcXpMWlBnQkhuTDVjQmdZUzha
        OG1qYU8rTnYreVFiK0p1Wm1rUzdZdGsKLS0tIGRFZHpkaXY1UVEvSTBJZXVpQUcr
        RHZEVEI0ZSthTkY2NVkvV2VxTk9PTkUKcsMEVYO4pzDny6rjloSsPpBpgPHCoIlO
        MZH9f3/CdOI1e+cSbZpn4TKAroTce4E8Yi+q0eXmAvziyeIdcK1cuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T08:11:33Z"
  mac: ENC[AES256_GCM,data:mKecc8KUR8YAfB1xejSf+eCzUUSxVyQ8nmHItL03lVc2nvhK9xioA4tAXYuUIYI/O1lXmCzNcmkItcEp3CN1mo7RhC1vjyeVdeVEoMUlsE8NlnUGTNnWTe+9WQor0HkU36JyNybH9tCIvgQVh3xUduz+V9L6nhKaH8zSPVDk8sQ=,iv:B92Dyq7db14nx0hf89NIOfDL5lUd0Qy6kvRmFCbtbTI=,tag:a9EojpTY47r7E5ZFE8GWxA==,type:str]
  version: 3.13.3
