apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-config-tmpl
  namespace: mesh-system
stringData:
  config.yaml: ENC[AES256_GCM,data:4TpuGRSvsRnSlbOO4NCJUVdFPWrWhk8J9JH0pMvjj1YG4nnItI8dGAwvRpHng7cYo4VyIHLnfeWryx20fP8/MunTKLKYvfebkbeoNdQifRk7yJ1CWp21L3yDoPwKGSamtBuvYp4uG/wpxetBeCHjsU/p3EwoiSwkKfQMwcEl/8C3LKYm92ga8rr0nwzNUNhpyJsgWyqk9fuHAkiriqT6GLoT24i5q5NeYmIFfSmLDbqymzwV+sJzA14PhHiqtfgLcxmZfNJ6bHJTZ1kQYUDcTc/j8SK4jz+S11YlvJikyOHKhRSd8xP9r18GWNJLVIW3DjGaCN0LFIu14P+RTdfN34ic8lDk7hzUB1tBUOmsc6bhnbt6JuNO3/NQBh6AS8wyfRGbKhV4UtG8NVOb8726rYFwQ9PW36YevDCpwIpZFehx4VCTaYfmBrQvWlGgVauRj6NjtHJkB6WEbErxBuFb7QJaecGg8bb+ParLTYU/oFN8zPV02Wb5QMyHrW6SHSVfcOhQr3n1L30M2VrkwBSmi69xEv2AG4SImbIv2wHO7zIAdhyM/tnx4JE7M6VpufcbQ/lxnl5Jw3EQu/9FNQcHazQ+9urZaxZNjMZER35ycOXCd7FIZjdnLTTHUbNoeGn8gqt03WEBMBOySiwzfQ7XzwAm5+h+zHECGhYJ9zgJGBmmLYYuYn4DU44X/ni4c5l4hC/kwb9Fy3lynq+TcjKe527CqYsp2oS7TiqLTEe6ZWzV7Ao1bIe8P9TJbA==,iv:YqJXJMdMNelocNasmKEBxUsgCb++pqASV030de+EEFA=,tag:cOqLtrNb0+fyrKQba/ZpCA==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbzV6UlkxQ0NOL1VQVlFu
        MUtUUitNZXpGR3M2RzFkMnNqQ3g3TEZnbVNBCkt4dFhWSE9DZzhlWTd4V1V6OHBE
        NEE0ckJ5SlJ6Vytpc2ZENW53eUt5a2cKLS0tIDNGam5yc3FxSXJMSXJzZWJrdUMr
        SVdhY04vckFwRnRDRHVLN3IrNG1KRWcKRs0fD1cvEOD1QKj6LtsZYhQd2VdcqJZu
        sW2uOLS5dEQeK1t1BqhqDPNPr+nmAHh95WJXu1Fy28sCgs5mzIakAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU1dTbXk3YnJpNXFDN2hl
        bzVjTDdwaWhicTZKZ3NOV2dGTHRhMG94UVRBCmRadGZHT0g4akpoVFU2THBMZmVX
        NjM5a2twbDFyRCtDZkg3QWFpQk92M0EKLS0tIFZJVEJyVEhDSk1NTWFnVmpoMFND
        SFYyQWFxaTM4em9xcDEyTStFbmRMRlkKjQP0uN6r36HK6F4XXaSmeFZlQyv5i0z+
        qbOmymi3JSfBwAJVl3FO42arfqUr47K9+Wn2ksPMN80O7XDqbRbD3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T08:48:21Z"
  mac: ENC[AES256_GCM,data:wtQoHpb3Zu3A9S2wH/QwHSbtLUNolo9s5Rn2lej3nj4Nzih8BHSrsdwVTh+p22fxtj49iDysCCv4m0O5BVg/Ky4mki/+V2RwtO7Ndvifj3ckwkCHiR+VY9A90c4/rI737NyLRvAeQvpxJUe6gjcBvKLrm8gZxesr6CcSTvqt0pQ=,iv:vLH9BF+rLM2RNY0MnV7qMJhhrTi8s+mGlUzI06Sc9xQ=,tag:rfNNpr6/TYU3JzE9iUjytQ==,type:str]
  version: 3.13.3
