apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-agent-auth
  namespace: mesh-system
stringData:
  preauthkey: ENC[AES256_GCM,data:iKF5jRUoo2a8oVV1PJ6RJPOC5Dml/irt66UibeH4BjeZ/A==,iv:aGqXi/vbpvCt2muvQzGD3dOA52gNKyIzw5Fyrnryx28=,tag:LWEkc8xVDryjOBIKereQXA==,type:str]
type: Opaque
sops:
  age:
    - recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvY1Bna0luMHhDaERxUnZ4
        d3d5cW0vM2xac3pvb2ZKWWxmWTVzOVB4YjFZCmNYYnJUTHBZeG1yRW1VSHFrUERD
        SW5BYTRXeXpJM1R5S1pNQ1dKL1ZENTgKLS0tIHd5dnc5dG9IZTNjelcwN1Nyb1Mz
        Q2QzYzNhM095QXR5V2YvM1IxczFDWDAKa4N5QJIIdAefHEXothDZw0k3Th2UXesI
        xIwex/1JvktskT/UadwmBJS4Yplb+lLyvt9IutumpnDCt+tkWyW0hA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdHJBbzd5MEQ0VFAyY2t2
        TWFSTjlMZUV2ZmtRd24rZ2ZuSWkyeTNTcGp3ClMxQUI3ZlMzQ2hBck0yU3l6ZlVV
        MjU3RGNGRUlyK01JUWZSSjBGMFhpeTAKLS0tIFNQQVJhcDREb1RINTRzaE5sYUkz
        QTZsRk1WTVdIQ09rN1d6TkZpV2k2Zm8K71OOSnecYLU7/PIDkRv8NjgpOIZ1v+fP
        ZQm7cw8bWkA6QeTR+xkfVPr8ZlM7xh5IUmaLEsaclB8Hluh546+lsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-23T05:42:31Z"
  mac: ENC[AES256_GCM,data:Atb/00ce6QMjeSGCo7WFjkJdaWMBPy/rvub/EoVU9iiMOlZpcCpU2eted7zMs476Zwj65qhIWDLc0+osWBa9ItbPiFGAsWEpFUtkq3ookXIZrAqoKjY1Fl3QJOULl3rdA4PskFEZz9WwSiqz5LVuLotrezOMgfOaLQ48bjX5xpk=,iv:yuZGCzbNoBANpg8HYjRC3ND7Sx5U619HIjnyeSXgM70=,tag:B8UGY2dqavE2Ik0Z0mBNQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
