apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-secrets
  namespace: mesh-system
stringData:
  cookie_secret: ENC[AES256_GCM,data:5hZ8jMt2s1QNq333ek2kaulNv1Cwt4nSC1gtRO6M4qg=,iv:9I8FrVddJedmcWRyd16PNZTT8mmLVJdT5jeWqfsJAlE=,tag:o05ViAXxtBQl2biSRM/TMg==,type:str]
type: Opaque
sops:
  age:
    - recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRGZ0UCtRbDFRYm5ERGFu
        K3lFQURPTzdOZWowVzdMZXhVNWZGOVF4L2pRCitndEx1TlQwdThEUjZSWnAyV3h4
        WVZRSmJTaWZnNkJUUDViL0doNmlqRWMKLS0tIHp5YzRGd2ZYbnpjTGs4YVJDSC9Y
        V2gyaUEybUphb1F1TFR3bG5aWFhCVzQKXvbWsIMLe1PjetYrQrCnQI40DxbBmzN5
        G5OwloMbgPr8+P2BNIgZ3sLTZHNaHEZgGUc/ftw7sVuYiXP/7Rj3eg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMitRNUI0RXIyeDl0b3Zm
        b05HL0tZSXlyaFlFRGpwdG5LaXZQbjQrQVZJClUxM0RQWDhsT1Y1TmFHcjFiNHFr
        RjRGQWd6UXdISUROZE5DNTBYakhoZjQKLS0tIGJ3aDc1WlBKMFNjN0RnbGVvQWpX
        QXVXTDVjWndBZFdxTUdOWDcrMC8wZncKXLfeSVYmqNU2YszOwhz5CUdy5sLLd/Ef
        2zQRE8454QvWKc84pzttuYCGbDb+AKMPZDSUDuQs1v7278Leo4xGLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-23T12:53:50Z"
  mac: ENC[AES256_GCM,data:MfpxC3ewk4+Q/pRsPDaGnbPmn2br4CghmZRSPm798n4Hi5jsmeSXqLdlGRSHdgKAfpFNMDAEcP6/iH+r1DOb3vGYDakl4IDC7DO2DSPMXAxWVTqFVVJ2mDeDTcMbIhb1HHk0LspT+dUPz8Zp03DAzcvnKH32xj+oLFIW4avOZ4o=,iv:LscMft5xJ+/I5BK78I+itnbDL1SYL2VbvxR+vd8jU4c=,tag:TE9gMj8h6Fl5tf7ltFPjmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
