// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class GetCertificateArgs extends com.pulumi.resources.InvokeArgs {

  public static final GetCertificateArgs Empty = new GetCertificateArgs();

  @Import(name = "certificate")
  private @Nullable Output<String> certificate;

  public Optional<Output<String>> certificate() {
    return Optional.ofNullable(this.certificate);
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "fingerprint", required = true)
  private Output<String> fingerprint;

  public Output<String> fingerprint() {
    return this.fingerprint;
  }

  @Import(name = "name")
  private @Nullable Output<String> name;

  public Optional<Output<String>> name() {
    return Optional.ofNullable(this.name);
  }

  @Import(name = "projects")
  private @Nullable Output<List<String>> projects;

  public Optional<Output<List<String>>> projects() {
    return Optional.ofNullable(this.projects);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "restricted")
  private @Nullable Output<Boolean> restricted;

  public Optional<Output<Boolean>> restricted() {
    return Optional.ofNullable(this.restricted);
  }

  @Import(name = "type")
  private @Nullable Output<String> type;

  public Optional<Output<String>> type() {
    return Optional.ofNullable(this.type);
  }

  private GetCertificateArgs() {}

  private GetCertificateArgs(GetCertificateArgs $) {
    this.certificate = $.certificate;
    this.description = $.description;
    this.fingerprint = $.fingerprint;
    this.name = $.name;
    this.projects = $.projects;
    this.remote = $.remote;
    this.restricted = $.restricted;
    this.type = $.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetCertificateArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private GetCertificateArgs $;

    public Builder() {
      $ = new GetCertificateArgs();
    }

    public Builder(GetCertificateArgs defaults) {
      $ = new GetCertificateArgs(Objects.requireNonNull(defaults));
    }

    public Builder certificate(@Nullable Output<String> certificate) {
      $.certificate = certificate;
      return this;
    }

    public Builder certificate(String certificate) {
      return certificate(Output.of(certificate));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    public Builder fingerprint(Output<String> fingerprint) {
      $.fingerprint = fingerprint;
      return this;
    }

    public Builder fingerprint(String fingerprint) {
      return fingerprint(Output.of(fingerprint));
    }

    public Builder name(@Nullable Output<String> name) {
      $.name = name;
      return this;
    }

    public Builder name(String name) {
      return name(Output.of(name));
    }

    public Builder projects(@Nullable Output<List<String>> projects) {
      $.projects = projects;
      return this;
    }

    public Builder projects(List<String> projects) {
      return projects(Output.of(projects));
    }

    public Builder projects(String... projects) {
      return projects(List.of(projects));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public Builder restricted(@Nullable Output<Boolean> restricted) {
      $.restricted = restricted;
      return this;
    }

    public Builder restricted(Boolean restricted) {
      return restricted(Output.of(restricted));
    }

    public Builder type(@Nullable Output<String> type) {
      $.type = type;
      return this;
    }

    public Builder type(String type) {
      return type(Output.of(type));
    }

    public GetCertificateArgs build() {
      if ($.fingerprint == null) {
        throw new MissingRequiredPropertyException("GetCertificateArgs", "fingerprint");
      }
      return $;
    }
  }
}
