// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class GetCertificatePlainArgs extends com.pulumi.resources.InvokeArgs {

  public static final GetCertificatePlainArgs Empty = new GetCertificatePlainArgs();

  @Import(name = "certificate")
  private @Nullable String certificate;

  public Optional<String> certificate() {
    return Optional.ofNullable(this.certificate);
  }

  @Import(name = "description")
  private @Nullable String description;

  public Optional<String> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "fingerprint", required = true)
  private String fingerprint;

  public String fingerprint() {
    return this.fingerprint;
  }

  @Import(name = "name")
  private @Nullable String name;

  public Optional<String> name() {
    return Optional.ofNullable(this.name);
  }

  @Import(name = "projects")
  private @Nullable List<String> projects;

  public Optional<List<String>> projects() {
    return Optional.ofNullable(this.projects);
  }

  @Import(name = "remote")
  private @Nullable String remote;

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "restricted")
  private @Nullable Boolean restricted;

  public Optional<Boolean> restricted() {
    return Optional.ofNullable(this.restricted);
  }

  @Import(name = "type")
  private @Nullable String type;

  public Optional<String> type() {
    return Optional.ofNullable(this.type);
  }

  private GetCertificatePlainArgs() {}

  private GetCertificatePlainArgs(GetCertificatePlainArgs $) {
    this.certificate = $.certificate;
    this.description = $.description;
    this.fingerprint = $.fingerprint;
    this.name = $.name;
    this.projects = $.projects;
    this.remote = $.remote;
    this.restricted = $.restricted;
    this.type = $.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetCertificatePlainArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private GetCertificatePlainArgs $;

    public Builder() {
      $ = new GetCertificatePlainArgs();
    }

    public Builder(GetCertificatePlainArgs defaults) {
      $ = new GetCertificatePlainArgs(Objects.requireNonNull(defaults));
    }

    public Builder certificate(@Nullable String certificate) {
      $.certificate = certificate;
      return this;
    }

    public Builder description(@Nullable String description) {
      $.description = description;
      return this;
    }

    public Builder fingerprint(String fingerprint) {
      $.fingerprint = fingerprint;
      return this;
    }

    public Builder name(@Nullable String name) {
      $.name = name;
      return this;
    }

    public Builder projects(@Nullable List<String> projects) {
      $.projects = projects;
      return this;
    }

    public Builder projects(String... projects) {
      return projects(List.of(projects));
    }

    public Builder remote(@Nullable String remote) {
      $.remote = remote;
      return this;
    }

    public Builder restricted(@Nullable Boolean restricted) {
      $.restricted = restricted;
      return this;
    }

    public Builder type(@Nullable String type) {
      $.type = type;
      return this;
    }

    public GetCertificatePlainArgs build() {
      if ($.fingerprint == null) {
        throw new MissingRequiredPropertyException("GetCertificatePlainArgs", "fingerprint");
      }
      return $;
    }
  }
}
