// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class InstanceExecArgs extends com.pulumi.resources.ResourceArgs {

  public static final InstanceExecArgs Empty = new InstanceExecArgs();

  @Import(name = "commands", required = true)
  private Output<List<String>> commands;

  public Output<List<String>> commands() {
    return this.commands;
  }

  @Import(name = "environment")
  private @Nullable Output<Map<String, String>> environment;

  public Optional<Output<Map<String, String>>> environment() {
    return Optional.ofNullable(this.environment);
  }

  @Import(name = "gid")
  private @Nullable Output<Double> gid;

  public Optional<Output<Double>> gid() {
    return Optional.ofNullable(this.gid);
  }

  @Import(name = "timeout")
  private @Nullable Output<String> timeout;

  public Optional<Output<String>> timeout() {
    return Optional.ofNullable(this.timeout);
  }

  @Import(name = "trigger")
  private @Nullable Output<String> trigger;

  public Optional<Output<String>> trigger() {
    return Optional.ofNullable(this.trigger);
  }

  @Import(name = "uid")
  private @Nullable Output<Double> uid;

  public Optional<Output<Double>> uid() {
    return Optional.ofNullable(this.uid);
  }

  @Import(name = "workingDir")
  private @Nullable Output<String> workingDir;

  public Optional<Output<String>> workingDir() {
    return Optional.ofNullable(this.workingDir);
  }

  private InstanceExecArgs() {}

  private InstanceExecArgs(InstanceExecArgs $) {
    this.commands = $.commands;
    this.environment = $.environment;
    this.gid = $.gid;
    this.timeout = $.timeout;
    this.trigger = $.trigger;
    this.uid = $.uid;
    this.workingDir = $.workingDir;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(InstanceExecArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private InstanceExecArgs $;

    public Builder() {
      $ = new InstanceExecArgs();
    }

    public Builder(InstanceExecArgs defaults) {
      $ = new InstanceExecArgs(Objects.requireNonNull(defaults));
    }

    public Builder commands(Output<List<String>> commands) {
      $.commands = commands;
      return this;
    }

    public Builder commands(List<String> commands) {
      return commands(Output.of(commands));
    }

    public Builder commands(String... commands) {
      return commands(List.of(commands));
    }

    public Builder environment(@Nullable Output<Map<String, String>> environment) {
      $.environment = environment;
      return this;
    }

    public Builder environment(Map<String, String> environment) {
      return environment(Output.of(environment));
    }

    public Builder gid(@Nullable Output<Double> gid) {
      $.gid = gid;
      return this;
    }

    public Builder gid(Double gid) {
      return gid(Output.of(gid));
    }

    public Builder timeout(@Nullable Output<String> timeout) {
      $.timeout = timeout;
      return this;
    }

    public Builder timeout(String timeout) {
      return timeout(Output.of(timeout));
    }

    public Builder trigger(@Nullable Output<String> trigger) {
      $.trigger = trigger;
      return this;
    }

    public Builder trigger(String trigger) {
      return trigger(Output.of(trigger));
    }

    public Builder uid(@Nullable Output<Double> uid) {
      $.uid = uid;
      return this;
    }

    public Builder uid(Double uid) {
      return uid(Output.of(uid));
    }

    public Builder workingDir(@Nullable Output<String> workingDir) {
      $.workingDir = workingDir;
      return this;
    }

    public Builder workingDir(String workingDir) {
      return workingDir(Output.of(workingDir));
    }

    public InstanceExecArgs build() {
      if ($.commands == null) {
        throw new MissingRequiredPropertyException("InstanceExecArgs", "commands");
      }
      return $;
    }
  }
}
