// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class InstanceInterfacesIpAddressArgs extends com.pulumi.resources.ResourceArgs {

  public static final InstanceInterfacesIpAddressArgs Empty = new InstanceInterfacesIpAddressArgs();

  /** IP address */
  @Import(name = "address")
  private @Nullable Output<String> address;

  /**
   * @return IP address
   */
  public Optional<Output<String>> address() {
    return Optional.ofNullable(this.address);
  }

  /** IP family (inet, inet6) */
  @Import(name = "family")
  private @Nullable Output<String> family;

  /**
   * @return IP family (inet, inet6)
   */
  public Optional<Output<String>> family() {
    return Optional.ofNullable(this.family);
  }

  /** Scope (local, global, link) */
  @Import(name = "scope")
  private @Nullable Output<String> scope;

  /**
   * @return Scope (local, global, link)
   */
  public Optional<Output<String>> scope() {
    return Optional.ofNullable(this.scope);
  }

  private InstanceInterfacesIpAddressArgs() {}

  private InstanceInterfacesIpAddressArgs(InstanceInterfacesIpAddressArgs $) {
    this.address = $.address;
    this.family = $.family;
    this.scope = $.scope;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(InstanceInterfacesIpAddressArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private InstanceInterfacesIpAddressArgs $;

    public Builder() {
      $ = new InstanceInterfacesIpAddressArgs();
    }

    public Builder(InstanceInterfacesIpAddressArgs defaults) {
      $ = new InstanceInterfacesIpAddressArgs(Objects.requireNonNull(defaults));
    }

    /**
     * @param address IP address
     * @return builder
     */
    public Builder address(@Nullable Output<String> address) {
      $.address = address;
      return this;
    }

    /**
     * @param address IP address
     * @return builder
     */
    public Builder address(String address) {
      return address(Output.of(address));
    }

    /**
     * @param family IP family (inet, inet6)
     * @return builder
     */
    public Builder family(@Nullable Output<String> family) {
      $.family = family;
      return this;
    }

    /**
     * @param family IP family (inet, inet6)
     * @return builder
     */
    public Builder family(String family) {
      return family(Output.of(family));
    }

    /**
     * @param scope Scope (local, global, link)
     * @return builder
     */
    public Builder scope(@Nullable Output<String> scope) {
      $.scope = scope;
      return this;
    }

    /**
     * @param scope Scope (local, global, link)
     * @return builder
     */
    public Builder scope(String scope) {
      return scope(Output.of(scope));
    }

    public InstanceInterfacesIpAddressArgs build() {
      return $;
    }
  }
}
