// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class InstanceInterfacesArgs extends com.pulumi.resources.ResourceArgs {

  public static final InstanceInterfacesArgs Empty = new InstanceInterfacesArgs();

  /** IP addresses assigned to the interface */
  @Import(name = "ipAddresses")
  private @Nullable Output<List<InstanceInterfacesIpAddressArgs>> ipAddresses;

  /**
   * @return IP addresses assigned to the interface
   */
  public Optional<Output<List<InstanceInterfacesIpAddressArgs>>> ipAddresses() {
    return Optional.ofNullable(this.ipAddresses);
  }

  /** Name of the network interface within an instance */
  @Import(name = "name")
  private @Nullable Output<String> name;

  /**
   * @return Name of the network interface within an instance
   */
  public Optional<Output<String>> name() {
    return Optional.ofNullable(this.name);
  }

  /** State of the network interface (up, down) */
  @Import(name = "state")
  private @Nullable Output<String> state;

  /**
   * @return State of the network interface (up, down)
   */
  public Optional<Output<String>> state() {
    return Optional.ofNullable(this.state);
  }

  /** Type of the network interface (link, local, global) */
  @Import(name = "type")
  private @Nullable Output<String> type;

  /**
   * @return Type of the network interface (link, local, global)
   */
  public Optional<Output<String>> type() {
    return Optional.ofNullable(this.type);
  }

  private InstanceInterfacesArgs() {}

  private InstanceInterfacesArgs(InstanceInterfacesArgs $) {
    this.ipAddresses = $.ipAddresses;
    this.name = $.name;
    this.state = $.state;
    this.type = $.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(InstanceInterfacesArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private InstanceInterfacesArgs $;

    public Builder() {
      $ = new InstanceInterfacesArgs();
    }

    public Builder(InstanceInterfacesArgs defaults) {
      $ = new InstanceInterfacesArgs(Objects.requireNonNull(defaults));
    }

    /**
     * @param ipAddresses IP addresses assigned to the interface
     * @return builder
     */
    public Builder ipAddresses(
        @Nullable Output<List<InstanceInterfacesIpAddressArgs>> ipAddresses) {
      $.ipAddresses = ipAddresses;
      return this;
    }

    /**
     * @param ipAddresses IP addresses assigned to the interface
     * @return builder
     */
    public Builder ipAddresses(List<InstanceInterfacesIpAddressArgs> ipAddresses) {
      return ipAddresses(Output.of(ipAddresses));
    }

    /**
     * @param ipAddresses IP addresses assigned to the interface
     * @return builder
     */
    public Builder ipAddresses(InstanceInterfacesIpAddressArgs... ipAddresses) {
      return ipAddresses(List.of(ipAddresses));
    }

    /**
     * @param name Name of the network interface within an instance
     * @return builder
     */
    public Builder name(@Nullable Output<String> name) {
      $.name = name;
      return this;
    }

    /**
     * @param name Name of the network interface within an instance
     * @return builder
     */
    public Builder name(String name) {
      return name(Output.of(name));
    }

    /**
     * @param state State of the network interface (up, down)
     * @return builder
     */
    public Builder state(@Nullable Output<String> state) {
      $.state = state;
      return this;
    }

    /**
     * @param state State of the network interface (up, down)
     * @return builder
     */
    public Builder state(String state) {
      return state(Output.of(state));
    }

    /**
     * @param type Type of the network interface (link, local, global)
     * @return builder
     */
    public Builder type(@Nullable Output<String> type) {
      $.type = type;
      return this;
    }

    /**
     * @param type Type of the network interface (link, local, global)
     * @return builder
     */
    public Builder type(String type) {
      return type(Output.of(type));
    }

    public InstanceInterfacesArgs build() {
      return $;
    }
  }
}
