// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class NetworkAclEgressArgs extends com.pulumi.resources.ResourceArgs {

  public static final NetworkAclEgressArgs Empty = new NetworkAclEgressArgs();

  @Import(name = "action", required = true)
  private Output<String> action;

  public Output<String> action() {
    return this.action;
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "destination")
  private @Nullable Output<String> destination;

  public Optional<Output<String>> destination() {
    return Optional.ofNullable(this.destination);
  }

  @Import(name = "destinationPort")
  private @Nullable Output<String> destinationPort;

  public Optional<Output<String>> destinationPort() {
    return Optional.ofNullable(this.destinationPort);
  }

  @Import(name = "icmpCode")
  private @Nullable Output<String> icmpCode;

  public Optional<Output<String>> icmpCode() {
    return Optional.ofNullable(this.icmpCode);
  }

  @Import(name = "icmpType")
  private @Nullable Output<String> icmpType;

  public Optional<Output<String>> icmpType() {
    return Optional.ofNullable(this.icmpType);
  }

  @Import(name = "protocol")
  private @Nullable Output<String> protocol;

  public Optional<Output<String>> protocol() {
    return Optional.ofNullable(this.protocol);
  }

  @Import(name = "source")
  private @Nullable Output<String> source;

  public Optional<Output<String>> source() {
    return Optional.ofNullable(this.source);
  }

  @Import(name = "sourcePort")
  private @Nullable Output<String> sourcePort;

  public Optional<Output<String>> sourcePort() {
    return Optional.ofNullable(this.sourcePort);
  }

  @Import(name = "state", required = true)
  private Output<String> state;

  public Output<String> state() {
    return this.state;
  }

  private NetworkAclEgressArgs() {}

  private NetworkAclEgressArgs(NetworkAclEgressArgs $) {
    this.action = $.action;
    this.description = $.description;
    this.destination = $.destination;
    this.destinationPort = $.destinationPort;
    this.icmpCode = $.icmpCode;
    this.icmpType = $.icmpType;
    this.protocol = $.protocol;
    this.source = $.source;
    this.sourcePort = $.sourcePort;
    this.state = $.state;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(NetworkAclEgressArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private NetworkAclEgressArgs $;

    public Builder() {
      $ = new NetworkAclEgressArgs();
    }

    public Builder(NetworkAclEgressArgs defaults) {
      $ = new NetworkAclEgressArgs(Objects.requireNonNull(defaults));
    }

    public Builder action(Output<String> action) {
      $.action = action;
      return this;
    }

    public Builder action(String action) {
      return action(Output.of(action));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    public Builder destination(@Nullable Output<String> destination) {
      $.destination = destination;
      return this;
    }

    public Builder destination(String destination) {
      return destination(Output.of(destination));
    }

    public Builder destinationPort(@Nullable Output<String> destinationPort) {
      $.destinationPort = destinationPort;
      return this;
    }

    public Builder destinationPort(String destinationPort) {
      return destinationPort(Output.of(destinationPort));
    }

    public Builder icmpCode(@Nullable Output<String> icmpCode) {
      $.icmpCode = icmpCode;
      return this;
    }

    public Builder icmpCode(String icmpCode) {
      return icmpCode(Output.of(icmpCode));
    }

    public Builder icmpType(@Nullable Output<String> icmpType) {
      $.icmpType = icmpType;
      return this;
    }

    public Builder icmpType(String icmpType) {
      return icmpType(Output.of(icmpType));
    }

    public Builder protocol(@Nullable Output<String> protocol) {
      $.protocol = protocol;
      return this;
    }

    public Builder protocol(String protocol) {
      return protocol(Output.of(protocol));
    }

    public Builder source(@Nullable Output<String> source) {
      $.source = source;
      return this;
    }

    public Builder source(String source) {
      return source(Output.of(source));
    }

    public Builder sourcePort(@Nullable Output<String> sourcePort) {
      $.sourcePort = sourcePort;
      return this;
    }

    public Builder sourcePort(String sourcePort) {
      return sourcePort(Output.of(sourcePort));
    }

    public Builder state(Output<String> state) {
      $.state = state;
      return this;
    }

    public Builder state(String state) {
      return state(Output.of(state));
    }

    public NetworkAclEgressArgs build() {
      if ($.action == null) {
        throw new MissingRequiredPropertyException("NetworkAclEgressArgs", "action");
      }
      if ($.state == null) {
        throw new MissingRequiredPropertyException("NetworkAclEgressArgs", "state");
      }
      return $;
    }
  }
}
