// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class StorageVolumeFileArgs extends com.pulumi.resources.ResourceArgs {

  public static final StorageVolumeFileArgs Empty = new StorageVolumeFileArgs();

  @Import(name = "append")
  private @Nullable Output<Boolean> append;

  public Optional<Output<Boolean>> append() {
    return Optional.ofNullable(this.append);
  }

  @Import(name = "content")
  private @Nullable Output<String> content;

  public Optional<Output<String>> content() {
    return Optional.ofNullable(this.content);
  }

  @Import(name = "createDirectories")
  private @Nullable Output<Boolean> createDirectories;

  public Optional<Output<Boolean>> createDirectories() {
    return Optional.ofNullable(this.createDirectories);
  }

  @Import(name = "directoryMode")
  private @Nullable Output<String> directoryMode;

  public Optional<Output<String>> directoryMode() {
    return Optional.ofNullable(this.directoryMode);
  }

  @Import(name = "gid")
  private @Nullable Output<Double> gid;

  public Optional<Output<Double>> gid() {
    return Optional.ofNullable(this.gid);
  }

  @Import(name = "mode")
  private @Nullable Output<String> mode;

  public Optional<Output<String>> mode() {
    return Optional.ofNullable(this.mode);
  }

  @Import(name = "sourcePath")
  private @Nullable Output<String> sourcePath;

  public Optional<Output<String>> sourcePath() {
    return Optional.ofNullable(this.sourcePath);
  }

  @Import(name = "targetPath", required = true)
  private Output<String> targetPath;

  public Output<String> targetPath() {
    return this.targetPath;
  }

  @Import(name = "uid")
  private @Nullable Output<Double> uid;

  public Optional<Output<Double>> uid() {
    return Optional.ofNullable(this.uid);
  }

  private StorageVolumeFileArgs() {}

  private StorageVolumeFileArgs(StorageVolumeFileArgs $) {
    this.append = $.append;
    this.content = $.content;
    this.createDirectories = $.createDirectories;
    this.directoryMode = $.directoryMode;
    this.gid = $.gid;
    this.mode = $.mode;
    this.sourcePath = $.sourcePath;
    this.targetPath = $.targetPath;
    this.uid = $.uid;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(StorageVolumeFileArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private StorageVolumeFileArgs $;

    public Builder() {
      $ = new StorageVolumeFileArgs();
    }

    public Builder(StorageVolumeFileArgs defaults) {
      $ = new StorageVolumeFileArgs(Objects.requireNonNull(defaults));
    }

    public Builder append(@Nullable Output<Boolean> append) {
      $.append = append;
      return this;
    }

    public Builder append(Boolean append) {
      return append(Output.of(append));
    }

    public Builder content(@Nullable Output<String> content) {
      $.content = content;
      return this;
    }

    public Builder content(String content) {
      return content(Output.of(content));
    }

    public Builder createDirectories(@Nullable Output<Boolean> createDirectories) {
      $.createDirectories = createDirectories;
      return this;
    }

    public Builder createDirectories(Boolean createDirectories) {
      return createDirectories(Output.of(createDirectories));
    }

    public Builder directoryMode(@Nullable Output<String> directoryMode) {
      $.directoryMode = directoryMode;
      return this;
    }

    public Builder directoryMode(String directoryMode) {
      return directoryMode(Output.of(directoryMode));
    }

    public Builder gid(@Nullable Output<Double> gid) {
      $.gid = gid;
      return this;
    }

    public Builder gid(Double gid) {
      return gid(Output.of(gid));
    }

    public Builder mode(@Nullable Output<String> mode) {
      $.mode = mode;
      return this;
    }

    public Builder mode(String mode) {
      return mode(Output.of(mode));
    }

    public Builder sourcePath(@Nullable Output<String> sourcePath) {
      $.sourcePath = sourcePath;
      return this;
    }

    public Builder sourcePath(String sourcePath) {
      return sourcePath(Output.of(sourcePath));
    }

    public Builder targetPath(Output<String> targetPath) {
      $.targetPath = targetPath;
      return this;
    }

    public Builder targetPath(String targetPath) {
      return targetPath(Output.of(targetPath));
    }

    public Builder uid(@Nullable Output<Double> uid) {
      $.uid = uid;
      return this;
    }

    public Builder uid(Double uid) {
      return uid(Output.of(uid));
    }

    public StorageVolumeFileArgs build() {
      if ($.targetPath == null) {
        throw new MissingRequiredPropertyException("StorageVolumeFileArgs", "targetPath");
      }
      return $;
    }
  }
}
