---
apiVersion: v1
data:
  members: |-
    v1|ServiceAccount|mesh-system|headscale-client
    v1|ServiceAccount|mesh-system|headscale-bootstrap
    v1|ServiceAccount|mesh-system|headscale-gateway
    rbac.authorization.k8s.io/v1|ClusterRole||headscale-client
    rbac.authorization.k8s.io/v1|ClusterRoleBinding||headscale-client
    rbac.authorization.k8s.io/v1|Role|mesh-system|headscale-bootstrap
    rbac.authorization.k8s.io/v1|RoleBinding|mesh-system|headscale-bootstrap
    v1|ConfigMap|mesh-system|headscale-config
    v1|ConfigMap|mesh-system|headscale-config-init-script
    v1|ConfigMap|mesh-system|headscale-env
    v1|Secret|mesh-system|headscale-client-auth
    v1|ConfigMap|mesh-system|headscale-bootstrap-script
    v1|ConfigMap|mesh-system|headscale-client-scripts
    v1|ConfigMap|mesh-system|headscale-acl
    v1|ConfigMap|mesh-system|headscale-derp
    v1|ConfigMap|mesh-system|headscale-extra-records
    v1|ConfigMap|mesh-system|headscale-gateway-script
    cilium.io/v2alpha1|CiliumL2AnnouncementPolicy||lan-policy
    apps/v1|Deployment|mesh-system|headscale
    v1|Service|mesh-system|headscale
    batch/v1|Job|mesh-system|headscale-bootstrap
    apps/v1|Deployment|mesh-system|headscale-gateway
    apps/v1|DaemonSet|mesh-system|headscale-client
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: headscale
  name: headscale.group
