apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headscale
  name: headscale-client-auth
  namespace: mesh-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYmxTL2Uvd0JmbEFSb1Ur
        VjJXRjdlM0pSUXhhcEJtUzcveWo3SWtnS3pVCkxoTUxLQ3F2UXY4NGo5TzBqeEl3
        N3RncFVWQTlHWUNmaktsUGRuNWxBNzAKLS0tIHcvbFd6eGd0VXkyNzhnTG9LMzdz
        OHdOSUJodW05SjhoSHNibE9QSmdhcVkKW1uhYJwr2eM5tN3a0mLlr5wkr2804vG5
        4MQn0GyoWn3zSZom5lKtpMnpm2ZA/AYL7Z52LmQ1dknrUYu18SF/yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVnRSWFVSSStEcVpGckdI
        bEkyV1RVbUk0QnJqS3VlRkFNcWJtQjZUSmpjCkIrWm9TOVZJekRwT3ZTdms0S3d4
        WUxOYUllbXA0NXRmb09JWHFoZVdRODAKLS0tIEY4bzU0MzVBa2c3UG5uUGpCNHlN
        dUdlQ1A3SHVoUTFWci9nbzFuYWlwd3MKQS29fEG+eR/5K3bxXQP0C4Kn8jLimMEj
        bYfxTun3qbVqM+RlZz8U4dSqgRUuQ8bC7pRCEnerKReCg/gGdeGXIA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T20:51:47Z"
  mac: ENC[AES256_GCM,data:0JQVL5oz3WUM3nFRyo0jQJ1L7t3Pa0uZ9X39UvTN1YOPtQmMfp/36mR3UTNVNfiDX1/IC93mgNkW6dtDuASP5LdYYuwpXap3VGJQfv97LbvpqN42fCIrXvcnr/X+PQ0vpTUeA7Ffexe+Yqtv3T1PSwqs8BPua9+2yzSvmIEsdwk=,iv:cnfDnu3aZdhfGDh9EleCjGJ6X0EUpj6WsYnDlePEi4o=,tag:fJ5tdGfX2hKpVFbU2NH23w==,type:str]
  version: 3.13.3
