apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headscale
  name: headscale-client-auth
  namespace: mesh-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R3FkYWpKS2JyVmhoTDcv
        ZVhNSk5kb0FnbTg3d0I5eUlGRVFodHNOTlFZCklnOWt2aXpKaVFzWDhYQmtpSmtT
        Tm54bi9FOEhLWG52SVJQQTNHblZSdzgKLS0tIFl4SDR3WXZMWEdvdGlqb3diRmFF
        dmpuWnlZNjBwV1BJQldqaTBMV2RGekkKL0Tnom4igA5elG0uqHCpBTAwXeiCWCo5
        ywYjaETuWRNFilV1HExiTAfAGe9ArEJrCeU4w5FP1mLmmY9G55W9Fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETmMvU3lIeUMrVHV1eGNz
        R2hsdEhyRTB0S3VKVkxqQlpUcDA5QTJNYmhVCkpqUWZHZ3pKWHZGRzV3VUtCS0gr
        L21uekYyZTE3dXc4bDBSQWNTS0hzRUkKLS0tIDVjeEM4T0FkN0lHM1VLOGo2WlBV
        VVNjS0JyY2xYUlU2OWhleEJQckEzd2MKiFderj84VZ1yFb8JNC1tS8h08OWrqbme
        LmBlqO4rVAQ7UypRokcWCKTOKG2OflbjTI9/rLryRUa8n2Yya57mfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T22:09:08Z"
  mac: ENC[AES256_GCM,data:E5Z/YS1cvl2+pQHXaXm8PRggYLEoP00t7N1NHEO5u0KziDfyBCOEWmmjulPj+xjWt+KqSiPz5Aa6h3eB/3wlAx1j8FzcvZxdibX4/5KKgJ6nyvbkASRcyR3j2FT+kZqALoNUI3fMCnB0+eag/gNwcKmgH9BxsUcfTnnY/uvbZAg=,iv:94Xwhazp0b/zzGSm4bVlhG+2YeynbV4AeL/4GwITGds=,tag:yXPVK+ZNGerQLfM8H9rmPA==,type:str]
  version: 3.13.3
