apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headscale
  name: headscale-client-auth
  namespace: mesh-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYXZZWWxRVytmU0xXVUhX
        YmM2WmdxdXNod0dhcXppdWlyVUdwUHQvZENzCnZhWHEvT1h5Z2tOSm1EN2h3VkRl
        MDEzM0NxN2xvTERXazdoSmpScFB6VTAKLS0tIFhGSDlWM1RGRGhlVnF4NlQrVnM3
        RDVLdlRLYWlHUEp5NVVxc1JpTit0MEEK/CVf/sMzkqxdrp/F7giokhPxHmSsMsiP
        UaS3FNNqFWDvbavhX8jbCVsZApikwjhoU/vdYH8wjwC9Cq6GXrPdeA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS0VRcC9taW1Ycmp2UWlB
        RUZSNmpRUTcraWp1UjVpdENRRFlLVUFMaEhFClV4K3dkVUhmd2Z1UHZFNmZtTm42
        MUNOZUVDdmhzWHllVjF0aUVJN3ZCNmcKLS0tIHdnOTM0OGlCRlhCeGxldXR3V2RN
        cTNHNWlnVkd5NC94aWY3ZWlKdy80akUKAWUbDZOWOlb00tCJnfIaVuJ7VLvjxfIl
        DiYRpjcOUZT329x8Pz2Nu3DQF/lIaKGoBimxzFVfsVk19dDRFfyUiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T20:46:02Z"
  mac: ENC[AES256_GCM,data:UUBtzBLT7BBEuKa8XU29e39Bp9WrUgAZjfOgBuEMWw4ev2rM8FroZvdS/6nt1xPv07vKJumOWzLEAYBQS3hYPZIg8gQXPgNH+q/x0lcUm5VFf615c4qFu0pI+6hRsrHlyB0k7hkaL/rrHx/2Iq04Uw71Tok6fHm6KWmq9zf5uyM=,iv:56IXGWvF1hgsiuRuhWtgZsna5P4Wnh8Z8B/RQAoG9n8=,tag:AOsAw2B8+0G7AVYToH2TQw==,type:str]
  version: 3.13.3
