---
apiVersion: v1
data:
  config.yaml: |
    server_url: http://headscale.hs.net:8080
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 0.0.0.0:50443
    grpc_allow_insecure: true

    tls:
      letsencrypt_hostname: ""
      letsencrypt_cache_dir: ""
      letsencrypt_challenge_type: ""
      cert_path: ""
      key_path: ""

    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key

    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48

    derp:
      server:
        enabled: false
      urls: []
      paths:
        - /etc/headscale/derp.yaml
      auto_update_enabled: false
      update_frequency: 24h

    disable_check_updates: true
    ephemeral_node_inactivity_timeout: 30m
    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite

    policy:
      mode: file
      path: /etc/headscale/acl.json

    dns:
      base_domain: hs.net
      nameservers:
        global:
          - 192.168.1.254
          - 1.1.1.1
          - 8.8.8.8
      extra_records_path: /var/lib/headscale/extra_records.json
      magic_dns: true

    log:
      format: text
      level: info
kind: ConfigMap
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headscale
  name: headscale-config
  namespace: mesh-system
