---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headscale
  labels:
    app: headscale-gateway
  name: headscale-gateway
  namespace: mesh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        flox.seedmatic.io/environment.tailscale: mesh/tailscale
        io.seedmatic.rke2lab/domain: mesh
        io.seedmatic.rke2lab/package: headscale
      labels:
        app: headscale-gateway
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - /scripts/gateway.sh
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              key: authkey
              name: headscale-client-auth
        envFrom:
        - configMapRef:
            name: headscale-env
        image: rke2lab/flox-carrier:0.1.0
        name: tailscale
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 500Mi
            memory: 256Mi
          requests:
            cpu: 50m
            ephemeral-storage: 100Mi
            memory: 64Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
          privileged: true
        volumeMounts:
        - mountPath: /dev/net/tun
          name: dev-net-tun
        - mountPath: /var/lib/tailscale
          name: tailscale-state
        - mountPath: /var/run/tailscale
          name: tailscale-socket
        - mountPath: /var/secrets
          name: authkey
          readOnly: true
        - mountPath: /scripts
          name: gateway-script
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: headscale-gateway
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: dev-net-tun
      - hostPath:
          path: /var/lib/tailscale
          type: DirectoryOrCreate
        name: tailscale-state
      - emptyDir: {}
        name: tailscale-socket
      - configMap:
          defaultMode: 493
          name: headscale-gateway-script
        name: gateway-script
      - name: authkey
        secret:
          items:
          - key: authkey
            path: authkey
          secretName: headscale-client-auth
