---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headscale
  labels:
    app: headscale-client
  name: headscale-client
  namespace: mesh-system
spec:
  selector:
    matchLabels:
      app: headscale-client
  template:
    metadata:
      annotations:
        flox.seedmatic.io/environment.tailscale: mesh/tailscale
        flox.seedmatic.io/environment.wait-for-headscale: mesh/headscale
        io.seedmatic.rke2lab/domain: mesh
        io.seedmatic.rke2lab/package: headscale
      labels:
        app: headscale-client
    spec:
      containers:
      - command:
        - /scripts/tailscale-client.sh
        env:
        - name: RKE2_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              key: authkey
              name: headscale-client-auth
        - name: TS_STATE_DIR
          value: /var/lib/tailscale
        - name: TS_SOCKET
          value: /var/run/tailscale/tailscaled.sock
        - name: TS_USERSPACE
          value: "true"
        - name: TS_KUBE_SECRET
          value: ""
        envFrom:
        - configMapRef:
            name: headscale-env
        image: rke2lab/flox-carrier:0.1.0
        name: tailscale
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 256Mi
            memory: 256Mi
          requests:
            cpu: 50m
            ephemeral-storage: 64Mi
            memory: 64Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
          privileged: true
        volumeMounts:
        - mountPath: /dev/net/tun
          name: dev-net-tun
        - mountPath: /var/lib/tailscale
          name: tailscale-state
        - mountPath: /var/run/tailscale
          name: tailscale-socket
        - mountPath: /var/secrets
          name: authkey
          readOnly: true
        - mountPath: /scripts
          name: client-scripts
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      initContainers:
      - command:
        - /scripts/wait-for-headscale.sh
        envFrom:
        - configMapRef:
            name: headscale-env
        image: rke2lab/flox-carrier:0.1.0
        name: wait-for-headscale
        volumeMounts:
        - mountPath: /scripts
          name: client-scripts
          readOnly: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: headscale-client
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: dev-net-tun
      - hostPath:
          path: /var/lib/tailscale
          type: DirectoryOrCreate
        name: tailscale-state
      - emptyDir: {}
        name: tailscale-socket
      - configMap:
          defaultMode: 493
          name: headscale-client-scripts
        name: client-scripts
      - name: authkey
        secret:
          items:
          - key: authkey
            path: authkey
          secretName: headscale-client-auth
