---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cicd-render-signing
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  force: true
  interval: 5m
  path: ./workloads/cicd/render-signing
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: rke2lab
  wait: true
