---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cicd-pac-secret.yml
- cicd-pac-webhook.yml
- cicd-render-pipeline.yml
- cicd-render-signing.yml
- cicd-repository.yml
- cicd-tekton-pipelines-crds.yml
- cicd-tekton-pipelines-workloads.yml
