---
apiVersion: v1
data:
  version: v0.81.1
kind: ConfigMap
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/package: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
  name: tekton-operator-info
  namespace: tekton-operator
