---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/package: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
  name: tekton-operator-info
  namespace: tekton-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-operator-info
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
