apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/package: tekton-pipelines
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
  name: tekton-operator-webhook-certs
  namespace: tekton-operator
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUXlSUjVmMko0T3hoQVlW
        RlQrdStVMlU5azFVVFU2Z1l2cXEyMk0ycTBrCndQNEdhVzNmRGZrcTdleTFjcko5
        L0oxQyt2bTZncU5XN3dLaEFRNVhPN28KLS0tIHJpV2hvdnMzL3BpbWQvMzd0VzNE
        WTdLalo1TytjbTU1Snlsb1RSejM5bFkKdgGiIoRl5RjC8ZgWPgM0tMB8SFrlMJSa
        Wr7TDGE8AW0Xa7pyqnE2X2FOAzzAg4UOlIImQlnp/xiRd7MBo65PGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK25zZnBoYUJvUUZQNkVs
        Umd4bWpiMmF0YktvNk5WQStVTHJRSzRjdTFzCk9kdEhMVmo1bjQ0bHIrVklLSGs5
        T2NPWE8rRlIvZ3M3VlhlUUt6dDI2V3MKLS0tIHpsK3VYRTU1SXhLS05YQWhJU2pL
        M290aUN2ZGd4SzEzNE9Sc2VuRjFHYkkK8j1aaXsUDma7RIdt//I7WWCXnihP3J3H
        r8hgkp8niDY3Z1mQeYMvq4mWTEdBYFZIZ7U8E7DNAh8TZJzDsIeRGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T22:25:47Z"
  mac: ENC[AES256_GCM,data:naH+99sgMeR6itBwvXLiQxV+fZhf4SI83OZMJwhz+m1RRmMm7wY9E2kj97W/6CS9nBeoi5bKj8hylbic0F7pETQimTFa7ucXeFluR84x3oFxrkIghxyManYAtAgkz7c2hFrPri043N+gn4ULoX/zi05UcIofsARlRB56N8E8OVc=,iv:dYM1uzY+h5m9xtP+P+Wa/8BJGQaZftxMmtX4I6sLedY=,tag:Ds5KimY0orDAAocT/jKlnA==,type:str]
  version: 3.13.3
