---
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/package: tekton-pipelines
  labels:
    app: tekton-pipelines-controller
    version: v0.81.1
  name: tekton-operator
  namespace: tekton-operator
spec:
  ports:
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: tekton-operator
    name: tekton-operator
