apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/package: tekton-pipelines
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
  name: tekton-operator-webhook-certs
  namespace: tekton-operator
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdlRoMDBJYU5uek1MV3BQ
        M1d3ZElRQkNnTFFtR3ltYmRoeUs3Uzczc1FBCmdBWDdzbzlnNUZ1K1Iram1ZWEFP
        S1l6M0VSZGR0Rk5JbnBxQ3doSUViY1UKLS0tIHZsSkNGY0JOQWgxcEltSEZkYUZ5
        ZkJNTUErMHhVNE9UTGg4ZXUzWVJvb0kKyC2A4zqGAAU9CNOtP/4jLVhbqIaq0TKG
        o9t2sMCCNVJM0vd6kp9kzxU9709tJFlrqhuv+wOvSKbTEe/elfL9Ww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Sy9KeFkzelRmSURoQTBU
        OGRobXNXa0JmL001ejZCcTBkemJQWTR4YldVCmVGdTVrMUJJZGw2YTYvZHBVL20r
        MjFWUjB3ZEphZXVwWnpORG0yRE52b3cKLS0tIHh4dGxtRGZXTklhMGp3Wlp2OXJW
        dE1mVFo0S0FOR1hOalAvbVNURUdjdjAKsXbWQ5LGbKA5Q9lQ2Mujq603B7uPvhhY
        QHSryD8lQj2cMUBpQjoYp94ldN/pMvFn8Grzk/1lUVhj/tfqwVbs3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-12T16:08:21Z"
  mac: ENC[AES256_GCM,data:1IVmR/cbmm0GpsimOCCWWPFAGOqwtieffmspm4LRL+jAMCEoo9Uo3yuZVVot3omWVjQ0CktkKO2G88kyf5tFRMUYO0zod+0WUQ2GX/RZsoYwO7BG/FBdmkazc5Mmvg6vnbNurQoSTTgx+6P2yuq7tSDDW88Tc8fjHNerMbic8t0=,iv:YiEzyso11Vi8NwFhbFwqVdw0CM5qrIWMoxVECVD7dbI=,tag:YGMwMcJrNBl/+Ger+24Y9A==,type:str]
  version: 3.13.3
