---
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/package: tekton-pipelines
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
    operator.tekton.dev/release: v0.81.1
    version: v0.81.1
  name: tekton-operator-webhook
  namespace: tekton-operator
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    app: tekton-operator
    name: tekton-operator-webhook
