apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cicd
    io.seedmatic.rke2lab/package: tekton-pipelines
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
  name: tekton-operator-webhook-certs
  namespace: tekton-operator
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WlZsYTJxang0T2phUWdJ
        TStob0hLMzZuVWhVU29XYUlmTkVNeVE0d1FJCnRmSFRQSmQ4KytBeS85V1lKTXp3
        Qjl1OVpSclE0UUNlUEx3VGpyQlVUZjgKLS0tIEhYQzZsNjN4L1JCaWpLRHF4eGdI
        ZE5ReGUrbWxsVTZQN2tydU9XSk01cVUKBklyu94t85lWv/UlYbBamg6MyFuXsndH
        hR8vyYFIPdlDyk2psfQIKGUYGsaanoQMTjqByni/jrY9w/6dfNm8tg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNVF4UXZNS0xGRDNHNERJ
        L2JYN0xxVEh2QzFWTVh2cVpLT3BMOTNHaWlrCm9CWWttalVxSlh1ZVA1OW1CUHN1
        QTF5ay9Fc2N0UXdpNkljamtqVXRwV1UKLS0tIFUwVEpTdjdsOEpsNkNVN2tGMDNQ
        MktwQXRJNG1tVFlCcEFuWHhLSGlXTmcKR65/9cRa4nq8hecG6/xFr0fZw6izsDIE
        xbZTNaHxtPe+lrxMAR8LeI759O1xctuFU3tZROEFDzfx5rFU6JQv7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k0tc4gmaqrk5df3ujja34gkqxstu0cye7fl7fktjeuua3yych3aqxfjlak
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T02:20:12Z"
  mac: ENC[AES256_GCM,data:6Q/DkUHefZ53QxAf93YLbUHnN/qE6D+YxACoGqIDMzygkIWrdtl/46+Ggq+G6zKfiJzKaSndEdxz4KvqrwMeqcCkUjq9XQmAxd8YnzuizFyLezpiP0lVdchQKJ+vty6POKTnsbR5DZfO4NAXPIfETKP6GvptEMArOMLiNAG6wR0=,iv:kJW7cVj0dbdTCuqxfax0J+a2BEten6rqCrYNS1JtjTw=,tag:0PUlq+2J+C2Z1tEKBSF7fA==,type:str]
  version: 3.13.3
