---
apiVersion: v1
data:
  members: |-
    tailscale.com/v1alpha1|ProxyClass||accept-routes
    tailscale.com/v1alpha1|ProxyGroup||egress
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: tailscale
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: egress
  name: egress.group
