---
apiVersion: v1
data:
  members: |-
    v1|Namespace||envoy-gateway-system
    v1|ServiceAccount|envoy-gateway-system|envoy-gateway-installer
    rbac.authorization.k8s.io/v1|ClusterRoleBinding||envoy-gateway-installer
    v1|ConfigMap|envoy-gateway-system|envoy-gateway-installer-script
    batch/v1|Job|envoy-gateway-system|envoy-gateway-installer-v1-9-0
    gateway.networking.k8s.io/v1|GatewayClass||envoy
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: networking
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: envoy-gateway
  name: envoy-gateway.group
