---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: rke2-adoption-controller
  name: rke2-adoption-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rke2-adoption-controller
subjects:
- kind: ServiceAccount
  name: rke2-adoption-controller
  namespace: rke2lab-system
