---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: cluster-api
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: rke2-adoption-controller
  name: rke2-adoption-controller
  namespace: rke2lab-system
