---
apiVersion: v1
data:
  members: ""
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    io.seedmatic.rke2lab/domain: gitops
    io.seedmatic.rke2lab/manifest-group: "true"
    io.seedmatic.rke2lab/package: githubapp
  name: githubapp.group
